<?
$title = 'Events';
$title = $this->_($title);
$this->headTitle($title, 'SET');
$items = $this->items;

$form = new Event\Form\EventUserForm();
$form
->setView($this)
->useSubFormGroup()
->setMethod('post')
->setAction($this->uri('/event/join/'))
->prepare();

$unjoinForm = clone $form;
$unjoinForm->setMethod('delete');


$eventSearchForm = $this->form ? $this->form : new Epic\Form\EventSearchForm();
$eventSearchForm->setView($this)
     ->setMethod('get')
     ->setAction($this->uri('/events/'))
     ->prepare();

$calendar = $this->calendar;
$week = $this->week;
$prevPath = $this->prevPath;
$nextPath = $this->nextPath;
$dayPath = $this->dayPath;

$jsEvents = array();
foreach($this->eventList as $eventDay){
    $jsEvents[] = array(
        'id' => $eventDay['id'],
        'title' => $eventDay['title'],
        'start' => $this->DateTime()->jsTime($eventDay['startDay'] . ' ' . $eventDay['startTime']),
        'end' => $this->DateTime()->jsTime($eventDay['endDay'] . ' ' . $eventDay['endTime']),
        //'allDay' => $eventDay['isFullDayEvent'] ? true : false,
        'allDay' => false,
        'url' => $this->uri('/event/' . $eventDay['urlName']),
    );
}
?>

<div class="container">
    <header class="event-header">
    <div class="row">
        <div class="span4">
            <h2><a href="<?=$this->uri('/events/')?>"><?=$this->_('Event');?></a></h2>
        </div><!--page main right end-->
        <div class="span8">
            <?=$this->widget('Epic', 'widgets/eventnav', $this->vars())?>
        </div><!--page main left end-->
    </div>
    </header>
</div>
<div class="container">
    <div class="page-bg">
        <div class="row">
            <div class="span4">
                <?=$this->widget('Epic', 'widgets/eventside', $this->vars())?>
            </div><!--page main right end-->
            <div class="span8">
                <div class="event-main">
                    <div id="calendar-day"></div>
                    <?if(0):?>
                    <div id="event-calendar-wrap">
                    <table class="event-calendar table table-bordered table-condensed table-striped hide">
                        <thead>
                            <tr>
                                <td class="prev">
                                    <a href="<?=$this->uri($prevPath, array('start' => $calendar['prev']['startDay']))?>"><i class="icon-large icon-chevron-left highlight"></i></a>
                                </td>
                                <td class="switch" colspan="5"><a href="<?=$this->uri($prevPath, array('start' => $calendar['today']['startDay']))?>"><?=$calendar['monthName']?> <?=$calendar['yearName']?></a></td>
                                <td class="next">
                                    <a href="<?=$this->uri($prevPath, array('start' => $calendar['next']['startDay']))?>"><i class="icon-large icon-chevron-right highlight"></i></a>
                                </td>
                            </tr>
                            <tr>
                                <?foreach($calendar['weekNames'] as $weekname):?>
                                <th class="dow"><?=$weekname?></th>
                                <?endforeach;?>
                            </tr>
                        </thead>
                        <tbody>
                            <?foreach($calendar['days'] as $week):?>
                            <tr>
                                <?foreach($week as $day):?>
                                <th  title="<?=$day['datedb']?>" class="day <?=$day['isAdd'] ? "old" : ''?> <?=$day['datedb'] < $calendar['today']['datedb'] ? 'passed' : ''?>">
                                    <?if($day['datedb'] == $calendar['today']['datedb']):?>
                                    <span class="today"><?=$day['day']?></span>
                                    <?else:?>
                                    <?=$day['day']?>
                                    <?endif?>
                                   
                                </th>
                                <?endforeach;?>
                            </tr>
                            <tr>
                                <?foreach($week as $day):?>
                                <td title="<?=$day['datedb']?>" class="day <?=$day['isAdd'] ? "old" : ''?> <?=$day['datedb'] < $calendar['today']['datedb'] ? 'passed' : ''?>  <?=$day['datedb'] == $calendar['today']['datedb'] ? 'today' : ''?>">
                                    <?if (isset($day['Events'])):?>
                                        <?foreach ($day['Events'] as $event):?>
                                        <a href="<?=$this->uri('/event/' . $event['urlName'])?>" class="label label-event" title="<?=$event['title']?>"><?=$event['title']?></a>
                                        <?endforeach;?>
                                    <?endif;?>
                                </td>
                                <?endforeach;?>
                            </tr>
                            <?endforeach;?>
                        </tbody>
                    </table>
                </div>
                <?endif?>

                    <script id="event-thumbnails" type="text/x-tmpl" data-url="<?=$this->uri('/data/event/', array('recommend' => 1,'rows' => 28))?>">
                    <div class="event-thumbnails">
                        <ul>
                            {% if(o.items.length > 0) { %}
                            {% for (var i=0, item; item=o.items[i]; i++) { %}
                                <li><a href="<?=$this->uri('/event/')?>{%=item.urlName%}">
                                {% if(item.File) { %}
                                    <img src="{%=eva.thumb(item.File.Thumb, 'c_fill,h_90,w_90')%}" alt="{%=item.title%}" />
                                {% }else{ %}
                                    <img src="<?=$this->assets('/module/epic/img/event-default.png')?>" alt="">
                                {% } %}
                                <div class="mask">{%=item.title%}</div>
                                </a></li>
                            {% } %}
                            {% } %}
                        </ul>
                    </div> 
                    </script>

                    <div class="event-grid">
                        <header class="event-grid-header">
                        <small class="pull-right"><?=$this->_('Feature Cities');?>: 
                            <a href="<?=$this->uri('/events/list/', array('city' => 'Paris','order' => 'timedesc'));?>">Paris</a>
                            <a href="<?=$this->uri('/events/list/', array('city' => 'London','order' => 'timedesc'));?>">London</a>
                            <a href="<?=$this->uri('/events/list/', array('city' => 'New York','order' => 'timedesc'));?>">New York</a>
                            <a href="<?=$this->uri('/events/list/', array('city' => 'Shanghai','order' => 'timedesc'));?>">Shanghai</a>
                        </small>
                        <div class="page-header border-header">
                            <h3><?=$this->_('New Events');?> </h3><a href="<?=$this->uri('/my/city/')?>" class="switch">[<span class="my-city"><?=$this->_('Switch City');?></span>]</a>
                        </div>
                        <ul class="event-new-nav nav nav-pills collapsed">
                            <li class="active"><a href="<?=$this->uri('/events/list/', array('order' => 'timedesc'));?>"><?=$this->_('All Cities');?></a> |</li>
                            <li><a href="<?=$this->uri('/events/list/', array('city' => 'mycity', 'order' => 'timedesc'));?>" class="my-city-url"><?=$this->_('My City');?></a> |</li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'dining','order' => 'timedesc'));?>">Dining</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'wine','order' => 'timedesc'));?>">Wine</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'food','order' => 'timedesc'));?>">Food</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'nightlife','order' => 'timedesc'));?>">Nightlife</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'culture','order' => 'timedesc'));?>">Culture</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'cocktail','order' => 'timedesc'));?>">Cocktail</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'tasting','order' => 'timedesc'));?>">Tasting</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'cooking','order' => 'timedesc'));?>">Cooking</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'education','order' => 'timedesc'));?>">Education</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'organic-biologic-food','order' => 'timedesc'));?>"><?=$this->_('Organic & Biologic food');?></a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'spirit','order' => 'timedesc'));?>">Spirit</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'travel','order' => 'timedesc'));?>">Travel</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'exhibition','order' => 'timedesc'));?>">Exhibition</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'other','order' => 'timedesc'));?>">Other</a> | </li>
                            <li class="more"><a href="#"><?=$this->_('More');?></a> </li>
                        </ul>
                        </header>
                        <div class="event-new-wrap loaded">
                        <script id="event-new" type="text/x-tmpl" data-url="<?=$this->uri('/data/event/', array('order' => 'timedesc','rows' => 6))?>">
                        <div class="event-new grid-3columns">
                            {% if(o.items.length > 0) { %}
                            {% for (var i=0, item; item=o.items[i]; i++) { %}
                            <div class="event media">
                                <a class="pull-left" href="<?=$this->uri('/event/')?>{%=item.urlName%}">
                                    {% if(item.File) { %}
                                    <img  src="{%=eva.thumb(item.File.Thumb, 'c_fill,h_90,w_90')%}" width="90" height="90" class="media-object img-rounded"/>
                                    {% } else { %}
                                    <img  src="<?=$this->assets('/module/epic/img/event-default.png')?>" width="90" height="90" class="media-object img-rounded"/>
                                    {% } %}
                                </a>
                                <div class="media-body">
                                    <h4 class="media-heading"><a href="<?=$this->uri('/event/')?>{%=item.urlName%}">{%=item.title%}</a></h4>
                                    <div class="media">
                                        <p class="lowlight"><?=$this->_('City');?> : {%=item.city%}.</p>
                                        <p class="lowlight"><?=$this->_('Date');?> : {%=item.startDay%}.</p>
                                        <p class="lowlight">{%=item.Count.memberCount%} <?=$this->_('members joined');?>.</p>
                                    </div>
                                </div>
                            </div>
                            {% } %}
                            {% } %}
                        </div>
                        </script>
                        </div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                        <div class="event-new-wrap"></div>
                    </div>

                    <div class="event-grid">
                        <header class="event-grid-header">
                        <div class="page-header border-header">
                            <h3><?=$this->_('Feature Events');?></h3>
                        </div>
                        <ul class="event-feature-nav nav nav-pills  collapsed">
                            <li class="active"><a href="<?=$this->uri('/events/list/', array('order' => 'memberdesc'));?>"><?=$this->_('All Cities');?></a> |</li>
                            <li><a href="<?=$this->uri('/events/list/', array('city' => 'mycity', 'order' => 'memberdesc'));?>" class="my-city-url"><?=$this->_('My City');?></a> |</li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'dining','order' => 'timedesc'));?>">Dining</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'wine','order' => 'timedesc'));?>">Wine</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'food','order' => 'timedesc'));?>">Food</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'nightlife','order' => 'timedesc'));?>">Nightlife</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'culture','order' => 'timedesc'));?>">Culture</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'cocktail','order' => 'timedesc'));?>">Cocktail</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'tasting','order' => 'timedesc'));?>">Tasting</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'cooking','order' => 'timedesc'));?>">Cooking</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'education','order' => 'timedesc'));?>">Education</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'organic-biologic-food','order' => 'timedesc'));?>"><?=$this->_('Organic & Biologic food');?></a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'spirit','order' => 'timedesc'));?>">Spirit</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'travel','order' => 'timedesc'));?>">Travel</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'exhibition','order' => 'timedesc'));?>">Exhibition</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('category' => 'other','order' => 'timedesc'));?>">Other</a> | </li>
                            <li class="more"><a href="#"><?=$this->_('More');?></a> </li>
                        </ul>
                        </header>
                        
                        <div class="event-feature-wrap">
                        <script id="event-feature" type="text/x-tmpl" data-url="<?=$this->uri('/data/event/', array('order' => 'memberdesc','rows' => 6))?>">
                            <div class="event-feature grid-2columns">
                            {% if(o.items.length > 0) { %}
                            {% for (var i=0, item; item=o.items[i]; i++) { %}
                            <div class="event media">
                                <a class="pull-left" href="<?=$this->uri('/event/')?>{%=item.urlName%}">
                                    {% if(item.File) { %}
                                        <img  src="{%=eva.thumb(item.File.Thumb, 'c_fill,h_90,w_90')%}" width="90" height="90" class="media-object img-rounded"/>
                                    {% } else { %}
                                    <img  src="<?=$this->assets('/module/epic/img/event-default.png')?>" width="90" height="90" class="media-object img-rounded"/>
                                    {% } %}
                                </a>
                                <div class="media-body">
                                    <h4 class="media-heading"><a href="<?=$this->uri('/event/')?>{%=item.urlName%}">{%=item.title%}</a></h4>
                                    <div class="media">
                                        <p class="lowlight">City : {%=item.city%}.</p>
                                        <p class="lowlight">Date : {%=item.startDay%}.</p>
                                        <p class="lowlight">{%=item.Count.memberCount%} members joined.</p>
                                    </div>
                                </div>
                            </div>
                            {% } %}
                            {% } %}
                        </div>
                        </script>
                        </div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                        <div class="event-feature-wrap"></div>
                    </div>



                </div><!--event main end-->
            </div><!--page main left end-->
        </div>
    </div><!-- page-bg end-->
</div><!--container end-->

<script>
eva.ready(function(){
        $(".event-new-nav li:not(:last) a").on('click', function(){
                var link = $(this);
                var index = link.parent().index();
                var wraps = $(".event-new-wrap");
                $(".event-new-nav li").removeClass('active');
                link.parent().addClass('active');
                if(wraps.eq(index).hasClass('loaded')) {
                        wraps.hide();
                        wraps.eq(index).show();
                } else {
                    wraps.eq(index).load($(this).attr('href') + ' .event-list', function(){
                        wraps.hide();
                        wraps.eq(index).addClass('loaded').show();
                    });
                }
                return false;
        });

        $(".more a").on('click', function(){
                $(this).parentsUntil('.nav').parent().removeClass('collapsed');
                return false;
        });

        $(".event-feature-nav li:not(:last) a").on('click', function(){
                var link = $(this);
                var index = link.parent().index();
                var wraps = $(".event-feature-wrap");
                $(".event-feature-nav li").removeClass('active');
                link.parent().addClass('active');
                if(wraps.eq(index).hasClass('loaded')) {
                        wraps.hide();
                        wraps.eq(index).show();
                } else {
                    wraps.eq(index).load($(this).attr('href') + ' .event-list', function(){
                        wraps.hide();
                        wraps.eq(index).addClass('loaded').show();
                    });
                }
                return false;
        });


        var viewCalendar = function(){
                var calendar = $('#calendar-day');
                var formatDate = function(input) {
                        function padZeroLeft(s, l) {
                                s = String(s);
                                for (var i = 0; i < l - s.length; i++){
                                        s = '0' + s;
                                }
                                return s;
                        }
                        return input.getFullYear() + '-' + (padZeroLeft(input.getMonth() + 1, 2)) + '-' + padZeroLeft(input.getDate(), 2);
                };
                var initEvents = <?=\Zend\Json\Json::encode($jsEvents)?>;
                var inited = false;
                var options = {
                        header: {
                                left: 'prev',
                                center: 'title',
                                right: 'next'
                        },
                        editable: false,
                        defaultView : 'month',
                        events: function(start, end, callback) {
                                if(!inited){
                                    inited = true;
                                    return callback(initEvents);
                                }
                                $.ajax({
                                        url: '/data/event',
                                        dataType: 'json',
                                        data: {
                                                afterStartDay: formatDate(start),
                                                beforeStartDay: formatDate(end)
                                        },
                                        success: function(data) {
                                                var items = data.items;
                                                var events = [];
                                                for(var i in items){
                                                    var item = items[i];
                                                    events.push({
                                                            id : item.id,
                                                            title : item.title,
                                                            start : item.startDay + ' ' + item.startTime,
                                                            end : item.endDay + ' ' + item.endTime,
                                                            //allDay : item.isFullDayEvent == '1' ? true : false,
                                                            allDay : false,
                                                            url : eva.d('/event/' + item.urlName)
                                                    });
                                                }
                                                callback(events);
                                        }
                                });
                        }
                    };

                calendar.fullCalendar(options);
                calendar.hide();
                $(".nav-week li a").on('click', function(){
                        var handler = $(this);
                        var index = handler.parent().index();
                        if(handler.hasClass('onShow')) {
                                calendar.fadeOut();
                                $(".event-thumbnails").fadeIn();
                        } else {
                                calendar.show();
                                if(index == 7){
                                        calendar.fullCalendar( 'changeView', 'month' );
                                } else {
                                        calendar.fullCalendar( 'changeView', 'agendaDay' );
                                        var gotoDate = new Date(Date.parse(handler.attr('data-date')));
                                        calendar.fullCalendar( 'gotoDate', gotoDate.getFullYear(), gotoDate.getMonth(), gotoDate.getDate() );
                                }
                                calendar.hide();
                                calendar.fadeIn();
                                $(".event-thumbnails").fadeOut();
                        }
                        $(".nav-week li:not(:eq(" + index + ")) a").removeClass('onShow');
                        handler.toggleClass('onShow');

                        return false;
                });
        };
        eva.loadcss(eva.s('/lib/js/jquery/fullcalendar/fullcalendar.css'));
        eva.loader(eva.s([
        '/lib/js/jquery/fullcalendar/fullcalendar.js',
        '/lib/js/moment/moment.js'
        ]), viewCalendar);

});
</script>
