/**
 * EvaEngine
 *
 * @link      https://github.com/AlloVince/eva-engine
 * @copyright Copyright (c) 2012 AlloVince (http://avnpc.com/)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 * @package   Eva_Api.php
 * @author    AlloVince
 */

namespace Eva\Form;

/**
 * Eva Form will automatic combination form Elements & Validators & Filters
 * Also allow add sub forms and unit validate
 * 
 * @category   Eva
 * @package    Eva_Form
 */
class <?=$this->formClassName?> extends \Zend\Form\Form
{
    /**
     * Form basic elements
     *
     * @var array
     */
    protected $baseElements = <?=$this->codeIndent($this->elementsCode)?>;

    /**
     * Form basic Validators
     *
     * @var array
     */
    protected $baseFilters = <?=$this->codeIndent($this->validatorsCode)?>;
}
