<?
$title = $this->_('EvaEngine');
$this->headTitle($title, 'SET');
?>
<div class="container">

    <div class="row" id="header">
        <div class="span12">
            <h1><a href="#"><span id="it">EvaEngine</span><span id="beta">Dev</span></a></h1>
        </div><!--end span12-->        
    </div><!--end row-->

    <div class="row" id="catchycontent">
        <div class="span12">
            <h2>a php development engine, coming soon...</h2>
            <p>EvaEngine is a PHP5 & Zend Framework 2.0 based development engine which is still under developing. <br />Building up websites like blog, social networking SNS, E-commerce in few minutes.</p>        
        </div><!--end span12-->            
    </div><!--end row-->

    <div class="row" id="subscribe">

        <div id="mc_embed_signup">
            <a class="btn btn-success btn-large" href="https://github.com/AlloVince/eva-engine">Fork EvaEngine on GitHub &raquo;</a>
        </div>
    </div><!--end row-->

    <div class="row" id="features">
        <div class="span3 divider">
            <div class="featureicon"><i class="icon-cogs"></i></div>
            <h3>Real Module Based</h3>
            <p>Every feature is an independent module in EvaEngine. What you need is just pick out features when you need them.</p>
        </div>        
        <div class="span3 divider">
            <div class="featureicon"><i class="icon-flag"></i></div>
            <h3>Everything is RESTFul</h3>
            <p>In EvaEngine, everything is designed by RESTFul style, you could build up a RESTFul webserice easily.</p>
        </div>       
        <div class="span3 divider">
            <div class="featureicon"><i class="icon-magnet"></i></div>
            <h3>Plugins and Customize</h3>
            <p>EvaEngine is complete follow Zend Framework 2.0 code standards, it make developers easy to add features and install 3rd-part modules.</p>
        </div>
        <div class="span3">
            <div class="featureicon"><i class="icon-cloud"></i></div>
            <h3>Power from Cloud</h3>
            <p>EvaEngine support more than 20 third-part websites login and API functions. As well as import/backup data on cloud.</p>
        </div>
    </div><!--end row-->

</div><!--end container-->     
