<ul class="nav nav-tabs nav-stacked">
    <li data-highlight-url="^/account/profile/?$"><a href="<?=$this->uri('/account/profile/')?>"><i class="icon-user"></i> <?=$this->_('Profile');?></a></li>
    <li data-highlight-url="^/account/header/?$"><a href="<?=$this->uri('/account/header/')?>"><i class="icon-camera"></i> <?=$this->_('Header');?></a></li>
    <li data-highlight-url="^/account/setting/?$"><a href="<?=$this->uri('/account/setting/')?>"><i class="icon-cogs"></i> <?=$this->_('Setting');?></a></li>
    <li data-highlight-url="^/account/privacy/?$"><a href="<?=$this->uri('/account/privacy/')?>"><i class="icon-eye-close"></i> <?=$this->_('Privacy');?></a></li>
    <li data-highlight-url="^/account/notification/?$"><a href="<?=$this->uri('/account/notification/')?>"><i class="icon-bell-alt"></i> <?=$this->_('Notification');?></a></li>
    <li data-highlight-url="^/account/membership/?$"><a href="<?=$this->uri('/account/membership/')?>"><i class="icon-trophy"></i> <?=$this->_('Membership');?></a></li>
    <li data-highlight-url="^/account/(import|addfriend|invite)"><a href="<?=$this->uri('/account/import/')?>"><i class="icon-search"></i> <?=$this->_('Find Friends');?></a></li>
    <li data-highlight-url="^/account/corporate/?$"><a href="<?=$this->uri('/account/corporate/')?>"><i class="icon-group"></i> <?=$this->_('Corporate');?></a></li>
</ul>
