<nav class="nav-week">
<ul>
    <?foreach($week as $day):?>
    <li>
    <a href="<?=$this->uri('/events/list/', array('beforeStartDay' => $day['datedb'],'afterStartDay' => $day['datedb']))?>" class="<?if($day['datedb'] == $calendar['today']['datedb']):?>active<?endif?>" data-date="<?=$this->Datetime()->jsTime($day['datedb'])?>">
        <span class="day"><?=$this->_($this->Datetime($day['datedb'], null, 'D'))?></span><span class="date"><?=$this->Datetime($day['datedb'], null, 'jS M')?></span>
    </a>
    </li>
    <?endforeach?>
    <li><a href="#"><i class="icon-calendar"></i></a></li>
</ul>
</nav>
