<?
$user = $this->user;
?>
<div class="event-side">
    <?if($user):?>
    <div class="usercard media">
        <a class="pull-left" href="<?=$this->uri('/user/' . $user['userName'])?>">
            <img src="<?=$user['Avatar'] ? $this->thumb($user['Avatar']['Thumb'], array('h_120', 'w_120', 'c_fill')) :  $this->assets('/module/epic/img/default_avatar.png')?>" alt=""  width="120" height="120" class="media-object"/>
        </a>
        <div class="media-body">
            <h4 class="media-heading"><a href="<?=$this->uri('/user/' . $user['userName'])?>"><?=$user['userName']?></a></h4>
            <h5><?=$this->_('Joined Events');?>: <span class="highlight"><?=$user['EventCount']['eventCount']?></span></h5>
            <div class="media">
                <a id="create-new-event" href="<?=$this->uri('/events/create/')?>" class="btn btn-gray"><i class="icon-plus"></i> <?=$this->_('Schedule an Event');?></a>
                <p class="lowlight"><?=$this->_('Share your life');?></p>
            </div>
        </div>
    </div> 
    <?endif?>

<script id="event-subscription" type="text/x-tmpl" data-url="<?=$this->uri('/data/newsletter/')?>"  data-url-forlogin="1">
    <div class="event-subscription">
        <p><?=$this->_('Receive free new event notifications');?>:</p>
        <form method="post" action="/core/newsletter/">
            <?=$this->callback()?>
            {% if(o.item.user_id) { %} 
            <input type="hidden" value="delete" name="_method"> 
            <button class="btn btn-orange"><i class="icon-mini icon-envelope-alt"></i> <?=$this->_('Unsubscription Newsletters');?></button>
            {% }else{ %}
            <input type="hidden" value="post" name="_method"> 
            <button class="btn btn-orange"><i class="icon-mini icon-envelope-alt"></i> <?=$this->_('Subscription Newsletters');?></button>
            {% } %}
        </form>
    </div>
</script>

    <script id="side-blog-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/eventuser/', array())?>">
        <div class="page-header border-header">
            <h4><?=$this->_('Featured Events Host');?></h4>
        </div>
        <div class="side-blog-list">
            {% if(o.items.length > 0) { %}
                {% for (var i=0, item; item=o.items[i]; i++) { %}
                    <div class="item">
                        <a href="<?=$this->uri('/user/')?>{%=item.userName%}" title="" class="item-absolute imgdelay figure userface">
                        {% if(item.Avatar.Thumb) { %}
                            <img src="{%=eva.thumb(item.Avatar.Thumb, 'c_fill,h_50,w_50')%}" alt="" class="img-rounded" width="50" height="50" />
                        {% } else { %}
                            <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="img-rounded" width="50" height="50" />
                        {% } %}
                        </a>
                        <div class="item-inline item-text">
                            <div class="text-content">
                                <div class="item-title">
                                    <a href="<?=$this->uri('/user/')?>{%=item.userName%}">{%=item.userName%}</a>
                                </div>
                                <p>Host <span class="highlight">{%=item.EventCount%}</span> Events</p>
                            </div>
                        </div>
                    </div>
                    {% } %}
                {% } %}
        </div>
    </script>
    <?=$this->widget('Epic', 'components/ad_event')?>
</div>
