<div class="profile-side">
    <div class="calendar calendar-mini">
        <div class="calendar-wrap">

        </div>
        <div class="calendar-caption">
            <i class="icon-stop green"></i><?=$this->_('Coming Events');?> 
            <i class="icon-stop brown"></i><?=$this->_('Finished Events');?> 
            <i class="icon-stop orange"></i><?=$this->_('Today');?> 
        </div>
    </div><!--calendar end-->

<script id="side-subscription" type="text/x-tmpl" data-url="<?=$this->uri('/data/newsletter/')?>" data-url-forlogin="1">
    <div class="side-subscription">
        <p><?=$this->_('Subscribe here to receive our free e-newsletters and notifications');?>:</p>
        <form method="post" action="/core/newsletter/">
            <?=$this->callback()?>
            {% if(o.item.user_id) { %} 
            <input type="hidden" value="delete" name="_method"> 
            <button class="btn btn-orange btn-block"><i class="icon-mini icon-envelope-alt"></i> <?=$this->_('Unsubscription Newsletters');?></button>
            {% }else{ %}
            <input type="hidden" value="post" name="_method"> 
            <button class="btn btn-orange btn-block"><i class="icon-mini icon-envelope-alt"></i> <?=$this->_('Subscription Newsletters');?></button>
            {% } %}
        </form>
    </div>
</script>

<script id="side-friend-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/friend/', array('user_id' => $this->user['id']))?>" >
<div class="page-header border-header">
    <!--
    <small class="pull-right"><a href="<?=$this->uri('/my/friend/')?>"><?=$this->_('View All');?></a></small>
    -->
    <h4><?=$this->_('Friends');?> ({% if(o.paginator) { %}{%=o.paginator.rowCount%}{% } else { %} 0 {% } %})</h4>
</div>
<div class="side-user-list">
    {% if(o.items.length > 0) { %}
    <ul class="thumbnails">
    {% for (var i=0, item; item=o.items[i]; i++) { %}
        <li>
        <a class="thumbnail" href="<?=$this->uri('/user/')?>{%=item.User.userName%}">
        {% if(item.User.Avatar.Thumb) { %}
            <img src="{%=eva.thumb(item.User.Avatar.Thumb, 'c_fill,h_30,w_30')%}" alt="" class="img-rounded" width="30" height="30" />
        {% } else { %}
            <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="img-rounded" width="30" height="30" />
        {% } %}
        </a>
        </li>
    {% } %}
    </ul>
    {% } %}
</div>
</script>

<script id="side-blog-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/blog/', array('user_id' => $this->user['id'], 'rows' => 4))?>">
<div class="page-header border-header">
    <small class="pull-right"><a href="<?=$this->uri('/user/' . $this->user['userName'] . '/blog/')?>"><?=$this->_('View All');?></a></small>
    <h4><?=$this->_('Blogs');?>  ({% if(o.paginator) { %}{%=o.paginator.rowCount%}{% } else { %} 0 {% } %})</h4>
</div>
<div class="side-blog-list">
{% if(o.items.length > 0) { %}
{% for (var i=0, item; item=o.items[i]; i++) { %}
<div class="item">
    <a href="<?=$this->uri('/user/')?>{%=item.User.userName%}" title="" class="item-absolute imgdelay figure userface">
        {% if(item.User.Avatar.Thumb) { %}
        <img src="{%=eva.thumb(item.User.Avatar.Thumb, 'c_fill,h_50,w_50')%}" alt="" class="img-rounded" width="50" height="50" />
        {% } else { %}
        <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="img-rounded" width="50" height="50" />
        {% } %}
    </a>
    <div class="item-inline item-text">
        <div class="text-content">
            <div class="item-title">
                <a href="<?=$this->uri('/user/')?>{%=item.User.userName%}/blog/{%=item.urlName%}">{%=item.title%}</a>
            </div>
            <p>{%=item.Text.Preview%}</p>
        </div>
    </div>
</div>
{% } %}
{% } %}
</div>
</script>


<script id="side-event-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/event/', array('user_id' => $this->user['id']))?>">
<div class="page-header border-header">
    <small class="pull-right"><a href="<?=$this->uri('/user/' . $this->user['userName'] . '/events/')?>"><?=$this->_('View All');?></a></small>
    <h4><?=$this->_('Events');?>  ({% if(o.paginator) { %}{%=o.paginator.rowCount%}{% } else { %} 0 {% } %})</h4>
</div>
<div class="side-event-list">
{% if(o.items.length > 0) { %}
{% for (var i=0, item; item=o.items[i]; i++) { %}
<div class="item">
    <a href="<?=$this->uri('/user/')?>{%=item.User.userName%}" title="" class="item-absolute imgdelay figure userface">
        {% if(item.User.Avatar.Thumb) { %}
        <img src="{%=eva.thumb(item.User.Avatar.Thumb, 'c_fill,h_50,w_50')%}" alt="" class="img-rounded" width="50" height="50" />
        {% } else { %}
        <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="img-rounded" width="50" height="50" />
        {% } %}    
    </a>
    <div class="item-inline item-text">
        <div class="text-content">
            <div class="item-title">
                <a href="<?=$this->uri('/event/')?>{%=item.urlName%}">{%=item.title%}</a>
            </div>
        </div>
    </div>
</div>
{% } %}
{% } %}
</div>
</script>

<script id="side-album-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/album/', array('user_id' => $this->user['id'], 'rows' => 8))?>">
<div class="page-header border-header">
    <small class="pull-right"><a href="<?=$this->uri('/user/' . $this->user['userName'] . '/albums/')?>"><?=$this->_('View All');?></a></small>
    <h4><?=$this->_('Albums');?>  ({% if(o.paginator) { %}{%=o.paginator.rowCount%}{% } else { %} 0 {% } %})</h4>
</div>
<div class="side-album-list">
    <ul class="thumbnails">
    {% if(o.items.length > 0) { %}
    {% for (var i=0, item; item=o.items[i]; i++) { %}
        <li>
            <a class="thumbnail" href="<?=$this->uri('/user/')?>{%=item.user_name%}/albums/{%=item.urlName%}">
                {% if(item.Cover.Thumb) { %}
                    <img src="{%=eva.thumb(item.Cover.Thumb, 'c_fill,h_65,w_65')%}" alt="" width="65" height="65" class="img-rounded"/>
                {% }else{ %}
                    <img src="<?=$this->assets('/module/epic/img/album-default.png')?>" alt="" width="65" height="65" class="img-rounded" />
                {% } %}
            </a>
        </li>
    {% } %}
    {% } %}
        </ul>
    </div>
</div>
</script>


<script id="side-group-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/group/', array('user_id' => $this->user['id'], 'rows' => 12))?>">
<div class="page-header border-header">
    <small class="pull-right"><a href="<?=$this->uri('/user/' . $this->user['userName'] . '/groups/')?>"><?=$this->_('View All');?></a></small>
    <h4><?=$this->_('Groups');?>  ({% if(o.paginator) { %}{%=o.paginator.rowCount%}{% } else { %} 0 {% } %})</h4>
</div>
<div class="side-group-list">
    <ul class="thumbnails">
    {% if(o.items.length > 0) { %}
    {% for (var i=0, item; item=o.items[i]; i++) { %}
        <li>
            <a class="thumbnail" href="<?=$this->uri('/group/')?>{%=item.groupKey%}">
                {% if(item.File) { %}
                    <img src="{%=eva.thumb(item.File.Thumb, 'c_fill,h_50,w_50')%}" alt="" width="50" height="50" class="item-absolute imgdelay figure userface" />
                {% }else{ %}
                    <img src="<?=$this->assets('/module/epic/img/group-default.png')?>" alt="" width="50" height="50" class="item-absolute imgdelay figure userface" />
                {% } %}
            </a>
        </li>
    {% } %}
    {% } %}
        </ul>
    </div>
</div>
</script>

    <?if($this->viewAsGuest):?>
    <?=$this->widget('Epic', 'components/ad_user')?>
    <?else:?>
    <?=$this->widget('Epic', 'components/ad_home')?>
    <?endif?>
</div><!--profile-side end-->
