<div class="page-header border-header">
    <h4><?=$this->_('Toolbox');?></h4>
</div>

<div class="side-toolbox">
<ul class="nav nav-tabs nav-stacked">
<li><a href="<?=$this->uri('/group/NfuQFr')?>" /><img src="<?=$this->assets('/module/epic/img/discussion.png')?>" alt=""> Go To Discussion </a></li>
<li><a href="<?=$this->uri('/users/list/')?>"><img src="<?=$this->assets('/module/epic/img/friend_find.png')?>" alt=""> Find Friends </a></li>
<li><a href="<?=$this->uri('/account/import/')?>"><img src="<?=$this->assets('/module/epic/img/friend_invite.png')?>" alt=""> Invite Friends </a></li>
<li><a href="<?=$this->uri('/groups/list/')?>"><img src="<?=$this->assets('/module/epic/img/group.png')?>" alt=""> Find Group </a></li>
<li><a href="<?=$this->uri('/dashboard/')?>"><img src="<?=$this->assets('/module/epic/img/dashboard.png')?>" alt=""> Back to DashBoard </a></li>
<li><a href="<?=$this->uri('/')?>"><?=$this->widget('Epic', 'widgets/googletranslate')?></a></li>
</ul>
</div>
