<script id="side-blog-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/blog/', array('rows' => 5))?>">
<div class="page-header border-header">
    <h4><?=$this->_('New Blogs');?></h4>
</div>
<div class="side-blog-list">
{% if(o.items.length > 0) { %}
{% for (var i=0, item; item=o.items[i]; i++) { %}
<div class="item">
    <a href="<?=$this->uri('/user/')?>{%=item.User.userName%}" title="" class="item-absolute imgdelay figure userface">
        {% if(item.User.Avatar.Thumb) { %}
        <img src="{%=eva.thumb(item.User.Avatar.Thumb, 'c_fill,h_50,w_50')%}" alt="" class="img-rounded" width="50" height="50" />
        {% } else { %}
        <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="img-rounded" width="50" height="50" />
        {% } %}
    </a>
    <div class="item-inline item-text">
        <div class="text-content">
            <div class="item-title">
                <a href="<?=$this->uri('/user/')?>{%=item.User.userName%}/blog/{%=item.urlName%}">{%=item.title%}</a>
            </div>
            <p>{%=item.Text.Preview%}</p>
        </div>
    </div>
</div>
{% } %}
{% } %}
</div>
</script>

<script id="side-friend-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/friend/')?>" data-url-forlogin="1">
<div class="page-header border-header">
    <small class="pull-right"><a href="<?=$this->uri('/my/friend/')?>"><?=$this->_('View All');?></a></small>
    <h4><?=$this->_('My Friends');?></h4>
</div>
<div class="side-user-list">
    {% if(o.items.length > 0) { %}
    <ul class="thumbnails">
    {% for (var i=0, item; item=o.items[i]; i++) { %}
        <li>
        <a class="thumbnail" href="<?=$this->uri('/user/')?>{%=item.User.userName%}">
        {% if(item.User.Avatar.Thumb) { %}
            <img src="{%=eva.thumb(item.User.Avatar.Thumb, 'c_fill,h_30,w_30')%}" alt="" class="img-rounded" width="30" height="30" />
        {% } else { %}
            <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="img-rounded" width="30" height="30" />
        {% } %}
        </a>
        </li>
    {% } %}
    </ul>
    {% } %}
</div>
</script>

<script id="side-event-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/event/', array('rows' => 5))?>"  data-url-forlogin="1">
<div class="page-header border-header">
    <small class="pull-right"><a href="<?=$this->uri('/my/event/')?>"><?=$this->_('View All');?></a></small>
    <h4><?=$this->_('My Events');?>  ({% if(o.paginator) { %}{%=o.paginator.rowCount%}{% } else { %} 0 {% } %})</h4>
</div>
<div class="side-event-list">
{% if(o.items.length > 0) { %}
{% for (var i=0, item; item=o.items[i]; i++) { %}
<div class="item">
    <a href="<?=$this->uri('/user/')?>{%=item.User.userName%}" title="" class="item-absolute imgdelay figure userface">
        {% if(item.User.Avatar.Thumb) { %}
        <img src="{%=eva.thumb(item.User.Avatar.Thumb, 'c_fill,h_50,w_50')%}" alt="" class="img-rounded" width="50" height="50" />
        {% } else { %}
        <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="img-rounded" width="50" height="50" />
        {% } %}
    </a>
    <div class="item-inline item-text">
        <div class="text-content">
            <div class="item-title">
                <a href="<?=$this->uri('/event/')?>{%=item.urlName%}">{%=item.title%}</a>
            </div>
        </div>
    </div>
</div>
{% } %}
{% } %}
</div>
</script>


<script id="side-album-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/album/', array('rows' => 8))?>" data-url-forlogin="1">
<div class="page-header border-header">
    <small class="pull-right"><a href="<?=$this->uri('/my/album/')?>"><?=$this->_('View All');?></a></small>
    <h4><?=$this->_('My Albums');?>  ({% if(o.paginator) { %}{%=o.paginator.rowCount%}{% } else { %} 0 {% } %})</h4>
</div>
<div class="side-album-list">
    <ul class="thumbnails">
    {% if(o.items.length > 0) { %}
    {% for (var i=0, item; item=o.items[i]; i++) { %}
        <li>
            <a class="thumbnail" href="<?=$this->uri('/user/')?>{%=item.user_name%}/albums/{%=item.urlName%}">
                {% if(item.Cover.Thumb) { %}
                    <img src="{%=eva.thumb(item.Cover.Thumb, 'c_fill,h_65,w_65')%}" alt="" width="65" height="65" class="img-rounded"/>
                {% }else{ %}
                    <img src="<?=$this->assets('/module/epic/img/album-default.png')?>" alt="" width="65" height="65" class="img-rounded" />
                {% } %}
            </a>
        </li>
    {% } %}
    {% } %}
        </ul>
    </div>
</div>
</script>
    <?if(0):?>
    <div class="page-header border-header">
        <small class="pull-right"><a href="#"><?=$this->_('View All');?></a></small>
        <h4><?=$this->_('Albums');?></h4>
    </div>
    <div class="side-album-list">
        <ul class="thumbnails">
            <?for($i = 0; $i <6; $i++):?>
            <li>
            <a class="thumbnail" href="#">
                <img src="<?=$this->link('/assets/module/epic/css/img/food.jpg')?>" alt="" class="img-rounded" width="70" height="70" />
            </a>
            </li>
            <?endfor;?>
        </ul>
    </div>
    <?endif;?>

    <script id="side-group-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/group/', array('rows' => 12))?>"  data-url-forlogin="1">
<div class="page-header border-header">
    <small class="pull-right"><a href="<?=$this->uri('/my/group/')?>"><?=$this->_('View All');?></a></small>
    <h4><?=$this->_('My Groups');?>  ({% if(o.paginator) { %}{%=o.paginator.rowCount%}{% } else { %} 0 {% } %})</h4>
</div>
<div class="side-group-list">
    <ul class="thumbnails">
    {% if(o.items.length > 0) { %}
    {% for (var i=0, item; item=o.items[i]; i++) { %}
        <li>
            <a class="thumbnail" href="<?=$this->uri('/group/')?>{%=item.groupKey%}">
                {% if(item.File) { %}
                    <img src="{%=eva.thumb(item.File.Thumb, 'c_fill,h_50,w_50')%}" alt="" width="50" height="50" class="item-absolute imgdelay figure userface" />
                {% }else{ %}
                    <img src="{%=eva.s('/assets/module/epic/img/event-default.jpg')%}" alt="" width="50" height="50" class="item-absolute imgdelay figure userface" />
                {% } %}
            </a>
        </li>
    {% } %}
    {% } %}
        </ul>
    </div>
</div>
</script>


    <?=$this->widget('Epic', 'components/ad_setting')?>
