<? 
$title = $this->_('Feed');
$this->headTitle($title, 'SET');
if($this->form){
	$form = $this->form;
} else {
    $form = new Activity\Form\MessageCreateForm();
}
$item = $this->item;
$items = $this->items;
$form->useSubFormGroup()
     ->setMethod($item['id'] ? 'put' : 'post')
     ->setView($this)
     ->setAction($this->uri('/activity/'))
     ->prepare();
?>
<div class="container">

    <div class="activity-list vlist">
        <div class="item">
            <a href="<?=$this->uri('/user/' . $item['user_id'])?>" title="" class="item-absolute item-userface"><img src="<?=$this->gravatar($item['User']['email'])?>" alt="" class="img-rounded" width="60" height="60" /></a>
            <div class="item-inline item-text span6">
                <div class="item-content">
                    <div class="item-title"><a href="<?=$this->uri('/user/' . $item['user_id'])?>" class="item-user"><?=$item['User']['userName']?></a> Said:</div>
                    <p><?=$item['ContentHtml']?></p>
                    <?if($item['File']):?>
                    <div class="item-image">
                        <p><a href="<?=$item['File'][0]['Thumb']?>"><img src="<?=$this->thumb($item['File'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                    </div>
                    <?endif?>

                    <?if($item['ForwardActivity']): $subItem = $item['ForwardActivity'];?>
                    <div class="well">
                        <p><?=$subItem['ContentHtml']?></p>
                        <?if($subItem['File']):?>
                        <div class="item-image">
                            <p><a href="<?=$subItem['File'][0]['Thumb']?>"><img src="<?=$this->thumb($subItem['File'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                        </div>
                        <?endif?>
                        <div class="item-action">
                            <p class="pull-right"><a href="javascript:;" class="item-func comment" data-activity-comment="<?=$subItem['id']?>"><i class="icon-comment"></i> Comments (<span class="highlight"><?=$subItem['commentedCount']?></span>)</a></p>
                            <p class="pull-left">
                            <a href="<?=$this->uri('/feed/' . $subItem['messageHash'])?>" class="item-id"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($subItem['createTime'])?>" datetime="<?=$this->datetime()->isoTime($subItem['createTime'])?>"><?=$this->datetime($subItem['createTime'])?></time></a>
                            </p>
                        </div>
                    </div>
                    <?endif?>

                    <div class="item-action">
                        <p class="pull-right"><a href="javascript:;" class="item-func comment" data-activity-comment="<?=$item['id']?>"><i class="icon-comment"></i> Comments (<span class="highlight"><?=$item['commentedCount']?></span>)</a></p>
                        <p class="pull-right"><a href="#activity-form" class="item-func reference" data-activity-reference="<?=$item['id']?>" data-activity-text="@Sophia"><i class="icon-share-alt"></i> RT (<span class="highlight"><?=$item['transferredCount']?></span>)</a></p>
                        <p class="pull-left">
                        <a href="<?=$this->uri('/feed/' . $item['messageHash'])?>" class="item-id"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['createTime'])?>" datetime="<?=$this->datetime()->isoTime($item['createTime'])?>"><?=$this->datetime($item['createTime'])?></time></a>
                        </p>
                    </div>
                </div>

                <div class="item-sub-wrap">
                    <?if($item['commentedCount']):?>
                    <div class="item-sub-title">
                        <?=$item['commentedCount']?> Comments in Total
                    </div>
                    <?endif?>

                    <div class="item-sub-form">
                        <form <?=$this->formAttr($form)?> class="">
                            <?=$form->helper('messageType', 'formHidden', array('class' => '', 'value' => 'comment'))?>        
                            <?=$form->helper('reference_id', 'formHidden', array('class' => '', 'value' => $item['id']))?>
                            <fieldset class="form">
                                <div class="item-sub-textarea">
                                    <?=$form->helper('content', 'formTextarea', array('placeholder' => 'Add Comment'))?>        
                                </div>
                                <div class="item-absolute item-sub-submit">
                                    <button type="submit" class="btn btn-light-brown btn-large">Submit</button>
                                </div>
                            </fieldset>
                            <input name="callback" type="hidden" value="<?=$this->uri('/feed/' . $item['messageHash'])?>" />
                        </form>
                    </div>

                    <?foreach($items as $item):?>
                    <div class="item-sub">
                        <a href="<?=$this->uri('/user/' . $item['user_id'])?>" title="" class="item-absolute item-sub-userface"><img src="<?=$this->gravatar($item['User']['email'], 30)?>" alt="" class="img-rounded" width="30" height="30" /></a>
                        <div class="item-sub-content">
                            <div class="item-sub-title">
                                <a href="<?=$this->uri('/user/' . $item['user_id'])?>" class="item-sub-user"><?=$item['User']['userName']?></a>
                                <a href="<?=$this->uri('/feed/' . $item['messageHash'])?>" class="item-sub-id"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['createTime'])?>" datetime="<?=$this->datetime()->isoTime($item['createTime'])?>"><?=$this->datetime($item['createTime'])?></time></a>
                            </div>
                            <p><?=$item['ContentHtml']?></p>
                        </div>
                    </div>
                    <?endforeach?>

                </div>
            </div>
        </div>
    </div><!--activity-list end-->

</div>

<?=$this->widget('File', 'file/index')?>

<style>
    #fileupload-modal {
            position:absolute;
            margin:0;
            width:250px;
    }
</style>
<script>

    var modal = $("#fileupload-modal");
    modal.hide();
    eva.loader(eva.s('/static/eva/js/eva.jquery.evaTip.js'), function(){
            modal.hide();
            $('#activity-box-image-button').on('click', function() {
                    $(this).evaTip("show", {
                            'tip' : modal,
                            'offsetX' : -75,
                            'offsetY' : 30,
                            'direction' : 'bottom'			
        });
        return false;
    });

    modal.find(".close").on("click", function(){
            modal.hide();
    });
});

var uploader = $('#singlefileupload');
var form = $("#activity-form");
var textarea = form.find('textarea');
uploader.bind('fileuploaddone', function (e, data) {
        var file = data.result[0];
        form.find('input[name="MessageFile[file_id]"]').val(file.id);
        modal.find(".close").hide();
});

$(".activity-box-text").live('click', function(){
        textarea.val(textarea.val() + $(this).attr('data-activity-text'));
        return false;
});

$(".item-func.reference").live('click', function(){
    textarea.val(textarea.val() + $(this).attr('data-activity-text'));
    form.find('input[name="reference_id"]').val($(this).attr('data-activity-reference'));
    form.find('input[name="messageType"]').val('forword');
});

var maxMessage = 140;
var countHandler = $('.activity-box-count');
var messageLetterCount = function(){
        countHandler.html(maxMessage - textarea.val().length);
}

textarea.live('keyup', function(){
    messageLetterCount();
});
</script>
