<? 
$title = $this->_('Feed');
$this->headTitle($title, 'SET');
if($this->form){
	$form = $this->form;
} else {
    $form = new Activity\Form\MessageCreateForm();
}
$item = $this->item;
$items = $items;
$form->useSubFormGroup()
     ->setMethod($item['id'] ? 'put' : 'post')
     ->setView($this)
     ->setAction($this->uri('/activity/'))
     ->bind($item)
     ->prepare();
?>
<div class="container">

    <div class="row">
        <form id="activity-form" <?=$this->formAttr($form)?> class="activity-box span7">
            <?=$form->helper('messageType', 'formHidden', array('class' => ''))?>        
            <?=$form->helper('reference_id', array('class' => ''))?>
            <?=$form->helper(array('MessageFile', 'file_id'), 'formHidden', array('class' => ''))?>
            <div class="page-header">
                <h3>Say something...</h3>
            </div>
            <fieldset class="form">
                <div class="activity-box-wrap">
                    <div class="activity-box-content">
                        <?=$form->helper('content', 'formTextarea', array('class' => '', 'rows' => 5))?>        
                    </div>
                    <div class="activity-box-buttons">
                        <a id="activity-box-image-button" class="activity-box-func activity-box-text" href="javascript:;" data-activity-text="Share Photo."><i class="icon-mini icon-picture"></i> Photo</a>
                        <a id="activity-box-video-button" class="activity-box-func" href="#"><i class="icon-mini icon-facetime-video"></i> Video</a>
                        There are <span class="highlight highlight-large activity-box-count">140</span> letters left <button type="submit" class="btn btn-light-brown btn-large">Submit</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>


    <div class="activity-list vlist">
        <?foreach($items as $item):?>
        <div class="item">
            <a href="<?=$this->uri('/user/' . $item['user_id'])?>" title="" class="item-absolute item-userface"><img src="<?=$this->gravatar($item['User']['email'])?>" alt="" class="img-rounded" width="60" height="60" /></a>
            <div class="item-inline item-text span6">
                <div class="item-content">
                    <div class="item-title"><a href="<?=$this->uri('/user/' . $item['user_id'])?>" class="item-user"><?=$item['User']['userName']?></a> Said:</div>
                    <p><?=$item['ContentHtml']?></p>
                    <?if($item['File']):?>
                    <div class="item-image">
                        <p><a href="<?=$item['File'][0]['Thumb']?>"><img src="<?=$this->thumb($item['File'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                    </div>
                    <?endif?>

                    <?if($item['ForwardActivity']): $subItem = $item['ForwardActivity'];?>
                    <div class="well">
                        <p><?=$subItem['ContentHtml']?></p>
                        <?if($subItem['File']):?>
                        <div class="item-image">
                            <p><a href="<?=$subItem['File'][0]['Thumb']?>"><img src="<?=$this->thumb($subItem['File'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                        </div>
                        <?endif?>
                        <div class="item-action">
                            <p class="pull-right"><a href="<?=$this->uri('/feed/' . $subItem['messageHash'])?>" class="" data-activity-comment="<?=$subItem['id']?>"><i class="icon-comment"></i> Comments (<span class="highlight"><?=$subItem['commentedCount']?></span>)</a></p>
                            <p class="pull-left">
                            <a href="<?=$this->uri('/feed/' . $subItem['messageHash'])?>"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($subItem['createTime'])?>" datetime="<?=$this->datetime()->isoTime($subItem['createTime'])?>"><?=$this->datetime($subItem['createTime'])?></time></a>
                            </p>
                        </div>
                    </div>
                    <?endif?>

                    <div class="item-action">
                        <p class="pull-right"><a href="javascript:;" class="item-func comment" data-activity-comment="<?=$item['id']?>"><i class="icon-comment"></i> Comments (<span class="highlight"><?=$item['commentedCount']?></span>)</a></p>
                        <p class="pull-right"><a href="#activity-form" class="item-func reference" data-activity-reference="<?=$item['id']?>" data-activity-text="@<?=$item['User']['userName']?> "><i class="icon-share-alt"></i> RT (<span class="highlight"><?=$item['transferredCount']?></span>)</a></p>
                        <p class="pull-left">
                        <a href="<?=$this->uri('/feed/' . $item['messageHash'])?>" class="item-id"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['createTime'])?>" datetime="<?=$this->datetime()->isoTime($item['createTime'])?>"><?=$this->datetime($item['createTime'])?></time></a>
                        </p>
                    </div>
                </div>

                <div class="item-sub-wrap">
                </div>
            </div>
        </div>
        <?endforeach?>
    </div><!--activity-list end-->

</div>

<?=$this->widget('File', 'file/index')?>

<style>
    #fileupload-modal {
            position:absolute;
            margin:0;
            width:250px;
    }
</style>
<script>

var modal = $("#fileupload-modal");
modal.hide();
eva.loader(eva.s('/static/eva/js/eva.jquery.evaTip.js'), function(){
    modal.hide();
    $('#activity-box-image-button').on('click', function() {
        $(this).evaTip("show", {
            'tip' : modal,
            'offsetX' : -75,
            'offsetY' : 30,
            'direction' : 'bottom'			
        });
        return false;
    });

    modal.find(".close").on("click", function(){
            modal.hide();
    });
});

var uploader = $('#singlefileupload');
var form = $("#activity-form");
var textarea = form.find('textarea');
uploader.bind('fileuploaddone', function (e, data) {
        var file = data.result[0];
        form.find('input[name="MessageFile[file_id]"]').val(file.id);
        modal.find(".close").hide();
});

$(".activity-box-text").live('click', function(){
        textarea.val(textarea.val() + $(this).attr('data-activity-text'));
        return false;
});

$(".item-func.reference").live('click', function(){
    textarea.val(textarea.val() + $(this).attr('data-activity-text'));
    form.find('input[name="reference_id"]').val($(this).attr('data-activity-reference'));
    form.find('input[name="messageType"]').val('forward');
});

$(".item-func.comment").live('click', function(){
        var item = $(this).parentsUntil('.item').parent();
        var idUrl = item.find('.item-id').attr('href');
        item.find('.item-sub-wrap').load(idUrl + ' .item-sub-wrap', function(){
            $(this).show();
        });
});

var maxMessage = 140;
var countHandler = $('.activity-box-count');
var messageLetterCount = function(){
        countHandler.html(maxMessage - textarea.val().length);
}

textarea.live('keyup', function(){
    messageLetterCount();
});
</script>
