<?
$this->headTitle('Feed', 'SET');
$user = $this->user;
$items = $this->items;
$viewAsGuest = $this->viewAsGuest;
$form = new Activity\Form\MessageCreateForm();
$form->useSubFormGroup()
     ->setMethod('post')
     ->setView($this)
     ->setAction($this->uri('/activity/'))
     ->prepare();
?>

<div class="page-inner">
    <div class="container">
        <div class="profile-cover">
            <?=$this->widget('Epic', 'widgets/profilenav', $this->vars())?>
        </div>
    </div><!-- above container end -->
    <div class="container">
        <div class="profile-main">
            <div class="row">
                <div class="span8">
                    <?=$this->widget('Epic', 'widgets/profilemeta', $this->vars())?>

                    <div class="profile-activities">
                        <?if(!$viewAsGuest):?>
                        <div class="row">
                            <form id="activity-form" <?=$this->formAttr($form)?> class="activity-box span7">
                                <?=$form->helper('messageType', 'formHidden', array('class' => ''))?>        
                                <?=$form->helper('reference_id', array('class' => ''))?>
                                <?=$form->helper(array('MessageFile', 'file_id'), 'formHidden', array('class' => ''))?>
                                <input name="callback" type="hidden" value="<?=$this->uri('/feed/')?>" />
                                <div class="page-header">
                                    <h3>Say something...</h3>
                                </div>
                                <fieldset class="form">
                                    <div class="activity-box-wrap">
                                        <div class="activity-box-content">
                                            <?=$form->helper('content', 'formTextarea', array('class' => '', 'rows' => 5))?>        
                                        </div>
                                        <div class="activity-box-buttons">
                                            <a id="activity-box-image-button" class="activity-box-func activity-box-text" href="javascript:;" data-activity-text="Share Photo."><i class="icon-mini icon-picture"></i> Photo</a>
                                            <a id="activity-box-video-button" class="activity-box-func" href="javascript:;" data-placement="bottom" rel="popover"><i class="icon-mini icon-facetime-video"></i> Video</a>
                                            There are <span class="highlight highlight-large activity-box-count">140</span> letters left <button type="submit" class="btn btn-light-brown btn-large">Submit</button>
                                        </div>
                                    </div>
                                </fieldset>

                            </form>


                        </div>
                        <?endif?>

                        <div class="page-header border-header">
                            <h3>New Activities</h3>
                        </div>

                        <div class="activity-list vlist">
                            <?foreach($items as $item):?>
                            <div class="item">
                                <a href="<?=$this->uri('/user/' . $item['User']['userName'])?>" title="" class="item-absolute item-userface"><img src="<?=$this->gravatar($item['User']['email'])?>" alt="" class="img-rounded" width="60" height="60" /></a>
                                <div class="item-inline item-text span6">
                                    <div class="item-content">
                                        <div class="item-title"><a href="<?=$this->uri('/user/' . $item['User']['userName'])?>" class="item-user"><?=$item['User']['userName']?></a> Said:</div>
                                        <p><?=$item['ContentHtml']?></p>
                                        <?if($item['File']):?>
                                        <div class="item-image">
                                            <p><a href="<?=$item['File'][0]['Thumb']?>" class="item-preview image" data-preview-type="image" data-url="<?=$this->thumb($item['File'][0]['Thumb'], array('w_400'))?>" data-width="400"><img src="<?=$this->thumb($item['File'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                                        </div>
                                        <?endif?>

                                        <?if($item['Video']):$video = $item['Video'];?>
                                        <div class="item-video">
                                            <?if($video['thumbnail']):?>
                                            <a href="<?=$video['url']?>" class="item-preview video" data-preview-type="video" data-url="<?=$video['swf']?>" data-width="<?=$video['width']?>" data-height="<?=$video['height']?>"><img src="<?=$video['thumbnail']?>" alt="video preview" class="img-polaroid" width="200" /><i class="icon-play btn-play"></i></a>
                                            <?else:?>
                                            <a href="<?=$video['url']?>" class="item-preview video" data-preview-type="video" data-url="<?=$video['swf']?>" data-width="<?=$video['width']?>" data-height="<?=$video['height']?>"><div class="video-no-preview"></div><i class="icon-play btn-play"></i></a>
                                            <?endif?>
                                        </div>
                                        <?endif?>

                                        <?if(isset($item['ForwardActivity']) && $item['ForwardActivity']): $subItem = $item['ForwardActivity'];?>
                                        <div class="well">
                                            <p><?=$subItem['ContentHtml']?></p>
                                            <?if($subItem['File']):?>
                                            <div class="item-image">
                                                <p><a href="<?=$subItem['File'][0]['Thumb']?>"><img src="<?=$this->thumb($subItem['File'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                                            </div>
                                            <?endif?>
                                            <div class="item-action">
                                                <p class="pull-right"><a href="<?=$this->uri('/feed/' . $subItem['messageHash'])?>" class="" data-activity-comment="<?=$subItem['id']?>"><i class="icon-comment"></i> Comments (<span class="highlight"><?=$subItem['commentedCount']?></span>)</a></p>
                                                <p class="pull-left">
                                                <a href="<?=$this->uri('/feed/' . $subItem['messageHash'])?>"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($subItem['createTime'])?>" datetime="<?=$this->datetime()->isoTime($subItem['createTime'])?>"><?=$this->datetime($subItem['createTime'])?></time></a>
                                                </p>
                                            </div>
                                        </div>
                                        <?endif?>

                                        <div class="item-action">
                                            <p class="pull-right">
                                                <a href="javascript:;" class="item-func remove <?=$viewAsGuest ? 'hide' : ''?>"><i class="icon-remove"></i> Delete</a>
                                                <a href="javascript:;" class="item-func comment" data-activity-comment="<?=$item['id']?>"><i class="icon-comment"></i> Comments (<span class="highlight"><?=$item['commentedCount']?></span>)</a>
                                            </p>
                                            <p class="pull-right hide"><a href="#activity-form" class="item-func reference" data-activity-reference="<?=$item['id']?>" data-activity-text="@<?=$item['User']['userName']?> "><i class="icon-share-alt"></i> RT (<span class="highlight"><?=$item['transferredCount']?></span>)</a></p>
                                            <p class="pull-left">
                                            <a href="<?=$this->uri('/feed/' . $item['messageHash'])?>" class="item-id"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['createTime'])?>" datetime="<?=$this->datetime()->isoTime($item['createTime'])?>"><?=$this->datetime($item['createTime'])?></time></a>
                                            </p>
                                        </div>
                                    </div>

                                    <div class="item-remove-ajax">
                                    </div>
                                    <div class="item-sub-ajax">
                                    </div>
                                </div>
                            </div>
                            <?endforeach?>

                            <?if($this->paginator):?>
                            <?=$this->paginator->setPath('/home/')->setBaseQuery($this->query);?>
                            <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                            <?endif;?>
                        </div><!--activity-list end-->


                    </div><!--profile-activities end-->
                </div><!--left span8 end-->
                <div class="span4">
                    <?=$this->widget('Epic', 'widgets/profileside', $this->vars())?>
                </div><!--right span4 end-->
            </div><!--row end-->
        </div><!--profil-main end-->
    </div><!--container end-->
</div><!--page inner end-->

<div id="video-popover" class="popover bottom">
    <div class="arrow"></div>
    <h3 class="popover-title">Add Video
        <span class="close">×</span>
    </h3>
    <div class="popover-content">
        <div class="form">
            <div class="input-append">
                <input name="url" class="input-medium" type="text" placeholder="Video Url..." />
                <button id="add-video" class="btn" type="button">Add</button>
            </div>
        </div>
        <div class="ajax-video-preview">
            <p>Support video sites: Youtube, Youku</p>
        </div>
    </div>
</div>
<?=$this->widget('File', 'file/index')?>

<script>
    var modal = $("#fileupload-modal");
    modal.hide();
    var videoPopover = $("#video-popover");
    eva.loader(eva.s('/static/eva/js/eva.jquery.evaTip.js'), function(){
            modal.hide();
            $('#activity-box-image-button').on('click', function() {
                    $(this).evaTip("show", {
                            'tip' : modal,
                            'offsetX' : -75,
                            'offsetY' : 30,
                            'direction' : 'bottom'			
                    });
                    return false;
            });

            modal.find(".close").on("click", function(){
                    modal.hide();
            });

            $("#activity-box-video-button").on('click', function() {
                    $(this).evaTip("show", {
                            'tip' : videoPopover,
                            'offsetX' : -90,
                            'offsetY' : 30,
                            'direction' : 'bottom'			
                    });
                    return false;
            });

            videoPopover.find(".close").on("click", function(){
                    videoPopover.hide();
            });
    });

    var modal = $("#fileupload-modal");
    modal.hide();
    eva.loader(eva.s('/static/eva/js/eva.jquery.evaTip.js'), function(){
            modal.hide();
            $('#activity-box-image-button').on('click', function() {
                    $(this).evaTip("show", {
                            'tip' : modal,
                            'offsetX' : -75,
                            'offsetY' : 30,
                            'direction' : 'bottom'			
                    });
                    return false;
            });

            modal.find(".close").on("click", function(){
                    modal.hide();
            });
    });

    var uploader = $('#singlefileupload');
    var form = $("#activity-form");
    var textarea = form.find('textarea');
    uploader.bind('fileuploaddone', function (e, data) {
            var file = data.result[0];
            form.find('input[name="MessageFile[file_id]"]').val(file.id);
            modal.find(".close").hide();
    });

    $(".activity-box-text").live('click', function(){
            textarea.val(textarea.val() + $(this).attr('data-activity-text'));
            return false;
    });

    $(".item-func.reference").live('click', function(){
            textarea.val(textarea.val() + $(this).attr('data-activity-text'));
            form.find('input[name="reference_id"]').val($(this).attr('data-activity-reference'));
            form.find('input[name="messageType"]').val('forward');
    });

    $(".item-func.comment").live('click', function(){
            var item = $(this).parentsUntil('.item').parent();
            var idUrl = item.find('.item-id').attr('href');
            item.find('.item-sub-ajax').load(idUrl + ' .item-sub-wrap', function(){
                    $(this).show();
            });
    });

    $(".item-func.remove").live('click', function(){
            var item = $(this).parentsUntil('.item').parent();
            var removeForm = item.find('.item-remove');
            var idUrl = item.find('.item-id').attr('href');
            if(!removeForm[0]){
                item.find('.item-remove-ajax').load(idUrl + ' .item-remove', function(){
                    item.find('.item-remove').show();
                });
            } else {
                removeForm.show();
            }
            return false;
    });

    $(".item-func.remove-cancel").live('click', function(){
            var item = $(this).parentsUntil('.item').parent();
            var removeForm = item.find('.item-remove');
            removeForm.hide();
            return false;
    });

    $(".activity-list").on("submit", ".item-sub-form form", function(){
            var form = $(this);
            var item = form.parentsUntil('.item').parent();
            var feedUrl = form.find('input[name=callback]').val();
            $.ajax({
                    url : form.attr('action'),
                    data : form.serialize(),
                    type : form.attr('method'),
                    success : function(){
                            item.find('.item-sub-ajax').load(feedUrl + ' .item-sub-wrap');
                    }
            });
            return false;
    });

    $("#add-video").on('click', function(){
            var popover = $("#video-popover");
            var url = popover.find("input[name=url]").val();
            if(url == ''){
                return false;
            }

            if(!/https?:\/\/[A-Za-z0-9\.-]{3,}\.[A-Za-z]{3}/i.test(url)) {
                    return false;
            }

            $.ajax({
                url : eva.d('/video/parser/'),
                data : {
                    url : url
                },
                dataType : 'json',
                success : function(response){
                        if(response.remoteId){
                                popover.find(".ajax-video-preview").html(eva.template('<embed src="{swf}" quality="high" width="200" height="120" align="middle" allowScriptAccess="always" allowFullScreen="true" mode="transparent" type="application/x-shockwave-flash"></embed>', response));
                                textarea.val(textarea.val() + ' ' + response.url);
                        } else {
                    
                        }
                }
            });

            return false;
    });

    var maxMessage = 140;
    var countHandler = $('.activity-box-count');
    var messageLetterCount = function(){
        countHandler.html(maxMessage - textarea.val().length);
    }

    textarea.live('keyup', function(){
        messageLetterCount();
    });
</script>


