<?
$this->headTitle('Epicurissimo compass | communauté privé pour les pros et les connaisseur du gastronomie et vin', 'SET');
$form = new Epic\Form\CorporateForm();
$form->useSubFormGroup()
    ->addSubForm('UserRoleFields', new User\Form\UserRoleFieldsForm(null, 11))
    ->setView($this)
    ->setMethod('post')
    ->setAction($this->uri('/reg/corporate'))
    ->prepare();
?>
<div class="container">
    <div id="titleblock">
        <div class="row">
            <?$locale = \Eva\Api::_()->getServiceManager()->get('translator')->getLocale();?>
            <div class="span5">
                <img src="<?=$this->assets('/module/epic/img/corporate-' . $locale . '-1.png')?>" />
            </div>
            <div class="span5">
                <img src="<?=$this->assets('/module/epic/img/corporate-' . $locale . '-2.png')?>" />
            </div>
            <?$locale="abc";?>
            <?if($locale == 'en'):?>

            <div class="span12">
                <h1><?=$this->_('Your Benefits')?></h1>
            </div>

            <div class="span6">
                <ul>
                    <li>Branding : reach your customers and audiences </li>
                    <li>Global Vision : profit our international.</li>
                    <li>Communicating : raise local attention</li>
                </ul>
            </div>
            <div class="span6">
                <ul>

                    <li>Human Capitals : post jobs and search for talents </li>
                    <li>Network : meet and connect with business contacts</li>
                    <li>Events : Hosing and promoting your events</li>
                </ul>
            </div>

            <?elseif($locale == 'fr'):?>

            <div class="span12">
                <h1><?=$this->_('Your Benefits')?></h1>
            </div>

            <div class="span6">
                <ul>
                    <li>Branding: atteindre vos clients et le public</li>
                    <li>Vision globale: notre but international.</li>
                    <li>Communication Publique: attirer l'attention locale</li>
                </ul>
            </div>
            <div class="span6">
                <ul>
                    <li>Talents: emplois poster et chercher des capitales de l'homme</li>
                    <li>Réseau: rencontrer et communiquer avec des contacts d'affaires</li>
                    <li>Evénements: tunning et la promotion de vos événements</li>
                </ul>
            </div>


            <?elseif($locale == 'zh'):?>

            <div class="span12">
                <h1><?=$this->_('Your Benefits')?></h1>
            </div>

            <div class="span6">
                <ul>
                    <li>品牌提升：近距离接触您的客户和潜在市场</li>
                    <li>全球视野：进入国际市场</li>
                    <li>参与互动：提升本地市场份额</li>
                </ul>
            </div>
            <div class="span6">
                <ul>
                    <li>人力资源：发布工作信息，找到企业所需人才</li>
                    <li>社交网络：认识和结交同行，发掘更多商业机会</li>
                    <li>组织活动：发起和宣传您的线下市场营销活动</li>
                </ul>
            </div>

            <?elseif($locale == 'zh_TW'):?>


            <div class="span12">
                <h1><?=$this->_('Your Benefits')?></h1>
            </div>

            <div class="span6">
                <ul>
                    <li>品牌提升：近距離接觸您的客戶和潛在市場</li>
                    <li>全球視野：進入國際市場</li>
                    <li>參與互動：提升本地市場份額</li>
                </ul>
            </div>
            <div class="span6">
                <ul>
                    <li>人力資源：發布工作信息，找到企業所需人才</li>
                    <li>社交網絡：認識和結交同行，發掘更多商業機會</li>
                    <li>組織活動：發起和宣傳您的線下市場營銷活動</li>
                </ul>
            </div>

            <?endif?>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <form id="signupform" <?=$this->formAttr($form)?> class="form">
            <?=$form->restful();?>
            <?=$form->helper('id');?>
            <div class="span5">
                <?=$form->helper('id', array('class' => ''))?>
                <div class="control-group <?=$form->isError('email') ? 'error' : '';?>">
                    <?=$form->helper('email', 'label', array('class' => 'control-label'))?>
                    <div class="controls">
                        <?=$form->helper('email', array('class' => 'validate[required,custom[email]]'))?>        
                        <div class="help-block"><?=$form->helper('email', 'formElementErrors')?></div>
                    </div>
                </div>

                <!-- companyName 4 -->
                <div class="control-group <?=$form->isError(array('UserRoleFields', '4')) ? 'error' : '';?>">
                    <?=$form->helper(array('UserRoleFields', '4'), 'label', array('class' => 'control-label'))?>
                    <div class="controls">
                        <?=$form->helper(array('UserRoleFields', '4'), array('class' => ''))?>        
                        <div class="help-block"><?=$form->helper(array('UserRoleFields', '4'), 'formElementErrors')?></div>
                    </div>
                </div>

                <div class="control-group <?=$form->isError(array('Profile', 'country')) ? 'error' : '';?>">
                    <?=$form->helper(array('Profile', 'country'), 'label', array('class' => 'control-label'))?>
                    <div class="controls">
                        <?=$form->helper(array('Profile', 'country'), 'formSelect', array('class' => ''))?>        
                        <div class="help-block"><?=$form->helper(array('Profile', 'country'), 'formElementErrors')?></div>
                    </div>
                </div>
                <div class="control-group <?=$form->isError(array('Profile', 'industry')) ? 'error' : '';?>">
                    <?=$form->helper(array('Profile', 'industry'), 'label', array('class' => 'control-label'))?>
                    <div class="controls">
                        <?=$form->helper(array('Profile', 'industry'), 'formSelect', array('class' => ''))?>        
                        <div class="help-block"><?=$form->helper(array('Profile', 'industry'), 'formElementErrors')?></div>
                    </div>
                </div>
                <div class="control-group <?=$form->isError(array('Profile', 'phoneBusiness')) ? 'error' : '';?>">
                    <?=$form->helper(array('Profile', 'phoneBusiness'), 'label', array('class' => 'control-label'))?>
                    <div class="controls">
                        <?=$form->helper(array('Profile', 'phoneBusiness'), array('class' => ''))?>        
                        <div class="help-block"><?=$form->helper(array('Profile', 'phoneBusiness'), 'formElementErrors')?></div>
                    </div>
                </div>
                <div class="control-group <?=$form->isError(array('Profile', 'address')) ? 'error' : '';?>">
                    <?=$form->helper(array('Profile', 'address'), 'label', array('class' => 'control-label'))?>
                    <div class="controls">
                        <?=$form->helper(array('Profile', 'address'), array('class' => ''))?>        
                        <div class="help-block"><?=$form->helper(array('Profile', 'address'), 'formElementErrors')?></div>
                    </div>
                </div>
                <div class="control-group <?=$form->isError(array('Profile', 'bio')) ? 'error' : '';?>">
                    <?=$form->helper(array('Profile', 'bio'), 'label', array('class' => 'control-label'))?>
                    <div class="controls">
                        <?=$form->helper(array('Profile', 'bio'), 'formTextarea', array('class' => ''))?>        
                        <div class="help-block"><?=$form->helper(array('Profile', 'bio'), 'formElementErrors')?></div>
                    </div>
                </div>
            </div>
            <div class="span5">

                <!-- How could we help you? -->
                <div class="control-group <?=$form->isError(array('UserRoleFields', '6')) ? 'error' : '';?>">
                    <?=$form->helper(array('UserRoleFields', '6'), 'label', array('class' => 'control-label'))?>
                    <div class="controls">
                        <?=$form->helper(array('UserRoleFields', '6'), 'formMultiCheckbox', array('class' => ''))?>        
                        <div class="help-block"><?=$form->helper(array('UserRoleFields', '6'), 'formElementErrors')?></div>
                    </div>
                </div>

                <!-- How could we help you? -->
                <div class="control-group <?=$form->isError(array('UserRoleFields', '7')) ? 'error' : '';?>">
                    <?=$form->helper(array('UserRoleFields', '7'), 'label', array('class' => 'control-label'))?>
                    <div class="controls">
                        <?=$form->helper(array('UserRoleFields', '7'), 'formMultiCheckbox', array('class' => ''))?>        
                        <div class="help-block"><?=$form->helper(array('UserRoleFields', '7'), 'formElementErrors')?></div>
                    </div>
                </div>


            </div>

            <div class="control-group span12">
                <div class="controls">
                    <label><input name="agree" class="validate[required]" type="checkbox" checke="checked"><?=$this->_('By clicking Sign Up, you agree to our Terms & Conditions.')?></label>
                    <br>
                    <button type="submit" class="btn btn-large"><?=$this->_('Sign Up')?></button>
                </div>
            </div>
        </form>
    </div>
</div>
