<?
$this->headTitle('Thank You', 'SET');
?>
<div class="container">
    <div id="singletitle" class="page-header typo">
        <h1><?=$this->_('Thank You')?></h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="span12">
            <div class="well">
                <div class="hero-unit typo">

                    <br/>
                    <br/>
                    <br/>
                    <br/>
                    <h2 class="centeralign"><?=$this->_('Once our website is completed, we will inform you by email')?></h2>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                    <br/>
                </div>
            </div>
        </div>
    </div>
</div>
