<? 
$title = $this->_('Login');
$this->headTitle($title, 'SET');
$item = $this->item;
if($this->form){
	$form = $this->form;
} else {
    $form = new User\Form\LoginForm();
}

$form
->setView($this)
->useSubFormGroup()
->setMethod('post')
->setAction($this->uri('/login/'))
->bind($item)
->prepare();

?>
<div class="container">

    <div class="row">
        <div class="span8">
            <header class="page-header">
            <h2 class=""><?=$title?></h2>
            </header>
            <form <?=$this->formAttr($form)?> class="form-horizontal">
                <?=$form->restful();?>
                <div class="control-group <?=$form->isError('loginName') ? 'error' : '';?>">
                    <?=$form->helper('loginName', 'label', array('class' => 'control-label'))?>
                    <div class="controls">
                        <?=$form->helper('loginName', array('class' => ''))?>        
                        <div class="help-block"><?=$form->helper('loginName', 'formElementErrors')?></div>
                    </div>
                </div>
                <div class="control-group <?=$form->isError('inputPassword') ? 'error' : '';?>">
                    <?=$form->helper('inputPassword', 'label', array('class' => 'control-label'))?>
                    <div class="controls">
                        <?=$form->helper('inputPassword', array('class' => ''))?>        
                        <div class="help-block"><?=$form->helper('inputPassword', 'formElementErrors')?></div>
                    </div>
                </div>
                <div class="control-group <?=$form->isError('rememberMe') ? 'error' : '';?>">
                    <div class="controls">
                        <label class="checkbox"><?=$form->helper('rememberMe', array('class' => 'checkbox'))?> <?=$this->_('Remember Me');?></label>
                    </div>
                </div>
                <div class="form-actions">
                    <button type="submit" class="btn btn-info btn-large"><?=$this->_('Login');?></button>
                </div>

            </form>
        </div>
        <div class="span4">
            <div class="well">
                <header class="page-header">
                <h4 class="">Login by</h4>
                </header>
                <div class="btn-group btn-group-vertical">
                    <a href="<?=$this->uri('/oauth/', array('callback' => $this->serverUrl() . '/login/', 'service' => 'twitter', ))?>" class="btn btn-small">Twitter</a>
                    <a href="<?=$this->uri('/oauth/', array('callback' => $this->serverUrl() . '/login/', 'service' => 'facebook',))?>" class="btn btn-small">Facebook</a>
                </div>
                <hr />
                <div class="btn-group btn-group-vertical">
                    <a href="<?=$this->uri('/oauth/', array('callback' => $this->serverUrl() . '/login/oauth/', 'service' => 'douban', 'version' => 1))?>" class="btn btn-small">Douban</a>
                    <a href="<?=$this->uri('/oauth/', array('callback' => $this->serverUrl() . '/login/oauth/', 'service' => 'weibo',))?>" class="btn btn-small">Weibo</a>
                </div>
            </div>
        </div>
    </div>



</div>
