<?
$item = $this->item;
$title = 'Send Newsletter';

$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', $title);
?>

<div class="row">
   <form method="post" action="/admin/core/newsletter/send">
        <input type="hidden" value="post" name="_method"> 
        <div class="span10">
            <div class="slate">
                <fieldset class="">
                    <div class="control-group ">
                        <label class="control-label" for="group-form-groupcreateform-groupname">Newsletter Subject</label>                        
                        <div class="controls docs-input-sizes">
                            <input type="text" value="" class="span9" id="group-form-groupcreateform-groupname" name="title">                            
                        </div>
                    </div>
                    
                    <div class="control-group ">
                        <label class="control-label" for="group-form-groupcreateform-bcc">Subscription Emails</label>                        
                        <div class="controls docs-input-sizes">
                            <textarea rows="5" class="span9" id="group-form-textform-bcc" name="bcc"><?=$this->bcc?></textarea>                            
                        </div>
                    </div>

                    <div class="control-group ">
                        <div class="controls" id="editor-left">
                            <textarea rows="15" class="span9" id="group-form-textform-content" name="content"></textarea>                        
                        </div>
                    </div>
                </fieldset>
            </div>
        </div><!--span10 end-->

        <div class="span10 listing-buttons">
            <button id="save-publish" class="btn btn-success btn-large"><?=$this->_('Send')?></button>
        </div>
    </form>
</div>
