<?
$item = $this->item;
$title = 'Send Newsletter';

$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', $title);

if($this->form){
	$form = $this->form;
} else {
    $form = new Core\Form\NewsletterForm();
}

$form
->setView($this)
->useSubFormGroup()
->setMethod('post')
->setAction($this->uri('/admin/core/newsletter/send/'))
->bind($item)
->prepare();
?>


<div class="row">
   <form <?=$this->formAttr($form)?> class="form">
   <?=$form->restful();?>
        <div class="span10">
            <div class="slate">
                <fieldset class="">
                            <div class="control-group <?=$form->isError('sender') ? 'error' : '';?> hide">
                                <?=$form->helper('sender', 'label', array('class' => 'control-label'))?>
                                <div class="controls">
                                    <?=$form->helper('sender', array('class' => 'span6'))?>        
                                    <div class="help-block"><?=$form->helper('sender', 'formElementErrors')?></div>
                                </div>
                            </div>
                            <div class="control-group <?=$form->isError('recipient') ? 'error' : '';?> hide">
                                <?=$form->helper('recipient', 'label', array('class' => 'control-label'))?>
                                <div class="controls">
                                    <?=$form->helper('recipient', array('class' => 'span6'))?>        
                                    <div class="help-block"><?=$form->helper('recipient', 'formElementErrors')?></div>
                                </div>
                            </div>
                            <div class="control-group <?=$form->isError('subject') ? 'error' : '';?>">
                                <?=$form->helper('subject', 'label', array('class' => 'control-label'))?>
                                <div class="controls">
                                    <?=$form->helper('subject', array('class' => 'span6', 'value' => ''))?>        

                                    <div class="help-block"><?=$form->helper('subject', 'formElementErrors')?></div>
                                </div>
                            </div>
                            <div class="control-group <?=$form->isError('bcc') ? 'error' : '';?>">
                                <?=$form->helper('bcc', 'label', array('class' => 'control-label'), array('args' => array(null, 'abc')))?>
                                <div class="controls">
                                    <?=$form->helper('bcc', 'formTextarea', array('class' => 'span6', 'rows' => 5))?>     
                                    <div class="help-block"><?=$form->helper('bcc', 'formElementErrors')?></div>
                                </div>
                            </div>
                            <div class="control-group <?=$form->isError('content') ? 'error' : '';?>">
                                <?=$form->helper('content', 'label', array('class' => 'control-label'), array('args' => array(null, 'abc')))?>
                                <div class="controls">
                                    <?=$form->helper('content', 'formTextarea', array('class' => 'span6', 'rows' => 10))?>        
                                    <div class="help-block"><?=$form->helper('content', 'formElementErrors')?></div>
                                </div>
                            </div>
                            <div class="control-group <?=$form->isError('attachment') ? 'error' : '';?>">
                                <?=$form->helper('attachment', 'label', array('class' => 'control-label'))?>
                                <div class="controls">
                                    <?=$form->helper('attachment', array('class' => ''))?>        
                                    <div class="help-block"><?=$form->helper('attachment', 'formElementErrors')?></div>
                                </div>
                            </div>
                </fieldset>
            </div>
        </div><!--span10 end-->

        <div class="span10 listing-buttons">
            <button id="save-publish" class="btn btn-success btn-large"><?=$this->_('Send')?></button>
        </div>
    </form>
</div>


<script>
eva.ready(function(){
      
    eva.callback.connect = function(item, parentWindow){
        $("#group-form-groupfileform-file-id").val(item.attr("data-connect-id"));
        var data = $.parseJSON(item.attr('data-connect-json'));
        $("#post-image").attr("src", data.Thumb);
        $.fn.colorbox.close();
    }
    eva.loadcss(eva.s('/lib/js/jquery/colorbox/colorbox.css'));
    eva.loader(eva.s('/lib/js/jquery/colorbox/jquery.colorbox.js'), function(){
        $("#connect-image").colorbox({
            iframe:true,
                width:"80%",
                height:"80%"
        });
    });


    $("#save-draft").on('click', function(){
        $("#blog-form-posteditform-status").val('draft');
    });

    var editor = $("#blog-form-textform-content");

    var editorMd;
    var mdInited = false;
    var initMd = function(_editor){
        if(true === mdInited) {
            return;
        }
        eva.loadcss(eva.s(['/lib/js/codemirror/lib/codemirror.css', '/lib/js/codemirror/theme/ambiance.css']));
        eva.loader(eva.s(['/lib/js/codemirror/lib/codemirror.js', '/lib/js/codemirror/mode/xml/xml.js', '/lib/js/codemirror/mode/markdown/markdown.js', '/lib/js/showdown/showdown.js']), function(){
            mdInited = true;
            builtMdEditor(_editor);
        });
    }
    var builtMdEditor = function(_editor){
        if(!mdInited){
            initMd(_editor); 
            return;
        }
        editorMd = CodeMirror.fromTextArea(_editor[0], {
            "mode":"markdown",
                "theme":"ambiance",
                "lineNumbers":true,
                "lineWrapping":true,
                onChange : function(){
                }
        });	
    }
    var removeMdEditor = function(){
        if(!editorMd){
                return;
            }
            editorMd.toTextArea();
    }


    var editorHtml;
    var htmlInited = false;
    var initHtml = function(_editor){
            if(true === htmlInited) {
                return;
            }
            eva.loader(eva.s(["/lib/js/tiny_mce/jquery.tinymce.js"]), function(){
                    htmlInited = true;
                    builtHtmlEditor(_editor);
            });
    }
    var builtHtmlEditor = function(_editor){
            if(!htmlInited){
                    initHtml(_editor); 
                    return;
            }

			var mceGlobelConfig = {
				mode : "textareas",
				theme : "advanced",
				plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

				// Theme options
				theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
				theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
				theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
				theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
				theme_advanced_toolbar_location : "top",
				theme_advanced_toolbar_align : "left",
				theme_advanced_statusbar_location : "bottom",
				theme_advanced_resizing : true,
				
				remove_linebreaks : false,
				extended_valid_elements : "pre[cols|rows|disabled|name|readonly|class]",
				script_url : eva.s('/lib/js/tiny_mce/tiny_mce.js'),
				
				content_css: eva.s("/lib/css/typo/typo.min.css"),
				spellchecker_rpc_url : eva.s('/lib/js/tiny_mce/plugins/spellchecker/rpc.php')
			};

            var mceconfig = mceGlobelConfig;
            editorHtml = _editor.tinymce(mceconfig);
    }

    var removeHtmlEditor = function(_editor){
            if(!editorHtml){
                return;
            }
            tinyMCE.execCommand('mceToggleEditor', false, _editor.attr('id'));
    }

    var switchEditor = function(){
            var codeType = $("input[name='codeType']:checked").val();
            if(codeType == 'markdown'){
                    removeHtmlEditor(editor);
                    builtMdEditor(editor); 
            } else if(codeType == 'html'){
                    removeMdEditor(editor);
                    builtHtmlEditor(editor);
            }
    }
    switchEditor();
    $("input[name='codeType']").on("change", function(){
            if(confirm('Content will be changed, are you sure ?')){
                switchEditor(); 
            }
    });
});
</script>
