<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
    <?=$this->headTitle()?>
    <?$this->link('/src/admin/css/bootstrap.css')?>
	<!--[if lt IE 9]>
	<meta http-equiv="PRAGMA" content="NO-CACHE" />
    <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
	<![endif]-->
    <?=$this->headMeta()?>
    <?=$this->googleAnalytics()?>
    <link href="<?=$this->link('/lib/css/fontawesome/css/font-awesome.css')?>" media="all" rel="stylesheet" type="text/css" />
    <link href="<?=$this->link('/src/engine/css/ee.css')?>" media="all" rel="stylesheet" type="text/css" />
    <?=$this->evajs()?>
    <script src="<?=$this->link('/lib/js/labjs/labjs.min.js')?>"></script>
    <script src="<?=$this->link('/lib/js/jquery/jquery.min.js')?>"></script>
    <!--<script src="<?=$this->link('/lib/js/bootstrap/bootstrap.min.js')?>"></script>-->
    <script src="<?=$this->link('/eva/js/core.js')?>"></script>
    <script src="<?=$this->link('/eva/js/ui.js')?>"></script>
    <script src="<?=$this->link('/src/admin/js/init.js')?>"></script>
</head>

<body class="">

    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="/">EvaEngine</a>	
                <div class="nav-collapse">
                    <ul class="nav">
                        <li data-highlight-url="^/$"><a href="/"><?=$this->_('Home')?></a></li>
                        <?if($this->hasModule('Blog')):?>
                        <li data-highlight-url="/(blog|pages)/*"><a href="/pages/"><?=$this->_('Blog')?></a></li>
                        <?endif?>
                        <?if($this->hasModule('Activity') && $this->loginUser):?>
                        <li data-highlight-url="/feed/?"><a href="/feed/"><?=$this->_('Feed')?></a></li>
                        <?endif?>
                        <!--
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li class="nav-header">Nav header</li>
                            <li><a href="#">Separated link</a></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                        </li>
                        -->
                    </ul>
                    <!--
                    <form class="navbar-search pull-left" action="">
                        <input class="search-query span2" placeholder="Search" type="text">
                    </form>
                    -->
                    <ul class="nav pull-right">
                        <li class="divider-vertical"></li>
                        <?if($this->hasModule('User')):?>
                        <?if($this->loginUser):?>
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->loginUser['userName']?> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Profile</a></li>
                            <li><a href="#">Setting</a></li>
                            <li class="divider"></li>
                            <li><a href="<?=$this->uri('/user/logout/')?>">Logout</a></li>
                        </ul>
                        </li>
                        <?else:?>
                        <li data-highlight-url="/register/*"><a href="/register/"><?=$this->_('Register')?></a></li>
                        <li data-highlight-url="/login/*"><a href="/login/"><?=$this->_('Login')?></a></li>
                        <?endif?>
                        <?endif?>

                    </ul>
                </div><!-- /.nav-collapse -->
            </div>
        </div><!-- /navbar-inner -->
    </div><!-- /navbar -->


    <div id="page" class="page">
        <?=$this->content;?>
    </div><!-- #page end-->

    <hr />
    <div class="container" id="footer">
        <div class="row">
            <div class="span4 ">
                <dl class="dl-horizontal">
                    <dt>Navigation</dt>
                    <dd>
                    <ul class="unstyled">

                        <li class="active">
                        <a href="https://github.com/AlloVince/eva-engine" title="Home" class="brand">Source Code</a>
                        </li>

                    </ul>
                    </dd>
                </dl>
            </div>
            <div class="span4">
                <dl class="dl-horizontal">
                    <dt>Documents</dt>
                    <dd>
                    <ul class="unstyled">

                        <li>
                        <a href="http://avnpc.com/">Author Blog</a>
                        </li>

                    </ul>
                    </dd>
                </dl>
            </div>

            <div class="span4">
                <dl class="dl-horizontal">
                    <dt>Admin Panel</dt>
                    <dd>
                    <ul class="unstyled">

                        <li>
                        <a href="<?=$this->uri('/admin/')?>">Login</a>
                        </li>

                    </ul>
                    </dd>
                </dl>
            </div>

        </div>
    </div>

    <script>
        eva.init(eva_config);
    </script>

</body>
</html>
