<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
    <?=$this->headTitle()?>
    <?$this->link('/src/admin/css/bootstrap.css')?>
	<!--[if lt IE 9]>
	<meta http-equiv="PRAGMA" content="NO-CACHE" />
    <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
	<![endif]-->
    <?=$this->headMeta()?>
    <?=$this->googleAnalytics()?>
    <link href="<?=$this->link('/lib/css/fontawesome/css/font-awesome.css')?>" media="all" rel="stylesheet" type="text/css" />
    <link href="<?=$this->link('/src/engine/css/ee.css')?>" media="all" rel="stylesheet" type="text/css" />
    <?=$this->evajs()?>
    <script src="<?=$this->link('/lib/js/labjs/labjs.min.js')?>"></script>
    <script src="<?=$this->link('/lib/js/jquery/jquery.min.js')?>"></script>
    <!--<script src="<?=$this->link('/lib/js/bootstrap/bootstrap.min.js')?>"></script>-->
    <script src="<?=$this->link('/eva/js/core.js')?>"></script>
    <script src="<?=$this->link('/eva/js/ui.js')?>"></script>
    <script src="<?=$this->link('/src/admin/js/init.js')?>"></script>
</head>

<body class="">
	<div class="navbar"><div class="navbar-inner"><div class="container">
                <a class="brand" href="/">EvaEngine</a>	
    <ul class="nav">
        <li data-highlight-url="^/$"><a href="/"><?=$this->_('Home')?></a></li>
        <?if($this->hasModule('Blog')):?>
        <li data-highlight-url="/(blog|pages)/*"><a href="/blog/"><?=$this->_('Blog')?></a></li>
        <?endif?>
        <?if($this->hasModule('User')):?>
        <li data-highlight-url="/register/*"><a href="/register/"><?=$this->_('Register')?></a></li>
        <li data-highlight-url="/login/*"><a href="/login/"><?=$this->_('Login')?></a></li>
        <?endif?>
        <?if($this->hasModule('Activity')):?>
        <li data-highlight-url="/feed/?"><a href="/feed/"><?=$this->_('Feed')?></a></li>
        <?endif?>
	</ul>
    <ul class="nav pull-right">
        <li><a href="/admin/"><?=$this->_('Admin')?></a></li>
    </ul>
    </div></div></div>

<div id="page" class="page">
<?=$this->content;?>
</div><!-- #page end-->

    <script>
        eva.init(eva_config);
    </script>

</body>
</html>
