<?
$title = $this->_('Queue List');
$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', $title);
?>

<div class="row">
    <div class="span10">
        <div class="slate">
            <div class="page-header">
               <div class="btn-group pull-right">
                  <a class="btn" href="<?=$this->uri('/admin/core/queue/monitor/')?>"><i class="icon-eye-open"></i> Monitor</a>
                  <a class="btn" href="<?=$this->uri('/admin/core/queue/run/?worker=all')?>"><i class="icon-fighter-jet"></i> Run Public Worker</a>
               </div>
               <h2><?=$title?></h2>
            </div>

            <table class="orders-table table">
               <thead>
                  <tr>
                     <th class="span1">
                        </th>
                        <th><?=$this->_('Queue Name')?></th>
                        <th><?=$this->_('Jobs Count')?></th>
                        <th class="actions"><?=$this->_('Actions')?></th>
                    </tr>
                </thead>
                <tbody>
                    <?if($this->items):?>
                    <?foreach($this->items as $key=>$item):?>
                    <tr class="">
                        <td>
                            <input name="id" type="checkbox" class="multiform-item-checkbox"  data-multiform="post" data-multiform-itemid="<?=$key?>" value="<?=$key?>" />
                        </td>	
                        <td>
                            <a href="<?=$this->uri('/admin/core/queue/' . $item['name'])?>" class="title"><?=$item['name']?></a>
                        </td>
                        <td>
                           <span class="label"><?=$item['size']?></span>
                        </td>
                        <td class="span4">
                           <a href="<?=$this->uri('/admin/core/queue/fork/?queue=' . $item['name'])?>" class="btn btn-small"><?=$this->_('Add Worker')?></a>
                           <a href="<?=$this->uri('/admin/core/queue/clear/?queue=' . $item['name'])?>" class="btn btn-small"><?=$this->_('Clear')?></a>
                           <a href="<?=$this->uri('/admin/core/queue/add/?queue=' . $item['name'])?>" class="btn btn-small"><?=$this->_('Add Job')?></a>
                        </td>
                    </tr>
                    <?endforeach;?>
                    <?endif;?>
                </tbody>
            </table>
        </div>
    </div><!--span10 end-->
</div>
