<?
$title = $this->_('Cache Cleaner');
$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', $title);
?>
<div class="main-area dashboard">

    <div class="row">
        <div class="span10">
            <div class="slate">
                    <h2><?=$title?></h2>
                </div>

                <table class="orders-table table">
                    <thead>
                        <tr>
                            <th><?=$this->_('Title')?></th>
                            <th class="actions"><?=$this->_('Actions')?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="">
                            <td>
                                <a href="<?=$this->uri('/admin/core/cache/static')?>" class="title">Static Cache Clean</a>
                            </td>
                            <td class="actions">
                                <a href="<?=$this->uri('/admin/core/cache/static')?>" class="btn btn-small"><?=$this->_('Run')?></a>
                            </td>
                        </tr>
                        <?if($this->stats):?>
                        <tr class="">
                            <td>
                                <a href="<?=$this->uri('/admin/core/cache/memcached')?>" class="title">Memcached Cache Clean (<?=$this->availableSpace . '/' . $this->totalSpace;?>)</a>

                            </td>
                            <td class="actions">
                                <a href="<?=$this->uri('/admin/core/cache/Memcached')?>" class="btn btn-small"><?=$this->_('Run')?></a>
                            </td>
                        </tr>
                        <?foreach($this->stats as $key=>$server)?>
                        <tr class="">
                            <td>
                                <?=$this->_('Server')?> : <?=$key?>
                            </td>
                            <td class="actions">
                               <p>
                               <?=$this->_('Available Space/Total Space');?> : <?=$server['availableSpace'] . '/' . $server['totalSpace'];?> 
                               </p>
                               <p>
                               <?=$this->_('Hit Rate')?> : <?=$server['get_hits'] . '/' . $server['cmd_get'];?>(<?=$server['hitRate']?>%)
                               </p>
                            </td>
                        </tr> 
                        <?endif;?>
                    </tbody>
                </table>
            </div>
        </div><!--span10 end-->
    </div>

</div>
