<?
$title = 'Groups';
$this->headTitle($title, 'SET');
$user = $this->user;
$item = $this->event;
?>

<div class="container">
    <header class="group-header">
        <?=$this->widget('Epic', 'widgets/groupnav', $this->vars())?> 
    </header>
</div>

<div class="container">
    <div class="page-bg">
        <div class="row">

            <div class="span8">
                <div class="group-main">

                    <?=$this->widget('Epic', 'widgets/groupcard', $this->vars())?>  
  
                                <div class="album-list">
                                    <?if(count($items) > 0 )?>
                                    <?for($i=0;$i< ceil(count($items) / 4);$i++):?>
                                    <div class="row-fluid stack-row">
                                        <?for($j= ($i * 4);$j< (4 * ($i+1));$j++):?>
                                        <?if(isset($items[$j])){$item = $items[$j];}else{continue;}?>
                                        <div class="span3">
                                            <div class="stack">	
                                                <a href="<?=$this->uri('/group/' . $this->item['groupKey'] . '/album/' . $item['urlName']);?>">
                                                    <?if(isset($item['Cover']) && $item['Cover']):?>
                                                        <img src="<?=$this->thumb($item['Cover']['Thumb'], array('c_fill', 'w_180', 'h_180'))?>" width="180" />
                                                    <?else:?>
                                                        <img src="<?=$this->assets('/module/epic/img/album-default.png')?>" width="180" alt="" />
                                                    <?endif?>
                                                </a>
                                            </div>
                                            <p class="caption">
                                                <a href="<?=$this->uri('/group/' . $this->item['groupKey'] . '/album/' . $item['urlName']);?>" class="caption-title"><?=$item['title']?></a>
                                                <span class="lowlight">(<?=$item['ImageCount']['imageCount']?> Photos Total)</span>
                                            </p>
                                        </div>
                                        <?endfor;?>
                                    </div>
                                    <?endfor;?>
                                </div><!--album-list end-->
                        
                        <?if($this->paginator):?>
                        <?=$this->paginator->setPath('/group/' . $this->item['groupKey'] . '/album/')->setBaseQuery($this->query);?>
                        <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                        <?endif;?>
                </div><!--group main end-->
            </div><!--page main left end-->
            <div class="span4">
                <?=$this->widget('Epic', 'widgets/groupside', $this->vars())?>  
            </div>

        </div><!--page main right end-->
    </div><!-- page-bg end-->
</div><!--container end-->
