<?
$title = 'Groups';
$this->headTitle($title, 'SET');
$user = $this->user;
$items = $this->items;
?>

<div class="container">
    <header class="group-header">
        <?=$this->widget('Epic', 'widgets/groupnav', $this->vars())?> 
    </header>
</div>

<div class="container">
    <div class="page-bg">
        <div class="row">

            <div class="span8">
                <div class="group-main">

                    <?=$this->widget('Epic', 'widgets/groupcard', $this->vars())?>  

                    <div class="tab-content">
                        <div class="tab-pane active group-forum group-forum-script" id="group-forum">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th class="span5">Discussion</th>
                                        <th>Author</th>
                                        <th class="span1 centeralign">Comments</th>
                                        <th class="span2 rightalign">Last Comment</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?if($this->posts):?>
                                    <?foreach($this->posts as $post):?>
                                    <tr>
                                        <td class="title"><a href="<?=$this->uri('/group/' . $post['Group']['groupKey'] . '/blog/info/' . $post['urlName'])?>"><?=$post['title']?></a></td>
                                        <td class="author"><a href="<?=$this->uri('/user/' . $post['User']['userName'])?>"><?=$post['User']['userName']?></a></td>
                                        <td class="centeralign comment-count"><a href=""><?=$post['commentCount']?></a></td>
                                        <td class="comment-time  rightalign"><?=$post['createTime']?></td>
                                    </tr>
                                    <?endforeach;?>
                                    <?endif;?>
                                </tbody>
                            </table>
                        </div> 
                        <?if($this->paginator):?>
                            <?=$this->paginator->setPath('/group/' . $post['Group']['groupKey'])->setBaseQuery($this->query);?>
                            <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                        <?endif;?>
                    </div>


                </div><!--group main end-->
            </div><!--page main left end-->
            <div class="span4">
               <?=$this->widget('Epic', 'widgets/groupside', $this->vars())?>  
            </div>

        </div><!--page main right end-->
    </div><!-- page-bg end-->
</div><!--container end-->
