<?
$title = 'Groups';
$title = $this->_($title);
$this->headTitle($title, 'SET');
$items = $this->items;

$form = new Group\Form\GroupUserForm();
$form
->setView($this)
->useSubFormGroup()
->setMethod('post')
->setAction($this->uri('/group/join/'))
->prepare();

$unjoinForm = clone $form;
$unjoinForm->setMethod('delete');


$groupSearchForm = $this->form ? $this->form : new Epic\Form\GroupSearchForm();
$groupSearchForm->setView($this)
     ->setMethod('get')
     ->setAction($this->uri('/groups/list/'))
     ->prepare();

?>

<div class="container">
    <header class="group-header">
        <?=$this->widget('Epic', 'widgets/groupnav', $this->vars())?> 
    </header>
</div>

<div class="container">
    <div class="page-bg">
        <div class="row">

            <div class="span8">
                <div class="group-main">

                    <?=$this->widget('Epic', 'components/banner_group')?>  

                    <div class="page-main-header">
                        <h3>
                            <?=$this->_('Groups')?>
                            <?if($this->query['keyword']):?>
                            | Now Searching "<span class="highlight"><?=$this->query['keyword']?></span>"
                            <?endif?>
                        </h3>
                    </div>
                    <div class="search-filter">
                        <form <?=$this->formAttr($groupSearchForm)?> class="form form-inline">
                            <?=$groupSearchForm->helper('keyword', array('class' => 'span2', 'placeholder' => 'Keyword...'))?>
                            <?if($this->categories):?>
                            <select class="input-medium select2" name="category">
                                <option value=""><?=$this->_('All')?></option>
                            <?foreach($this->categories as $cate):?> 
                                <?if(!$cate['urlName']){continue;}?>   
                                <option <?=$cate['urlName'] == $this->query['category'] ? 'selected="selected"' : null?> value="<?=$cate['urlName']?>"><?=$cate['categoryName']?></option>
                            <?endforeach;?>
                            </select>
                            <?endif;?>
                            <?=$groupSearchForm->helper('tag', array('class' => 'input-small','placeholder' => 'Tag'))?>
                            <button class="btn" type="submit"><?=$this->_('Find a Group')?></button>
                        </form>
                    </div>
                    <div class="user-list vlist">
                        <?foreach($items as $item):?>
                        <div class="item">
                            <div class="item-inline item-text">
                                <div class="item-title">
                                    <h2><a href="<?=$this->uri('/group/' . $item['groupKey'])?>" class="item-user"><?=$item['groupName']?></a></h2>
                                </div>
                                <div class="item-meta">
                                    <table class="table-condensed">
                                        <tbody>
                                            <tr>
                                                <td><?=$this->_('Create Time')?>: 
                                                    <?=$item['createTime']?>
                                                </td>
                                                <td><?=$this->_('Members')?> : <a href=""><?=$item['Count']['memberCount']?></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="item-content">
                                </div>
                            </div>
                            <a class="pull-left" href="<?=$this->uri('/group/' . $item['groupKey'])?>">
                            <?if(isset($item['File'])):?>
                                <img class="media-object img-rounded" src="<?=$this->thumb($item['File'][0]['Thumb'], array('c_fill', 'w_90', 'h_90'))?>" width="90" />
                            <?else:?>
                                <img class="media-object img-rounded" src="<?=$this->assets('/module/epic/img/group-default.png')?>" width="90" />
                            <?endif?>
                            </a>
                            <div class="item-absolute item-action">
                                <form <?=$this->formAttr($unjoinForm)?> class="group-checker group-quit-form hide" data-checker="<?=$item['id']?>">
                                    <?=$unjoinForm->restful();?>
                                    <?=$unjoinForm->helper('group_id', 'formHidden', array('class' => '', 'value' => $item['id']))?>
                                    <?=$unjoinForm->helper('user_id', array('class' => ''))?>
                                    <?=$this->callback()?>
                                    <button class="btn btn-small item-action-main">Quit</button>
                                </form>
                                <form <?=$this->formAttr($form)?> class="group-checker group-join-form hide" data-checker="<?=$item['id']?>">
                                    <?=$form->restful();?>
                                    <?=$form->helper('group_id', 'formHidden', array('class' => '', 'value' => $item['id']))?>
                                    <?=$form->helper('user_id', array('class' => ''))?>
                                    <?=$this->callback()?>
                                    <button class="btn btn-small item-action-main">Join</button>
                                </form>
                                <span class="group-edit-btn group-checker hide" data-checker="<?=$item['id']?>"><a href="<?=$this->uri('/groups/edit/' . $item['id'])?>" class="btn btn-small ">Edit</a></span>
                            </div>
                        </div>
                        <?endforeach?>
                    </div><!--activity-list end-->

                    <?if($this->paginator):?>
                    <?=$this->paginator->setPath('/groups/')->setBaseQuery($this->query);?>
                    <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                    <?endif;?>
                </div><!--group main end-->
            </div><!--page main left end-->
            <div class="span4">
               <?=$this->widget('Epic', 'widgets/groupsside', $this->vars())?> 
            </div>

        </div><!--page main right end-->
    </div><!-- page-bg end-->
</div><!--container end-->


