<?
$title = 'Groups';
$this->headTitle($title, 'SET');
$user = $this->user;
$item = $this->item;
?>

<div class="container">
    <header class="group-header">
    <?=$this->widget('Epic', 'widgets/groupnav', $this->vars())?> 
    </header>
</div>

<div class="container">
    <div class="page-bg">
        <div class="row">
            <div class="span8">
                <div class="group-main">
                    <?=$this->widget('Epic', 'widgets/groupcard', $this->vars())?>  
                    <div class="blog-list vlist">
                        <?
                        $formAction = '';
                        if(!$this->form){
                            $formAction = $this->post['id'] ? $this->uri('/blog/edit/') : $this->uri('/group/post/');
                        }
                        ?>
                        <?=$this->widget('Epic', 'epic/blog/form', array(
                            'form' => $this->form,
                            'formAction' => $formAction,
                            'item' => $this->post,
                            'callbackInput' => '<input type="hidden" name="callback" value="' . '/group/' . $item['groupKey'] . '">',
                            'formExt' => '<input type="hidden" name="group_id" value="' . $this->item['id'] . '">'
                        ))?>
                    </div>
                </div><!--group main end-->
            </div><!--page main left end-->
            <div class="span4">
                <?=$this->widget('Epic', 'widgets/groupside', $this->vars())?>  
            </div>
        </div><!--page main right end-->
    </div><!-- page-bg end-->
</div><!--container end-->
