<? 
$title = $this->_('Blog Posts');
$this->headTitle($title, 'SET');
?>
<div class="container">

	<header class="page-header">
    <h2 class=""><?=$title?></h2>
	</header>

	<?if($this->posts):?>
	<?foreach($this->posts as $key=>$post):?>
	<div id="post_<?=$post['id'] ?>" class="table">
        <h3><a href="<?=$this->Uri('/blog/page/' . $post['urlName'])?>" class="title"><?=$post['title'] ?></a></h3>
		<p><?=$post['preview'];?></p>
	</div>
	<?endforeach;?>
	<?else:?>
    <p><?=$this->_('No blog post found')?></p>
	<?endif;?>

</div>
