<?php 
$title = 'Blog Posts ';
$this->headTitle($title, 'SET');
?>
<div class="page_header">
<h2 class="">Blog Posts</h2>
</div>


<?if($this->posts):?>
<?foreach($this->posts as $key=>$post):?>
<div id="post_<?=$post['id'] ?>" class="table">
	<h3><a href="<?=$this->Uri('/blog/post/' . $post['id'])?>" class="title"><?=$post['title'] ?></a></h3>
	<p><?=$post['preview'];?></p>
</div>
<?endforeach;?>
<?endif;?>
