<?
$item = $this->item;
$formAction = $this->formAction;
$form = $this->form;
if(!$formAction){
    $formAction = $item['id'] ? $this->uri('/blogs/edit/') : $this->uri('/blogs/create/');
}
$method = $item['id'] ? 'put' : 'post';
$formExt = $this->formExt;

if(!$form) {
    $form = $item['id'] ? new Epic\Form\PostEditForm() : new Epic\Form\PostCreateForm();
}
$form->setAction($formAction)
->useSubFormGroup()
->setMethod($method)
->setView($this)
->bind($item)
->prepare();
?>
<form <?=$this->formAttr($form)?> class="form">
    <?=$form->restful();?>
    <?=$form->helper('id');?>
    <?=$formExt?>
    <?if($this->callbackInput):?>
        <?=$this->callbackInput;?>
    <?endif;?>

    <fieldset class="">
        <div class="control-group <?=$form->isError('title') ? 'error' : '';?>">
            <?=$form->helper('title', 'label', array('class' => 'control-label'))?>
            <div class="controls docs-input-sizes">
                <?=$form->helper('title', array('class' => 'input-block-level'))?>
                <div class="help-block"><?=$form->helper('title', 'formElementErrors')?></div>
            </div>
        </div>

        <div class="control-group <?=$form->isError(array('Text', 'content')) ? 'error' : '';?>">
            <div id="editor-left" class="controls">
                <?=$form->helper(array('Text', 'content'), 'formTextarea', array('class' => 'input-block-level editor-html simple', 'rows' => '15',))?>
            </div>
            <div id="editor-right" class="markdown-preview"></div>
            <div class="help-block"><?=$form->helper(array('Text', 'content'), 'formElementErrors')?></div>
        </div>

        <div class="control-group <?=$form->isError('status') ? 'error' : '';?> hide">
            <?=$form->helper('status', 'label', array('class' => 'control-label'))?>
            <div class="controls">
                <?=$form->helper('status', 'formSelect', array('class' => ''))?>
                <div class="help-block"><?=$form->helper('status', 'formElementErrors')?></div>
            </div>
        </div>

        <div class="control-group <?=$form->isError('codeType') ? 'error' : '';?> hide">
            <?=$form->helper('codeType', 'label', array('class' => 'control-label'))?>
            <div class="controls">
                <?=$form->helper('codeType', 'formRadio', array('class' => 'checkbox inline'))?>
                <div class="help-block"><?=$form->helper('codeType', 'formElementErrors')?></div>
            </div>
        </div>

        <div class="control-group <?=$form->isError('visibility') ? 'error' : '';?> hide">
            <?=$form->helper('visibility', 'label', array('class' => 'control-label'))?>
            <div class="controls">
                <?=$form->helper('visibility', 'formSelect', array('class' => ''))?>
                <div class="help-block"><?=$form->helper('visibility', 'formElementErrors')?></div>
            </div>
        </div>
        <div class="control-group <?=$form->isError('language') ? 'error' : '';?> hide">
            <?=$form->helper('language', 'label', array('class' => 'control-label'))?>
            <div class="controls">
                <?=$form->helper('language', 'formSelect', array('class' => ''))?>        
                <div class="help-block"><?=$form->helper('language', 'formElementErrors')?></div>
            </div>
        </div>
        <div class="control-group <?=$form->isError('commentStatus') ? 'error' : '';?> hide">
            <?=$form->helper('commentStatus', 'label', array('class' => 'control-label'))?>
            <div class="controls">
                <?=$form->helper('commentStatus', 'formSelect', array('class' => ''))?>        
                <div class="help-block"><?=$form->helper('commentStatus', 'formElementErrors')?></div>
            </div>
        </div>

        <div class="control-group <?=$form->isError('commentType') ? 'error' : '';?> hide">
            <?=$form->helper('commentType', 'label', array('class' => 'control-label'))?>
            <div class="controls">
                <?=$form->helper('commentType', 'formSelect', array('class' => ''))?>        
                <div class="help-block"><?=$form->helper('commentType', 'formElementErrors')?></div>
            </div>
        </div>
    </fieldset>

    <div class="form-actions">
        <button type="submit" class="btn btn-info btn-large"><?=$this->_('Publish');?></button>
    </div>
</form>
