<?
$item = $this->item;
$title = $this->_('Delete Post');
$this->headTitle($title, 'SET');
$form = new Blog\Form\PostDeleteForm();

$form->setView($this)
->setMethod('delete')
->setAction($this->uri('/blogs/remove/'))
->bind($item)
->prepare();
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span6">
                                <div class="page-main-header">
                                    <a href="<?=$this->uri('/blogs/create/')?>" class="btn btn-small btn-orange pull-right"><i class="icon-pencil"></i> Write New</a>
                                    <h3><?=$this->_($title)?></h3>
                                </div>
                                <div class="">
                                    <?if($item):?>
                                    <div class="alert alert-block">
                                        <div class="typo">
                                        <h2 class="alert-heading"><?=$title?></h2>
                                        <p><?=$this->_(array('Post %title% will be deleted, are you sure?', $item['title']))?></p>
                                        <p>
                                        <form class="form-horizontal" <?=$this->formAttr($form)?>>
                                            <?=$form->restful();?>
                                            <?=$this->formInput($form->get('id'));?>
                                            <button class="btn btn-danger" type="submit"><?=$this->_('Delete')?></button>
                                            <input name="callback" type="hidden" value="<?=$this->callback?>" />
                                        </form>
                                        </p>
                                        </div>
                                    </div>
                                    <?else:?>
                                    <div class="alert alert-success container">
                                        <h2 class="alert-heading"<?=$this->_('>Post have been deleted')?></h2>
                                    </div>
                                    <?endif?>
                                </div><!--main form end-->
                                <?if($this->paginator):?>
                                <?=$this->paginator->setPath('/my/blog/')->setBaseQuery($this->query);?>
                                <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                                <?endif;?>

                            </div><!--page main left end-->
                            <div class="span3">
                                <div class="page-extra">
                                    <?=$this->widget('Epic', 'widgets/userextra')?>
                                </div>
                            </div><!--page main right end-->
                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside', $this->vars())?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->



