<?
$this->headTitle('Epicurissimo compass | communauté privé pour les pros et les connaisseur du gastronomie et vin', 'SET');
$user = $this->user;
$items = $this->items;
$item = $this->item;
$viewAsGuest = $this->viewAsGuest;
$form = new Activity\Form\MessageCreateForm();
$form->useSubFormGroup()
     ->setMethod('post')
     ->setView($this)
     ->setAction($this->uri('/activity/'))
     ->prepare();

$deleteForm = new Activity\Form\MessageDeleteForm();

$deleteForm->setView($this)
->setMethod('delete')
->setAction($this->uri('/feed/' . $item['messageHash']))
->bind($item)
->prepare();
?>

<div class="page-inner">
    <div class="container">
        <div class="profile-cover">
            <?=$this->widget('Epic', 'widgets/profilenav', $this->vars())?>
        </div>
    </div><!-- above container end -->
    <div class="container">
        <div class="profile-main">
            <div class="row">
                <div class="span8">
                    <?=$this->widget('Epic', 'widgets/profilemeta', $this->vars())?>

                    <div class="profile-activities">


                        <div class="page-header border-header">
                            <h3></h3>
                        </div>

                        <div class="activity-list vlist">
                            <div class="item">
                                <a href="<?=$this->uri('/user/' . $item['user_id'])?>" title="" class="item-absolute item-userface">
                                    <img src="<?=$item['User']['Avatar'] ? $this->thumb($item['User']['Avatar']['Thumb'], array('h_60', 'w_60', 'c_fill')) :  $this->assets('/module/epic/img/default_avatar.png')?>" alt=""  width="60" height="60" class="img-rounded"/>
                                </a>
                                <div class="item-inline item-text span6">
                                    <div class="item-content">
                                        <div class="item-title"><a href="<?=$this->uri('/user/' . $item['user_id'])?>" class="item-user"><?=$item['User']['userName']?></a> Said:</div>
                                        <p><?=$item['ContentHtml']?></p>
                                        <?if($item['File']):?>
                                        <div class="item-image">
                                            <p><a href="<?=$item['File'][0]['Thumb']?>" class="item-preview image" data-preview-type="image" data-url="<?=$this->thumb($item['File'][0]['Thumb'], array('w_400'))?>" data-width="400"><img src="<?=$this->thumb($item['File'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                                        </div>
                                        <?endif?>

                                         <?if($item['Video']):$video = $item['Video'];?>
                                        <div class="item-video">
                                            <?if($video['thumbnail']):?>
                                            <a href="<?=$video['url']?>" class="item-preview video" data-preview-type="video" data-url="<?=$video['swf']?>" data-width="<?=$video['width']?>" data-height="<?=$video['height']?>"><img src="<?=$video['thumbnail']?>" alt="video preview" class="img-polaroid" width="200" /><i class="icon-play btn-play"></i></a>
                                            <?else:?>
                                            <a href="<?=$video['url']?>" class="item-preview video" data-preview-type="video" data-url="<?=$video['swf']?>" data-width="<?=$video['width']?>" data-height="<?=$video['height']?>"><div class="video-no-preview"></div><i class="icon-play btn-play"></i></a>
                                            <?endif?>
                                        </div>
                                        <?endif?>

                                        <?if($item['ForwardActivity']): $subItem = $item['ForwardActivity'];?>
                                        <div class="well">
                                            <p><?=$subItem['ContentHtml']?></p>
                                            <?if($subItem['File']):?>
                                            <div class="item-image">
                                                <p><a href="<?=$subItem['File'][0]['Thumb']?>"><img src="<?=$this->thumb($subItem['File'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                                            </div>
                                            <?endif?>
                                            <div class="item-action">
                                                <p class="pull-right"><a href="javascript:;" class="item-func comment" data-activity-comment="<?=$subItem['id']?>"><i class="icon-comment"></i> Comments (<span class="highlight"><?=$subItem['commentedCount']?></span>)</a></p>
                                                <p class="pull-left">
                                                <a href="<?=$this->uri('/feed/' . $subItem['messageHash'])?>" class="item-id"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($subItem['createTime'])?>" datetime="<?=$this->datetime()->isoTime($subItem['createTime'])?>"><?=$this->datetime($subItem['createTime'])?></time></a>
                                                </p>
                                            </div>
                                        </div>
                                        <?endif?>

                                        <div class="item-action">
                                            <p class="pull-right">
                                                <a href="javascript:;" class="item-func remove <?=$viewAsGuest ? 'hide' : ''?>"><i class="icon-remove"></i> Delete</a>
                                                <a href="javascript:;" class="item-func comment" data-activity-comment="<?=$item['id']?>"><i class="icon-comment"></i> Comments (<span class="highlight"><?=$item['commentedCount']?></span>)</a>
                                            </p>
                                            <p class="pull-right hide"><a href="#activity-form" class="item-func reference" data-activity-reference="<?=$item['id']?>" data-activity-text="@<?=$item['User']['userName']?> "><i class="icon-share-alt"></i> RT (<span class="highlight"><?=$item['transferredCount']?></span>)</a></p>
                                            <p class="pull-left">
                                            <a href="<?=$this->uri('/feed/' . $item['messageHash'])?>" class="item-id"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['createTime'])?>" datetime="<?=$this->datetime()->isoTime($item['createTime'])?>"><?=$this->datetime($item['createTime'])?></time></a>
                                            </p>
                                        </div>
                                    </div>

                                    <div class="item-remove hide">
                                        <div class="alert alert-block">
                                            <p><?=$this->_(array('Current message will be deleted, are you sure?', $item['id']))?></p>
                                            <p>
                                            <form class="form-horizontal" <?=$this->formAttr($deleteForm)?>>
                                                <?=$deleteForm->restful();?>
                                                <?=$this->formInput($deleteForm->get('id'));?>
                                                <button class="btn btn-danger" type="submit"><?=$this->_('Delete')?></button>
                                                <input name="callback" type="hidden" value="<?=$this->uri('/home')?>" />
                                                <a class="btn item-func remove-cancel" href="<?=$this->uri('/feed/' . $item['messageHash'])?>"><?=$this->_('No')?></a>
                                            </form>
                                            </p>
                                        </div>
                                    </div>

                                    <div class="item-sub-wrap">
                                        <?if($item['commentedCount']):?>
                                        <div class="item-sub-title">
                                            <?=$item['commentedCount']?> Comments in Total
                                        </div>
                                        <?endif?>

                                        <div class="item-sub-form">
                                            <form <?=$this->formAttr($form)?> class="">
                                                <?=$form->helper('messageType', 'formHidden', array('class' => '', 'value' => 'comment'))?>        
                                                <?=$form->helper('reference_id', 'formHidden', array('class' => '', 'value' => $item['id']))?>
                                                <fieldset class="form">
                                                    <div class="item-sub-textarea">
                                                        <?=$form->helper('content', 'formTextarea', array('placeholder' => 'Add Comment'))?>        
                                                    </div>
                                                    <div class="item-absolute item-sub-submit">
                                                        <button type="submit" class="btn btn-light-brown btn-large">Submit</button>
                                                    </div>
                                                </fieldset>
                                                <input name="callback" type="hidden" value="<?=$this->uri('/feed/' . $item['messageHash'])?>" />
                                            </form>
                                        </div>

                                        <?foreach($items as $item):?>
                                        <div class="item-sub">
                                            <a href="<?=$this->uri('/user/' . $item['user_id'])?>" title="" class="item-absolute item-sub-userface">
                                                <img src="<?=$item['User']['Avatar'] ? $this->thumb($item['User']['Avatar']['Thumb'], array('h_30', 'w_30', 'c_fill')) :  $this->assets('/module/epic/img/default_avatar.png')?>" alt=""  width="30" height="30" class="img-rounded"/>
                                            </a>
                                            <div class="item-sub-content">
                                                <div class="item-sub-title">
                                                    <a href="<?=$this->uri('/user/' . $item['user_id'])?>" class="item-sub-user"><?=$item['User']['userName']?></a>
                                                    <a href="<?=$this->uri('/feed/' . $item['messageHash'])?>" class="item-sub-id"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['createTime'])?>" datetime="<?=$this->datetime()->isoTime($item['createTime'])?>"><?=$this->datetime($item['createTime'])?></time></a>
                                                </div>
                                                <p><?=$item['ContentHtml']?></p>
                                            </div>
                                        </div>
                                        <?endforeach?>

                                    </div>
                                </div>
                            </div>
                        </div><!--activity-list end-->

                    </div><!--profile-activities end-->
                </div><!--left span8 end-->
                <div class="span4">
                    <?=$this->widget('Epic', 'widgets/profileside', $this->vars())?>
                </div><!--right span4 end-->
            </div><!--row end-->
        </div><!--profil-main end-->
    </div><!--container end-->
</div><!--page inner end-->

<?=$this->widget('File', 'file/index')?>

<script>
eva.ready(function(){
    var modal = $("#fileupload-modal");
    modal.hide();
    eva.loader(eva.assets('/module/code/js/eva.jquery.evaTip.js'), function(){
            modal.hide();
            $('#activity-box-image-button').on('click', function() {
                    $(this).evaTip("show", {
                            'tip' : modal,
                            'offsetX' : -75,
                            'offsetY' : 30,
                            'direction' : 'bottom'			
                    });
                    return false;
            });

            modal.find(".close").on("click", function(){
                    modal.hide();
            });
    });

    var modal = $("#fileupload-modal");
    modal.hide();
    eva.loader(eva.assets('/module/code/js/eva.jquery.evaTip.js'), function(){
            modal.hide();
            $('#activity-box-image-button').on('click', function() {
                    $(this).evaTip("show", {
                            'tip' : modal,
                            'offsetX' : -75,
                            'offsetY' : 30,
                            'direction' : 'bottom'			
                    });
                    return false;
            });

            modal.find(".close").on("click", function(){
                    modal.hide();
            });
    });

    var uploader = $('#singlefileupload');
    var form = $("#activity-form");
    var textarea = form.find('textarea');
    uploader.bind('fileuploaddone', function (e, data) {
            var file = data.result[0];
            form.find('input[name="MessageFile[file_id]"]').val(file.id);
            modal.find(".close").hide();
    });

    $(".activity-box-text").live('click', function(){
            textarea.val(textarea.val() + $(this).attr('data-activity-text'));
            return false;
    });

    $(".item-func.reference").live('click', function(){
            textarea.val(textarea.val() + $(this).attr('data-activity-text'));
            form.find('input[name="reference_id"]').val($(this).attr('data-activity-reference'));
            form.find('input[name="messageType"]').val('forward');
    });

    $(".item-func.comment").live('click', function(){
            var item = $(this).parentsUntil('.item').parent();
            var idUrl = item.find('.item-id').attr('href');
            item.find('.item-sub-ajax').load(idUrl + ' .item-sub-wrap', function(){
                    $(this).show();
            });
    });

    $(".item-func.remove").live('click', function(){
            var item = $(this).parentsUntil('.item').parent();
            var removeForm = item.find('.item-remove');
            if(!removeForm[0]){
            
            } else {
                removeForm.show();
            }
            return false;
    });

    $(".item-func.remove-cancel").live('click', function(){
            var item = $(this).parentsUntil('.item').parent();
            var removeForm = item.find('.item-remove');
            removeForm.hide();
            return false;
    });


    var maxMessage = 140;
    var countHandler = $('.activity-box-count');
    var messageLetterCount = function(){
        countHandler.html(maxMessage - textarea.val().length);
    }

    textarea.live('keyup', function(){
            messageLetterCount();
    });
});
</script>

