<?
$user = $this->item;
$title = $this->_('Delete User');
$this->headTitle($title, 'SET');
$form = new User\Form\UserDeleteForm();

$form->setMethod('delete')
     ->setView($this)
     ->setAction($this->uri('/admin/user/'))
     ->bind($item)
     ->prepare();
?>

<?if($user):?>
<div class="alert alert-block">
   <h2 class="alert-heading"><?=$title?></h2>
   <p><?=$this->_(array('User %username% will be deleted, are you sure?', $user['userName']))?></p>
   <p>
		<form class="form-horizontal" <?=$this->formAttr($form)?>>
			<?=$form->restful();?>
			<?=$this->formInput($form->get('id'));?>
            <button class="btn btn-danger" type="submit"><?=$this->_('Delete')?></button>
            <input name="callback" type="hidden" value="<?=$this->callback?>" />
            <a class="btn" href="<?=$this->callback?>"><?=$this->_('Go Back')?></a>
   		</form>
	</p>
</div>
<?else:?>
<div class="alert alert-success container">
    <h2 class="alert-heading"><?=$this->_('User has been deleted')?></h2>
</div>
<?endif?>
