<?
$title = 'Albums';
$this->headTitle($title, 'SET');
$user = $this->user;
$items = $this->items;
$viewAsGuest = $this->viewAsGuest;
?>

<div class="page-inner">
    <div class="container">
        <?=$this->widget('Epic', 'widgets/profilenav', $this->vars())?>
    </div><!-- above container end -->
    <div class="container">
        <div class="profile-main">
            <div class="row">
                <div class="span8">
                    <?=$this->widget('Epic', 'widgets/profilemeta', $this->vars())?>

                    <div class="profile-activities">

                        <div class="page-header border-header">
                            <h3><?=$this->_($title);?></h3>
                        </div>

                                <div class="album-list">
                                    <?if(count($items) > 0 )?>
                                    <?for($i=0;$i< ceil(count($items) / 4);$i++):?>
                                    <div class="row-fluid stack-row">
                                        <?for($j= ($i * 4);$j< (4 * ($i+1));$j++):?>
                                        <?if(isset($items[$j])){$item = $items[$j];}else{continue;}?>
                                        <div class="span3">
                                            <div class="stack">	
                                                <a href="<?=$this->uri('/user/' . $item['user_name'] . '/albums/' . $item['urlName']);?>">
                                                    <?if(isset($item['Cover']) && $item['Cover']):?>
                                                        <img src="<?=$this->thumb($item['Cover']['Thumb'], array('c_fill', 'w_180', 'h_180'))?>" width="180" />
                                                    <?else:?>
                                                        <img src="<?=$this->assets('/module/epic/img/album-default.png')?>" width="180" alt="" />
                                                    <?endif?>
                                                </a>
                                            </div>
                                            <p class="caption">
                                                <a href="<?=$this->uri('/user/' . $item['user_name'] . '/albums/' . $item['urlName']);?>" class="caption-title"><?=$item['title']?></a>
                                                <span class="lowlight">(<?=$item['ImageCount']['imageCount']?> Photos Total)</span>
                                            </p>
                                        </div>
                                        <?endfor;?>
                                    </div>
                                    <?endfor;?>
                                </div><!--album-list end-->
                        <?if($this->paginator):?>
                        <?=$this->paginator->setPath('/user/' . $user['userName'] . '/albums/')->setBaseQuery($this->query);?>
                        <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                        <?endif;?>


                    </div><!--profile-activities end-->
                </div><!--left span8 end-->
                <div class="span4">
                    <?=$this->widget('Epic', 'widgets/profileside', $this->vars())?>
                </div><!--right span4 end-->
            </div><!--row end-->
        </div><!--profil-main end-->
    </div><!--container end-->
</div><!--page inner end-->
