<?
$title = 'Album ' . $item['title'];
$album = $item['title'];
$this->headTitle($title, 'SET');
$user = $this->user;
$items = $this->items->toArray();
$viewAsGuest = $this->viewAsGuest;
?>

<div class="page-inner">
    <div class="container">
        <?=$this->widget('Epic', 'widgets/profilenav', $this->vars())?>
    </div><!-- above container end -->
    <div class="container">
        <div class="profile-main">
            <div class="row">
                <div class="span8">
                    <?=$this->widget('Epic', 'widgets/profilemeta', $this->vars())?>

                    <div class="profile-activities">

                        <div class="page-header border-header">
                            <h3><?=$this->_($title);?></h3>
                        </div>

                                <div class="album-photos">
                                    <?if(count($items) > 0 )?>
                                    <?for($i=0;$i< ceil(count($items) / 4);$i++):?>
                                    <div class="row-fluid stack-row">
                                        <?for($j= ($i * 4);$j< (4 * ($i+1));$j++):?>
                                        <?if(isset($items[$j])){$item = $items[$j]['Image'];}else{continue;}?>
                                        <div class="thumbnail span3">
                                            <a href="<?=$this->thumb($item['Thumb'], array('w_1024'))?>"  class="gallery"  rel="event-album">
                                                <?if(isset($item['Thumb']) && $item['Thumb']):?>
                                                <img src="<?=$this->thumb($item['Thumb'], array('c_fill', 'w_180', 'h_180'))?>" width="100%" class="" />
                                                <?endif?>
                                            </a>
                                        </div>
                                        <?endfor;?>
                                    </div>
                                    <?endfor;?>
                                </div><!--album-list end-->


                    </div><!--profile-activities end-->
                </div><!--left span8 end-->
                <div class="span4">
                    <?=$this->widget('Epic', 'widgets/profileside', $this->vars())?>
                </div><!--right span4 end-->
            </div><!--row end-->
        </div><!--profil-main end-->
    </div><!--container end-->
</div><!--page inner end-->
