<?
$title = 'Groups';
$this->headTitle($title, 'SET');
$user = $this->user;
$items = $this->items;
$viewAsGuest = $this->viewAsGuest;
?>

<div class="page-inner">
    <div class="container">
        <?=$this->widget('Epic', 'widgets/profilenav', $this->vars())?>
    </div><!-- above container end -->
    <div class="container">
        <div class="profile-main">
            <div class="row">
                <div class="span8">
                    <?=$this->widget('Epic', 'widgets/profilemeta', $this->vars())?>

                    <div class="profile-activities">

                        <div class="page-header border-header">
                            <h3><?=$this->_($title);?></h3>
                        </div>

                        <div class="blog-list vlist">
                            <?foreach($items as $item):?>
                            <?$item = $item['Group'];?>
                            <div class="item">
                                <div class="item-title"><h2><a href="<?=$this->uri('/group/' . $item['groupKey'])?>"><?=$item['groupName']?></a></h2></div>
                                <div class="item-meta">
                                    <!--
                                    <p class="pull-right"><i class="icon-comment"></i> Members (<span class="highlight"><?=$item['memberCount']?></span>)</p>
                                    -->
                                    <p class="pull-left">
                                    <time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['createTime'])?>" datetime="<?=$this->datetime()->isoTime($item['createTime'])?>"><?=$this->datetime($item['createTime'])?></time>
                                    </p>
                                </div>
                                <div class="item-inline item-text">
                                    <?if($item['GroupFile']):?>
                                    <div class="item-image pull-left">
                                        <p><a href="<?=$item['GroupFile'][0]['Thumb']?>"><img src="<?=$this->thumb($item['GroupFile'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                                    </div>
                                    <?endif?>

                                    <?=$this->subText($item['Text']['content'], 250)?>
                                </div>
                            </div>
                            <?endforeach?>
                        </div><!--activity-list end-->
                        <?if($this->paginator):?>
                        <?=$this->paginator->setPath('/user/' . $user['userName'] . '/blog/')->setBaseQuery($this->query);?>
                        <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                        <?endif;?>


                    </div><!--profile-activities end-->
                </div><!--left span8 end-->
                <div class="span4">
                    <?=$this->widget('Epic', 'widgets/profileside', $this->vars())?>
                </div><!--right span4 end-->
            </div><!--row end-->
        </div><!--profil-main end-->
    </div><!--container end-->
</div><!--page inner end-->
