<?
$title = 'Members';
$title = $this->_($title);
$this->headTitle($title, 'SET');

$userSearchForm = $this->form ? $this->form : new Epic\Form\UserSearchForm();
$userSearchForm->setView($this)
     ->setMethod('get')
     ->setAction($this->uri('/users/list/'))
     ->prepare();

$categories = array(
    'hot' => array(
        'label' => 'Event Host',
        'url'   => $this->uri('/data/eventuser/', array('role' => $this->query['role'], 'rows' => 9)),
    ),
    'new' => array(
        'label' => 'New Members',
        'url'   => $this->uri('/data/user/', array('order' => 'timedesc', 'role' => $this->query['role'], 'rows' => 9))
    ),
    'flag' => array(
        'label' => 'Feature Members',
        'url'   => $this->uri('/data/user/', array('order' => 'followdesc', 'role' => $this->query['role'], 'rows' => 9))
    ),
    'vip' => array(
        'label' => 'Event Host',
        'url'   => $this->uri('/data/user/', array('order' => 'timedesc', 'role' => 'PAID_MEMBER', 'rows' => 9))
    ),
);

?>
 <div class="container">
     <header class="member-header">
     <div class="row">
         <div class="span3">
             <h2><a href="/users/"><?=$this->_('Members');?></a></h2>
         </div><!--page main right end-->
         <div class="span9">
             <nav class="nav-member">
             <a class="pull-right margin10h" href="<?=$this->uri('/users/list/')?>"><?=$this->_('Find Friend Here');?></a>
             <ul>
                 <li><a class="<?=!$this->query['role'] ? 'active' : null?>" href="<?=$this->uri('/users/')?>">All</a></li>
                 <li><a class="<?=$this->query['role'] == 'CONNOISSEUR_MEMBER' ? 'active' : null?>" href="<?=$this->uri('/users/?role=CONNOISSEUR_MEMBER')?>"><?=$this->_('Connoisseur');?></a></li>
                 <li><a class="<?=$this->query['role'] == 'PROFESSIONAL_MEMBER' ? 'active' : null?>" href="<?=$this->uri('/users/?role=PROFESSIONAL_MEMBER')?>"><?=$this->_('Professional');?></a></li>
                 <li><a class="<?=$this->query['role'] == 'PAID_MEMBER' ? 'active' : null?>" href="<?=$this->uri('/users/?role=PAID_MEMBER')?>"><?=$this->_('Event Host');?></a></li>
                 <li><a class="<?=$this->query['role'] == 'CORPORATE_MEMBER' ? 'active' : null?>" href="<?=$this->uri('/users/?role=CORPORATE_MEMBER')?>"><?=$this->_('More to Discover');?></a></li>
             </ul>
             </nav>
         </div><!--page main left end-->
     </div>
     </header>
 </div>



 <div class="container">
     <div class="member-bg">
         <div class="row">
             <div class="span2">
                 <div class="member-side">
                     <div class="form-wrap">
                         <form <?=$this->formAttr($userSearchForm)?> class="form form-inline">
                             <div class="input-append">
                                 <?=$userSearchForm->helper('keyword', array('class' => 'input-small', 'placeholder' => 'Keyword...'))?>
                                 <span class="add-on"><button class="btn-search" type="submit"><i class="icon-search"></i></button></span>
                             </div>
                         </form>
                     </div>

                     <ul id="member-tab" class="nav nav-tabs">
                         <li class="active">
                         <a href="#by-industry"><?=$this->_('By Interest');?></a>
                         </li>
                         <li><a href="#by-city"><?=$this->_('By City');?></a></li>
                     </ul>
                     <div class="tab-content">
                         <div id="by-industry" class="tab-pane fade in active">
                             <?$industries = $userSearchForm->get('interest')->getValueOptions();?>
                             <?if($industries):?>
                             <ul class="member-section">
                                 <?foreach($industries as $key => $industry):?>
                                 <li><a href="<?=$this->uri('/users/list/?interest=' . $industry['value'])?>"><?=$industry['label']?></a></li>
                                 <?endforeach?>
                             </ul>
                             <?endif?>
                         </div>
                         <div id="by-city" class="tab-pane fade">
                             <?$cities = $userSearchForm->get('city')->getValueOptions();?>
                             <?if($cities):?>
                             <ul class="member-section">
                                 <?foreach($cities as $key => $citiarea):?>
                                 <li><?=$citiarea['label']?></li>
                                 <?foreach($citiarea['options'] as $city):?>
                                 <li><a href="<?=$this->uri('/users/list/?city=' . $city['value'])?>"><?=$city['label']?></a></li>
                                 <?endforeach?>
                                 <?endforeach?>
                             </ul>
                             <?endif?>
                         </div>
                     </div>
                 </div>
             </div><!--page main left end-->
             <div class="span10 box-shadow-left">
                 <div class="member-main">
                    <script id="member-wall" type="text/x-tmpl" data-url="<?=$this->uri('/data/user/', array('flag' => 1,'role' => $this->query['role'],'rows' => 37))?>">
                    <div class="member-wall">
                         <ul>
                         {% if(o.items.length > 0) { %}
                         {% for (var i=0, item; item=o.items[i]; i++) { %}
                             <li><a href="<?=$this->uri('/user/')?>{%=item.userName%}">
                                 {% if(item.Avatar.Thumb) { %}
                                    <img src="{%=eva.thumb(item.Avatar.Thumb, 'c_fill,h_70,w_70')%}" alt="" class="img-rounded" width="70" height="70" />
                                 {% } else { %}
                                    <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="img-rounded" width="70" height="70" />
                                 {% } %}
                                 <div class="mask">{%=item.userName%}</div>
                             </a></li>
                         {% } %}
                         {% } %}
                         </ul>
                     </div>
                    </script> 
                    
                     <div class="row-fluid">
                         <ul class="thumbnails member-thumbnails">
                             <?foreach($categories as $key=>$cate):?>
                             <li class="span3">
                             <script id="<?=$key?>" type="text/x-tmpl" data-url="<?=$cate['url']?>">
                             <div class="thumbnail <?=$key?>">
                                 <div class="thumbnail-title thumbnail-title-alt">
                                     <?=$this->_($cate['label'])?>
                                 </div>
                                 {% if(o.items.length > 0) { %}      
                                 <div class="thumbnail-list">
                                     {%item=o.items[0]; %}
                                     <a href="<?=$this->uri('/user/')?>{%=item.userName%}">
                                        {% if(item.Avatar.Thumb) { %}
                                            <img src="{%=eva.thumb(item.Avatar.Thumb, 'c_fill,h_200,w_200')%}" alt="" class="medium" width="200" height="200" />
                                        {% } else { %}
                                            <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="medium" width="200" height="200" />
                                        {% } %}    
                                     </a>
                                     <div class="thumbnail-line row-fluid">
                                         {% for (var i=1, item; item=o.items[i]; i++) { %}
                                         {% if(i>4) {continue;}%}   
                                         <a href="<?=$this->uri('/user/')?>{%=item.userName%}" class="span3">
                                         {% if(item.Avatar.Thumb) { %}
                                            <img src="{%=eva.thumb(item.Avatar.Thumb, 'c_fill,h_50,w_50')%}" alt="" class="small img-rounded" width="50" height="50" />
                                         {% } else { %}
                                            <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="small img-rounded" width="50" height="50" />
                                         {% } %}   
                                         </a>
                                         {% } %}
                                     </div>
                                     <div class="row-fluid">
                                         {% for (var i=5, item; item=o.items[i]; i++) { %}
                                         <a href="<?=$this->uri('/user/')?>{%=item.userName%}" class="span3">
                                         {% if(item.Avatar.Thumb) { %}
                                            <img src="{%=eva.thumb(item.Avatar.Thumb, 'c_fill,h_50,w_50')%}" alt="" class="small img-rounded" width="50" height="50" />
                                         {% } else { %}
                                            <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="small img-rounded" width="50" height="50" />
                                         {% } %}   
                                         </a>
                                         {% } %}
                                     </div>
                                 </div>
                                 <div class="caption">
                                     <p><a href="">{% if(o.paginator) { %}{%=o.paginator.rowCount%}{% } else { %} {%=o.items.length%} {% } %} <?=$this->_('Members');?></a></p>
                                 </div>
                                 {% } %}
                             </div>
                             </script>  
                             </li>
                             <?endforeach;?>
                         </ul>
                     </div>

                     <div class="page-header border-header">
                         <h3><?=$this->_('By Interests');?></h3>
                     </div>

                     <?if(count($industries) > 0):?>
                     <div class="member-category-wrap">
                         <div class="row-fluid">
                             <ul class="member-category">
                                 <?foreach($industries as $key => $industry):?>
                                 <?if($key > 2){break;}?>
                                 <li class="span4">
                                 <script id="member-category-<?=$key?>" type="text/x-tmpl" data-url="<?=$this->uri('/data/user/', array('interest' => $industry['value'], 'role' => $this->query['role'], 'rows' => 12))?>">
                                 <div class="thumbnail">
                                     <div class="thumbnail-title">
                                         <small class="pull-right"><a href="<?=$this->uri('/users/list/?interest=' . $industry['value'])?>"><?=$this->_('More');?></a></small>
                                         <a href="<?=$this->uri('/users/list/?interest=' . $industry['value'])?>"><?=$this->_($industry['label'])?></a>
                                     </div>
                                     <div class="thumbnail-list">
                                     {% if(o.items.length > 0) { %}
                                         <div class="thumbnail-line row-fluid">
                                             {% for (var i=0, item; item=o.items[i]; i++) { %}
                                             {% if(i>3) {continue;}%}   
                                             <a href="<?=$this->uri('/user/')?>{%=item.userName%}" class="span3">
                                             {% if(item.Avatar.Thumb) { %}
                                                <img src="{%=eva.thumb(item.Avatar.Thumb, 'c_fill,h_50,w_50')%}" alt="" class="small img-rounded" width="50" height="50" />
                                             {% } else { %}
                                                <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="small img-rounded" width="50" height="50" />
                                             {% } %}   
                                                 <span class="name">{%=item.userName%}</span>
                                             </a>
                                             {% } %}
                                         </div>
                                      {% } %}
                                      {% if(o.items.length > 3) { %}   
                                         <div class="thumbnail-line row-fluid">
                                             {% for (var i=4, item; item=o.items[i]; i++) { %}
                                             {% if(i>7) {continue;}%}   
                                             <a href="<?=$this->uri('/user/')?>{%=item.userName%}" class="span3">
                                             {% if(item.Avatar.Thumb) { %}
                                                <img src="{%=eva.thumb(item.Avatar.Thumb, 'c_fill,h_50,w_50')%}" alt="" class="small img-rounded" width="50" height="50" />
                                             {% } else { %}
                                                <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="small img-rounded" width="50" height="50" />
                                             {% } %}   
                                                 <span class="name">{%=item.userName%}</span>
                                             </a>
                                             {% } %}
                                         </div>
                                      {% } %}
                                      {% if(o.items.length > 7) { %}
                                         <div class="thumbnail-line row-fluid">
                                             {% for (var i=8, item; item=o.items[i]; i++) { %}
                                             {% if(i>11) {continue;}%}   
                                             <a href="<?=$this->uri('/user/')?>{%=item.userName%}" class="span3">
                                             {% if(item.Avatar.Thumb) { %}
                                                <img src="{%=eva.thumb(item.Avatar.Thumb, 'c_fill,h_50,w_50')%}" alt="" class="small img-rounded" width="50" height="50" />
                                             {% } else { %}
                                                <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="small img-rounded" width="50" height="50" />
                                             {% } %}   
                                                 <span class="name">{%=item.userName%}</span>
                                             </a>
                                             {% } %}
                                         </div>
                                      {% } %}
                                     </div>
                                 </div>
                                 </script>  
                                 </li>
                                 <?endforeach?>
                             </ul>
                         </div>
                     </div>
                     <?endif?>


                     <?if(count($industries) > 3):?>
                     <div class="member-category-wrap">
                         <div class="row-fluid">
                             <ul class="member-category">
                                 <?foreach($industries as $key => $industry):?>
                                 <?if($key < 3 || $key > 5){continue;}?>
                                 <li class="span4">
                                 <script id="member-category-<?=$key?>" type="text/x-tmpl" data-url="<?=$this->uri('/data/user/', array('interest' => $industry['value'], 'role' => $this->query['role'], 'rows' => 12))?>">
                                 <div class="thumbnail">
                                     <div class="thumbnail-title">
                                         <small class="pull-right"><a href="<?=$this->uri('/users/list/?interest=' . $industry['value'])?>">More</a></small>
                                         <a href="<?=$this->uri('/users/list/?interest=' . $industry['value'])?>"><?=$industry['label']?></a>
                                     </div>
                                     <div class="thumbnail-list">
                                     {% if(o.items.length > 0) { %}
                                         <div class="thumbnail-line row-fluid">
                                             {% for (var i=0, item; item=o.items[i]; i++) { %}
                                             {% if(i>3) {continue;}%}   
                                             <a href="<?=$this->uri('/user/')?>{%=item.userName%}" class="span3">
                                             {% if(item.Avatar.Thumb) { %}
                                                <img src="{%=eva.thumb(item.Avatar.Thumb, 'c_fill,h_50,w_50')%}" alt="" class="small img-rounded" width="50" height="50" />
                                             {% } else { %}
                                                <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="small img-rounded" width="50" height="50" />
                                             {% } %}   
                                                 <span class="name">{%=item.userName%}</span>
                                             </a>
                                             {% } %}
                                         </div>
                                      {% } %}
                                      {% if(o.items.length > 3) { %}   
                                         <div class="thumbnail-line row-fluid">
                                             {% for (var i=4, item; item=o.items[i]; i++) { %}
                                             {% if(i>7) {continue;}%}   
                                             <a href="<?=$this->uri('/user/')?>{%=item.userName%}" class="span3">
                                             {% if(item.Avatar.Thumb) { %}
                                                <img src="{%=eva.thumb(item.Avatar.Thumb, 'c_fill,h_50,w_50')%}" alt="" class="small img-rounded" width="50" height="50" />
                                             {% } else { %}
                                                <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="small img-rounded" width="50" height="50" />
                                             {% } %}   
                                                 <span class="name">{%=item.userName%}</span>
                                             </a>
                                             {% } %}
                                         </div>
                                      {% } %}
                                      {% if(o.items.length > 7) { %}
                                         <div class="thumbnail-line row-fluid">
                                             {% for (var i=8, item; item=o.items[i]; i++) { %}
                                             {% if(i>11) {continue;}%}   
                                             <a href="<?=$this->uri('/user/')?>{%=item.userName%}" class="span3">
                                             {% if(item.Avatar.Thumb) { %}
                                                <img src="{%=eva.thumb(item.Avatar.Thumb, 'c_fill,h_50,w_50')%}" alt="" class="small img-rounded" width="50" height="50" />
                                             {% } else { %}
                                                <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="small img-rounded" width="50" height="50" />
                                             {% } %}   
                                                 <span class="name">{%=item.userName%}</span>
                                             </a>
                                             {% } %}
                                         </div>
                                      {% } %}
                                     </div>
                                 </div>
                                 </script>  
                                 </li>
                                 <?endforeach?>
                             </ul>
                         </div>
                     </div>
                     <?endif?>


                 </div><!--member main end-->
             </div><!--page main right end-->
         </div><!-- row end-->
     </div><!-- page-bg end-->
 </div><!-- container end-->


 <script>
     eva.ready(function(){
             $('#member-tab a').click(function (e) {
                     e.preventDefault();
                     $(this).tab('show');
             });

             $(".member-wall li").eq(13).addClass('medium');
             $(".member-wall li").eq(19).addClass('large');

             var container = $(".member-wall");
             var userWall = function(){
                     container.masonry({
                             itemSelector : 'li',
                             //columnWidth : $(window).width() > 800 ? 320 : 260,
                             isAnimated: true
                     });
             }

             eva.loader(eva.s([
             '/lib/js/jquery/jquery.masonry.js'
             ]), userWall);
     });
 </script>
