<?
$title = 'Dashboard';
$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', $title);

$posts = $this->posts;
?>
<div class="main-area dashboard">

    <div class="row">
        <div class="span10">
            <div class="slate clearfix">
                <a href="<?=$this->uri('/admin/blog/')?>" class="stat-column">
                    <span class="number"><?=$this->postsCount ? $this->postsCount : '0'?></span>
                    <span><?=$this->_('Blog Posts')?></span>
                </a>

                <a href="<?=$this->uri('/admin/file/')?>" class="stat-column">
                    <span class="number"><?=$this->filesCount ? $this->filesCount : '0'?></span>
                    <span><?=$this->_('Uploaded Files')?></span>
                </a>

            </div>
        </div>
    </div>

    <div class="row">

        <div class="span5">
            <div class="slate">
                <div class="page-header">
                    <h2><a href="" class="pull-right iconlink"><i class="icon-rss"></i></a><?=$this->_('New Posts')?></h2>
                </div>
                <table class="orders-table table">
                    <tbody>
                        <?if($posts):?>
                        <?foreach($this->posts as $key=>$post):?>
                        <tr>
                            <td><a href="<?=$this->uri('/admin/blog/' . $post['id'])?>" class="title"><?=$post['title'] ?></a></td>
                            <td class="date"><span class="meta"><?=$post['user_name'] ?> <?=$post['createTime'];?></span></td>
                        </tr>
                        <?endforeach?>
                        <?endif?>
                    </tbody>
                </table>
            </div>
        </div><!-- span5 end-->

        <div class="span5">
            <div class="slate">
                <div class="page-header">
                    <h2><i class="icon-file pull-right"></i><?=$this->_('Uploaded Files')?></h2>
                </div>
                <table class="orders-table table">
                    <tbody>
                        <?if($files):?>
                        <?foreach($this->files as $key=>$file):?>
                        <tr>
                            <td><a href="<?=$this->uri('/admin/file/' . $file['id'])?>" class="title"><?=$file['originalName'] ?></a></td>
                            <td class="date"><span class="meta"><?=$file['user_name'] ?> <?=$file['createTime'];?></span></td>
                        </tr>
                        <?endforeach?>
                        <?endif?>

                    </tbody>
                </table>

            </div>

        </div>

    </div>

</div>
