<? 
$title = $this->_('Find Friends');
$this->headTitle($title, 'SET');
?>
<div class="container">

	<header class="page-header">
    <h2 class=""><?=$title?></h2>
	</header>

            <div class="well">

                <header class="page-header">
                <h4 class=""><?=$this->_('Find your friends with')?>:</h4>
                </header>
                <div class="btn-group btn-group-vertical">
                    <a href="<?=$this->uri('/contacts/import/', array('r' => $this->serverUrl() . '/findfriends/add/?service=google','service' => 'google'))?>" class="btn btn-small">Gmail</a>
                    <a href="<?=$this->uri('/contacts/import/', array('r' => $this->serverUrl() . '/findfriends/add/?service=msn', 'service' => 'msn'))?>" class="btn btn-small">Msn/Hotmail</a>
                </div>
            </div>


</div>
