<?
$item = $this->item;
$forms = $this->forms;
$title = 'User Custom Fields';
$title = $this->_($title);
$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', $title);

$form = new \Eva\Form\RestfulForm();

$form->setMethod('put');
$form->setView($this)
     ->setAction($this->uri('/admin/user/fieldvalue'))
     ->bind($item)
     ->prepare();
?>

<div class="row">
    <form <?=$this->formAttr($form)?>>
        <?=$form->restful();?>
        <div class="span10">
            <div class="slate">
             <ul class="nav nav-tabs">
                <li>
                <a href="<?=$this->uri('/admin/user/' . $item['id'])?>">Edit User</a>
                </li>
                <li class="active"><a href="<?=$this->uri('/admin/user/field/userfield/' . $item['id'])?>"><?=$this->_('User Fields')?></a></li>
                <li><a href="#"><?=$this->_('User Tags')?></a></li>
            </ul>
            </div>
        </div><!--span10 end-->

        <?foreach($forms as $forminfo):?>
<?
$form = new \Eva\Form\RestfulForm($forminfo['name']);
$form->setMethod('put')
->setView($this)
->setMergeElements($forminfo['elements'])
->init()
->setAction($this->uri('/admin/user/fieldvalue'))
->bind($item)
->prepare();
?>
        <div class="span10">
            <div class="slate">
                <fieldset class="form-horizontal">
                    <?foreach($form->getMergeElements() as $element):?>
                    <div class="control-group <?=$form->isError($element['name']) ? 'error' : '';?>">
                        <?=$form->helper($element['name'], 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper($element['name'], 'form' . ucfirst($element['type']), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper($element['name'], 'formElementErrors')?></div>
                        </div>
                    </div>
                    <?endforeach?>

                </fieldset>
            </div>
        </div><!--span10 end-->
        <?endforeach?>


        <div class="span10 listing-buttons">
            <button id="save-publish" class="btn btn-success btn-large"><?=$this->_('Save')?></button>
        </div>
    </form>
</div>
