<? 
$title = 'Form Class Generator';
$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', $title);

$method = 'put';
$form = Eva\Api::_()->getForm('Scaffold\Form\AutoClassForm');

$form->init(array(
    'action' => $this->uri('/scaffold/form/'),
    'method' => $method,
    'values' => $this->tab
));

function selectType($dataName, $dataType, $columnType)
{
    $value = 'text';
    if($dataName == 'id' || strpos($dataName, '_id') !== false){
        return $value = 'hidden';
    }

    switch($dataType){
        case 'varchar':
        break;
        case 'int':
        case 'bigint':
        $value = 'number';
        break;
        case 'enum':
        $value = 'select';
        break;
        case 'datetime':
        $value = 'datetime';
        break;
        case 'text':
        case 'mediumtext':
        case 'longtext':
        $value = 'textarea';
        break;
    }
    return $value;
}

function autoCheck($dataName, $dataType, $columnType)
{
    $check = '';
    if(strpos($dataName, '_') !== false){
        return $check;
    }

    switch($dataType){
        case 'varchar':
        case 'enum':
        case 'text':
        case 'mediumtext':
        case 'longtext':
        $check = 'checked="checked"';
        break;
    }
    return $check;
}
?>

<div class="row">
    <div class="span10">
        <header class="page-header">
        <h2 class="">Check Inputs</h2>
        </header>
    </div>

    <form action="<?=$this->uri('/scaffold/form/' . $this->table)?>" method="post" class="pull-left">
        <?=$form->restful();?>
        <div class="span10">
            <div class="slate">
                <table class="table">
                    <thead>
                        <tr>
                            <th class="span1">
                                <span class="form" data-multiform="createform">
                                    <input type="checkbox" class="multiform-checker" />
                                </span>
                            </th>
                            <th>Field</th>
                            <th class="span2">Input Type</th>
                            <th class="span2">Validators</th>
                            <th class="span2">Filters</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?if($this->columns):?>
                        <?foreach($this->columns as $key=>$column):?>
                        <tr id="column_<?=$column['name'] ?>" class="">
                            <td>
                                <input type="checkbox" class="multiform-item-checkbox" <?=autoCheck($column['name'], $column['data_type'], $column['data_type'])?>  data-multiform="createform" name="column_ids[]" value="<?=$column['name'] ?>" />
                            </td>
                            <td>
                                <a href="#"><?=$column['name'] ?></a>
                                <span class="label"><?=$column['data_type'];?></span>
                                <p>
                                <span class="meta"><?=$column['column_type'];?></span>
                                </p>
                            </td>
                            <td>
                                <?=$form->helper('select_type[]', 'formSelect', array(
                                    'class' => 'span2',
                                    'id' => 'scaffold-form-postform-select-type-' . $key,
                                    'value' => selectType($column['name'], $column['data_type'], $column['data_type'])
                                ))?>
                            </td>
                            <td>
                                <?=$form->helper('validtors[]', 'formMultiCheckbox', array())?>
                            </td> 
                            <td>
                                <?=$form->helper('filters[]', 'formMultiCheckbox', array())?>
                            </td> 
                        </tr>
                        <?endforeach;?>
                        <?endif;?>
                    </tbody>
                </table>
            </div>
        </div><!--span10 end-->
        <div class="span10 listing-buttons">
            <button class="btn btn-info btn-large">Create Form Class</button>
        </div>
    </form>
</div>


<script>
    var validatorMapping = {
            'text' : ['StringLength'],
            'email' : ['EmailAddress'],
            'url' : ['Uri']
    };

    var filtersMapping = {
            'text' : ['StripTags', 'StringTrim'],
            'email' : ['StripTags', 'StringTrim'],
            'url' : ['StripTags', 'StringTrim']
    };
    function autoValidators(){
            var typeSelector = $(this);
            var type = $(this).val();
            var validtor = typeSelector.parentsUntil("tr").parent().find("input[name='validtors[][]']");

            validtor.attr("checked", false);

            var filter = [];
            if(validatorMapping[type]){
                for(var i in validatorMapping[type]){
                        filter.push("[value='" + validatorMapping[type][i] + "']");
                }

                if(filter.length > 0){
                       filter = filter.join(",");
                       validtor.filter(filter).attr("checked", true);
                }

            }
    }
    function autoFilters(){
            var typeSelector = $(this);
            var type = $(this).val();
            var filters = typeSelector.parentsUntil("tr").parent().find("input[name='filters[][]']");

            filters.attr("checked", false);

            var filter = [];
            if(filtersMapping[type]){
                for(var i in filtersMapping[type]){
                        filter.push("[value='" + filtersMapping[type][i] + "']");
                }

                if(filter.length > 0){
                       filter = filter.join(",");
                       filters.filter(filter).attr("checked", true);
                }

            }
    }
    $("select[name='select_type[]']").on("change", autoValidators).each(autoValidators);
    $("select[name='select_type[]']").on("change", autoFilters).each(autoFilters);

</script>
