<? 
$title = 'Form Class Generator';
$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', $title);

$method = 'put';
$form = Eva\Api::_()->getForm('Scaffold\Form\AutoClassForm');

$form->init(array(
    'action' => $this->uri('/scaffold/form/'),
    'method' => $method,
    'values' => $this->tab
));

function selectType($dataName, $dataType, $columnType)
{
    $value = 'text';
    if($dataName == 'id' || strpos($dataName, '_id') !== false){
        return $value = 'hidden';
    }

    switch($dataType){
        case 'varchar':
        break;
        case 'int':
        case 'bigint':
        $value = 'number';
        break;
        case 'enum':
        $value = 'select';
        break;
        case 'datetime':
        $value = 'datetime';
        break;
        case 'text':
        case 'mediumtext':
        case 'longtext':
        $value = 'textarea';
        break;
    }
    return $value;
}
?>

<div class="row">
    <div class="span10">
        <header class="page-header">
        <h2 class="">Check Inputs</h2>
        </header>
    </div>

    <form action="<?=$this->uri('/scaffold/form/' . $this->table)?>" method="post" class="pull-left">
        <?=$form->restful();?>
        <div class="span10">
            <div class="slate">
                <table class="table">
                    <thead>
                        <tr>
                            <th class="span1">
                                <span class="form" data-multiform="createform">
                                    <input type="checkbox" class="multiform-checker" />
                                </span>
                            </th>
                            <th class="span2">Input Type</th>
                            <th class="span2">Validators</th>
                            <th>Field Name</th>
                            <th class="span2">Db Type</th>
                            <th class="span1">Db Type Detail</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?if($this->columns):?>
                        <?foreach($this->columns as $key=>$column):?>
                        <tr id="column_<?=$column['name'] ?>" class="">
                            <td>
                                <input type="checkbox" class="multiform-item-checkbox"  data-multiform="createform" name="column_ids[]" value="<?=$column['name'] ?>" />
                            </td>
                            <td>
                                <?=$form->helper('select_type[]', 'formSelect', array(
                                    'class' => 'span2',
                                    'id' => 'scaffold-form-postform-select-type-' . $key,
                                    'value' => selectType($column['name'], $column['data_type'], $column['data_type'])
                                ))?>
                            </td>
                            <td>
                                <input type="checkbox" name="column_required[]" value="<?=$column['name'] ?>" />
                                <input type="checkbox" name="column_hidden[]" value="<?=$column['name'] ?>" />
                            </td> 
                            <td>
                                <?=$column['name'] ?>
                            </td>
                            <td>
                                <?=$column['data_type'];?>
                            </td>
                            <td>
                                <?=$column['column_type'];?>
                            </td>
                        </tr>
                        <?endforeach;?>
                        <?endif;?>
                    </tbody>
                </table>
            </div>
        </div><!--span10 end-->
        <div class="span10 listing-buttons">
            <button class="btn btn-info btn-large">Create Form Class</button>
        </div>
    </form>
</div>
