<? 
$title = 'Form Html Generator';
$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', $title);

$form = new Scaffold\Form\AutoHtmlForm();
$form->setView($this)
->setMethod('put')
->setAction($this->uri('/scaffold/form/html'));
?>
<header class="page-header">
<h2 class="">Form Html Generator</h2>
</header>

<form action="<?=$this->uri('/scaffold/form/html')?>" method="post">
    <?=$form->restful();?>
    <div class="control-group">
        <label for="mainform" class="control-label">Main Form Class</label>
        <div class="controls">
            <input id="mainform" type="text" name="form" class="span5" value="Blog\Form\PostForm"/>
        </div>
    </div>

    <div class="control-group">
        <label for="subform" class="control-label">Subform Class (Split with conmma if have multi subforms)</label>
        <div class="controls">
            <input id="subform" type="text" name="subform" class="span9" value=""/>
        </div>
    </div>

    <div class="form-actions">
        <button class="btn btn-large">Create Form Html</button>
    </div>
</form>
