<? 
$title = 'Form Create Scaffold';
$this->headTitle($title, 'SET');
?>
<div class="container">

	<header class="page-header">
	<h2 class="">Form Create Scaffold </h2>
    </header>

    <?if($this->tables):?>
    <?foreach($this->tables as $key=>$table):?>
        <div>
        <a href="<?=$this->uri('/scaffold/form/' . $table)?>" class=""><?=$table?></a>
        </div>
    <?endforeach;?>
    <?endif;?>
</div>
