<? 
$title = 'Form Class Generator';
$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', $title);
?>
<header class="page-header">
<h2 class="">Select A Database Table:</h2>
</header>

<?if($this->tables):?>
<?foreach($this->tables as $key=>$table):?>
<ul class="nav nav-tabs nav-stacked">
    <li><a href="<?=$this->uri('/scaffold/form/' . $table)?>" class=""><?=$table?></a></li>
</ul>
<?endforeach;?>
<?endif;?>
