<div class="container"> 
<form class="form-horizontal">
        <fieldset>
          <div class="control-group">
            <label for="focusedInput" class="control-label">User Name</label>
            <div class="controls">
              <input type="text" value="User Name" id="focusedInput" class="input-xlarge">
            </div>
          </div>
          <div class="control-group">
            <label for="disabledInput" class="control-label">Password</label>
            <div class="controls">
              <input type="password" placeholder="" id="disabledInput" class="input-xlarge">
            </div>
          </div>
          <div class="form-actions">
            <button class="btn btn-primary" type="submit">Login</button>
          </div>
        </fieldset>
      </form>

</div>
