<?
$title = 'Admin Login';
$this->headTitle($title, 'SET');

if($this->form){
	$form = $this->form;
} else {
    $form = Eva\Api::_()->getForm('User\Form\AdminLoginForm');
}
$form->init(array(
	'action' => $this->uri('/admin/user/login/'),
	'method' => 'put',
	'values' => $this->user
));
?>

<div class="slate">
    <form class="form-horizontal" <?=$this->formAttr($form)?> >
        <?=$form->restful();?>
        <header class="page-header">
        <h3>Admin Login</h3>
        </header>
        <fieldset>
            <div class="control-group <?=$form->isError('userName') ? 'error' : '';?>">
                <?=$form->helper('userName', 'label', array('class' => 'control-label'))?>
                <div class="controls">
                    <?=$form->helper('userName', array('class' => 'input-xlarge'))?>
                    <div class="help-block"><?=$form->helper('userName', 'formElementErrors')?></div>
                </div>
            </div>
            <div class="control-group <?=$form->isError('password') ? 'error' : '';?>">
                <?=$form->helper('password', 'label', array('class' => 'control-label'))?>
                <div class="controls">
                    <?=$form->helper('password', array('class' => 'input-xlarge'))?>
                    <div class="help-block"><?=$form->helper('password', 'formElementErrors')?></div>
                </div>
            </div>
            <div class="form-actions">
                <button class="btn btn-primary" type="submit">Login</button>
                <a href="<?=$this->uri('/admin/user/reset/')?>">Forget Passsword</a>
            </div>
        </fieldset>
    </form>
</div>
