<?
$title = 'Admin Login';
$this->headTitle($title, 'SET');

if($this->form){
	$form = $this->form;
} else {
    $form = Eva\Api::_()->getForm('Core\Form\SuperAdminLoginForm');
}

if($this->hasModule('User')){
    $url = $this->uri('/admin/user/login/');
} else {
    $url = $this->uri('/admin/core/login/');
}
$form->init(array(
	'action' => $url,
	'method' => 'put',
	'values' => $this->user
));
?>
<input id="flash-messenger" type="hidden" value="<?=is_array($this->flashMessenger) ? implode(',', $this->flashMessenger) : ''?>" />
<div id="user-name-failed" class="alert alert-error hide">
    <a href="#" data-dismiss="alert" class="close">x</a>
    <h4 class="alert-heading">Input user not exist</h4>
</div>
<div id="password-failed" class="alert alert-error hide">
    <a href="#" data-dismiss="alert" class="close">x</a>
    <h4 class="alert-heading">Password not match</h4>
</div>


<div class="slate">
    <form class="form-horizontal" <?=$this->formAttr($form)?> >
        <?=$form->restful();?>
        <header class="page-header">
        <h3>Admin Login</h3>
        </header>
        <fieldset>
            <div class="control-group <?=$form->isError('userName') ? 'error' : '';?>">
                <?=$form->helper('userName', 'label', array('class' => 'control-label'))?>
                <div class="controls">
                    <?=$form->helper('userName', array('class' => 'input-xlarge'))?>
                    <div class="help-block"><?=$form->helper('userName', 'formElementErrors')?></div>
                </div>
            </div>
            <div class="control-group <?=$form->isError('password') ? 'error' : '';?>">
                <?=$form->helper('password', 'label', array('class' => 'control-label'))?>
                <div class="controls">
                    <?=$form->helper('password', array('class' => 'input-xlarge'))?>
                    <div class="help-block"><?=$form->helper('password', 'formElementErrors')?></div>
                </div>
            </div>
            <div class="form-actions">
                <input name="callback" type="hidden" value="<?=$callback?>" />
                <button class="btn btn-primary" type="submit">Login</button>
                <?if($this->hasModule('User')):?>
                <a href="<?=$this->uri('/admin/user/reset/')?>">Forget Passsword</a>
                <?endif?>
            </div>
        </fieldset>
    </form>
</div>
