<?
$title = $this->_('Category List');
$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', $title);
if($this->form){
	$form = $this->form;
} else {
    $form = Eva\Api::_()->getForm('\Group\Form\CategorySearchForm');
}
$form->init(array(
    'action' => $this->uri('/admin/group/category/'),
    'method' => 'get',
    'values' => $this->query
));

?>

<div class="row">
    <div class="span10 listing-buttons">
        <div class="btn-group pull-right">
            <a href="<?=$this->uri('/admin/group/category/create')?>" class="btn btn-info"><?=$this->_('Add New Category')?></a>
        </div>
        <form action="<?=$this->uri('/admin/group/multi/')?>" method="post" class="pull-left" data-multiform="post">
            <input type="hidden" name="id" class="multiform-container-main" value="" />
            <input type="hidden" name="order" class="multiform-container" value="" />
            <div class="btn-group">
                <span class="btn"><input type="checkbox" class="multiform-checker" /></span>
                <a href="#" class="btn multiform-submiter" data-multiform-action="<?=$this->uri('/admin/group/categorymulti/reorder')?>"><?=$this->_('Re-Order')?></a>
            </div>
        </form>
    </div>

    <div class="span10">
        <div class="slate">
            <div class="page-header">
                <div class="btn-group pull-right">
                    <span data-toggle="dropdown" class="btn dropdown-toggle">
                        <?=$this->_('Order')?><span class="caret"></span>
                    </span>
                    <ul class="dropdown-menu">
                        <li><a href="<?=$this->uri('/admin/group/category/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'idasc',),));?>" class=""><i class="icon-arrow-up"></i> <?=$this->_('Id')?></a></li>
                        <li><a href="<?=$this->uri('/admin/group/category/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'iddesc',),));?>" class=""><i class="icon-arrow-down"></i> <?=$this->_('Id')?></a></li>
                        <li><a href="<?=$this->uri('/admin/group/category/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'titleasc',),));?>" class=""><i class="icon-arrow-up"></i> <?=$this->_('Title')?></a></li>
                        <li><a href="<?=$this->uri('/admin/group/category/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'titledesc',),));?>" class=""><i class="icon-arrow-down"></i> <?=$this->_('Title')?></a></li>
                        <li><a href="<?=$this->uri('/admin/group/category/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'timeasc',),));?>" class=""><i class="icon-arrow-up"></i> <?=$this->_('Time')?></a></li>
                        <li><a href="<?=$this->uri('/admin/group/category/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'timedesc',),));?>" class=""><i class="icon-arrow-down"></i> <?=$this->_('Time')?></a></li>

                    </ul>
                </div>
                <h2><?=$title?></h2>
            </div>

            <table class="orders-table table">
                <thead>
                    <tr>
                        <th class="span1">
                        </th>
                        <th><?=$this->_('Category Name')?></th>
                        <th class="span1"><?=$this->_('Order')?></th>
                        <th class="actions"><?=$this->_('Actions')?></th>
                    </tr>
                </thead>
                <tbody>
                    <?if($this->items):?>
                    <?foreach($this->items as $key=>$item):?>
                    <tr class="">
                        <td>
                            <input name="id" type="checkbox" class="multiform-item-checkbox"  data-multiform="post" data-multiform-itemid="<?=$item['id'] ?>" value="<?=$item['id'] ?>" />
                        </td>	
                        <td>
                               <?if($item['level'] > 1) {
			                        echo str_repeat("&nbsp;&nbsp;&nbsp;",$item['level']).'|_';
			                    }?>
                            <a href="<?=$this->uri('/admin/group/category/' . $item['id'])?>" class="title"><?=$item['categoryName'] ?></a>
                            <p>
                            <span class="meta"><?=$item['urlName'] ?> <?=$item['createTime'];?></span>
                            </p>
                        </td>
                        <td>
                            <input name="order" tabindex="<?=$key+1 ?>" type="text" class="span1 multiform-item-input" size="2" maxlength="3"  data-multiform="post" data-multiform-itemid="<?=$item['id'] ?>" value="<?=$item['orderNumber'] ? $item['orderNumber'] : "0" ?>" />
                        </td>
                        <td class="actions">
                            <a href="<?=$this->uri('/admin/group/category/remove/' . $item['id'], 'c', array('c' => $this->uri('/admin/event/category', array('page' => $this->page)))); ?>" class="btn btn-small btn-danger"><?=$this->_('Delete')?></a>
                            <a href="<?=$this->uri('/admin/group/?category=' . $item['id'])?>" class="btn btn-small"><?=$this->_('Search Posts')?></a>
                            <a href="<?=$this->uri('/admin/group/category/' . $item['id'])?>" class="btn btn-small"><?=$this->_('Edit')?></a>
                        </td>
                    </tr>
                    <?endforeach;?>
                    <?endif;?>
                </tbody>
            </table>
        </div>
    </div><!--span10 end-->

    <div class="span10">
        <?if($this->paginator):?>
        <?=$this->paginator->setPath('/admin/group/category')->setBaseQuery($this->query);?>
        <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
        <?endif;?>
    </div>

</div>
