<?
$tag = isset($this->query['tag']) ? $this->query['tag'] : '';
$title = 'Just Fine - Story of AlloVince';
$title = $tag ? $title . ' About ' . $tag : $title;
if($this->paginator && $this->paginator->getCurrentPageNumber() > 1){
    $this->headTitle($title . ' | page ' . $this->paginator->getCurrentPageNumber(), 'SET');
} else {
    $this->headTitle($title, 'SET');
}
if($this->query['page'] == '1' && !$tag) {
    $this->headLink(array(
        'rel' => 'canonical',
        'href' => $this->uri('/')
    ));
}

if($this->query['page'] == '1' && $tag) {
    $this->headLink(array(
        'rel' => 'canonical',
        'href' => $this->uri('/thinking/' . $tag)
    ));
}
?>
<div class="page-content">
    <?if($this->items):?>
    <div class="vlist posts">
        <?foreach($this->items as $key => $item):?>
        <div class="item <?=$key == 0 ? 'first' : ''?>">
            <div class="item-inline item-title">
                <h3><a href="<?=$this->uri('/pages/' . $item['urlName'])?>"><?=$item['title']?></a></h3>
                <p class="info">发布时间： <time datetime="<?=$this->datetime()->isoTime($item['createTime'])?>" data-jstime="<?=$this->datetime()->jsTime($item['createTime'])?>" class="agotime"><?=$this->datetime($item['createTime'])?></time></p>
            </div>
        </div>
        <?endforeach;?>
    </div>
    <?if($this->paginator):?>
    <?=$this->paginator->setPath('/thinking/')->setBaseQuery(array());?>
    <?=$this->widget('Avnpc', 'widgets/paginator', $this->vars())?>
    <?endif;?>
    <?endif;?>
</div>
