<?
$item = $this->item;
$title = $item ? $item['title'] : 'Page Not Found';
$this->headTitle($title, 'SET');
?>
<div class="container">
    <div class="typo typocn">
    <?if($item):?>
	<header class="page-header">
		<h1><?=$this->escapeHtml($title); ?></h1>
	</header>
	<div class="typo"><?=$item['Text']['ContentHtml']?></div>
    <?else:?>
	<header class="page-header">
		<h1>Page Not Found</h1>
	</header>
    <?endif?>
    </div>
</div>
