<?
$item = $this->item;
$title = 'Find Friends';
$title = $this->_($title);
$this->headTitle($title, 'SET');

$inviteCode = $this->inviteCode;
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">

                        <div class="alert">Please invite only trusted friends who share the values of Epicurissimo. Kindly regard that there is a limitation of invitations you send, the numbers may vary according to multiple criterias such as seniority, and contribution.
                        </div>
                        <div class="page-main-header">
                            <h3><?=$this->_('Find Friends On Epicurissimo')?></h3>
                        </div>

                        <div class="well">
                            <a class="btn btn-large" style="padding-left:20px;text-align:left;" href="<?=$this->uri('/users/list/')?>"><i class="icon-search"></i> Find Friends On Epicurissimo</a>
                        </div>

                        <div class="page-main-header">
                            <h3><?=$this->_('Find Friends By')?></h3>
                        </div>

                        <div class="well">
                            <a class="btn btn-large" style="padding-left:20px;padding-right:120px;margin-right:50px;text-align:left;" href="<?=$this->uri('/contacts/import/', array('r' => $this->serverUrl() . '/account/addfriend/?service=google','service' => 'google'))?>"><i class="icon-social-google"></i> By Google Contacts</a>
                            <a class="btn btn-large" style="padding-left:20px;text-align:left;" href="<?=$this->uri('/contacts/import/', array('r' => $this->serverUrl() . '/account/addfriend/?service=msn','service' => 'msn'))?>"><i class="icon-social-windows"></i> By Hotmail/Live/MSN Contacts</a>
                        </div>

                        <div class="page-main-header">
                            <h3><?=$this->_('Invite Friends By Link')?></h3>
                        </div>

                        <div class="well form">
                            <div class="control-group">
                                <label class="control-label" for="invite-url">Invite Link</label>
                                <div class="controls">
                                    <input type="text" id="invite-url" class="span8" value="<?=$this->serverUrl() . '/register/?code=' . $inviteCode?>" readonly="readonly" >
                                </div>
                            </div>
                            

                        </div>

                        <div class="page-main-header">
                            <h3><?=$this->_('Invite Friends By Email')?></h3>
                        </div>

                        <div class="well">
                            <form action="<?=$this->uri('/contacts/invite/', array('r' => '/account/import/'))?>" method="post" class="form form-horizontal">
                            <div class="control-group">
                                <label class="control-label" for="invite-url">Friend Email Address</label>
                                <div class="controls">
                                    <input name="email[]" type="email" class="validate[required]" value="" />
                                </div>
                            </div>
                            <div class="controls">
                                <button class="btn"><?=$this->_('Send Invite')?></button>
                            </div>
                            </form>
                        </div>


                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/accountnav', $this->vars())?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->
