<?
$item = $this->item;
$title = 'Invite Friends';
$title = $this->_($title);
$this->headTitle($title, 'SET');

$contacts = $this->contacts;

$items = array();
if($contacts['outSiteContacts']){
    $items = $contacts['outSiteContacts'];
}
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="page-main-header">
                            <small class="pull-right">You could invite <span class="highlight"><?=$contacts['outSiteContactsCount']?></span> friends.</small>
                            <h3><?=$this->_('Invite Friends')?></h3>
                        </div>

                        <?if($items):?> 
                        <form action="<?=$this->uri('/contacts/invite/', array('r' => '/account/invite/?service=' . $this->service, 'service' => $this->service))?>" method="post" class="">
                            <div class="well typo">
                                <ul class="row">
                                    <?foreach($items as $item):?>
                                    <li class="span4">
                                    <label>
                                        <input name="email[]" type="checkbox" class="multiform-item-checkbox" value="<?=$item['email'] ?>" />
                                        <?=$item['email']?>
                                        <?if(isset($item['name']) && $item['name']):?>
                                        (<?=$item['name']?>)
                                        <?endif?>
                                    </label>
                                    </li>
                                    <?endforeach;?>
                                </ul>
                                <input type="submit" class="btn btn-large btn-block" value="Invite" />
                            </div>
                        </form>
                        <?endif;?>


                        <div class="well typo">
                            <p>Or you could try to:</p>
                            <a class="btn btn-large btn-block" href="<?=$this->uri('/account/import/')?>">Find friends by other site.</a>
                        </div>


                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/accountnav', $this->vars())?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->
