<?
$item = $this->item;
$title = 'Notification Setting';
$title = $this->_($title);
$this->headTitle($title, 'SET');

$form = new Notification\Form\UsersettingForm();
$form
->useSubformGroup()
->setMethod('put')
->setView($this)
->setAction($this->uri('/account/notification/'))
->prepare();

?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="page-main-header">
                            <h3><?=$this->_($title);?></h3>
                        </div>
                        
                      <form id="profile-edit-form" <?=$this->formAttr($form)?> class="form">
                            <?=$form->restful();?>
                            <input type="hidden" name="callback" value="<?=$this->uri('/account/notification/')?>" />
                                
                                <?foreach($settings as $key=>$setting):?>
                                <div class="page-header">
                                    <h4><?=$this->_($setting['Notification']['title'])?></h4>
                                </div> 
                                <fieldset class="form-horizontal">
                                    <div class="control-group <?=$form->isError('notification_id') ? 'error' : '';?> hide">
                                        <?=$form->helper('notification_id', 'label', array('class' => 'control-label'))?>
                                        <div class="controls">
                                            <?=$form->helper('notification_id', array('name' => "notification_id[$key]",'value' => $setting['notification_id']))?>        
                                            <div class="help-block"><?=$form->helper('notification_id', 'formElementErrors')?></div>
                                        </div>
                                    </div>
                                    
                                    <div class="control-group <?=$form->isError('disableNotice') ? 'error' : '';?> <?=$setting['Notification']['allowDisableNotice'] && $setting['Notification']['sendNotice'] ? '' : 'hide'?>">
                                        <?=$form->helper('disableNotice', 'label', array('class' => 'control-label'))?>
                                        <div class="controls">
                                            <?=$form->helper('disableNotice', 'formRadio', array('name' => "disableNotice[$key]",'value' => $setting['disableNotice']))?>        
                                            <div class="help-block"><?=$form->helper('disableNotice', 'formElementErrors')?></div>
                                        </div>
                                    </div>
                                    
                                    <div class="control-group <?=$form->isError('disableEmail') ? 'error' : '';?> <?=$setting['Notification']['allowDisableEmail'] && $setting['Notification']['sendEmail'] ? '' : 'hide'?>">
                                        <?=$form->helper('disableEmail', 'label', array('class' => 'control-label'))?>
                                        <div class="controls">
                                            <?=$form->helper('disableEmail', 'formRadio', array('name' => "disableEmail[$key]",'value' => $setting['disableEmail']))?>        
                                            <div class="help-block"><?=$form->helper('disableEmail', 'formElementErrors')?></div>
                                        </div>
                                    </div>  
                                </fieldset>
                                <?endforeach;?>
                                <div class="form-actions">
                                    <button id="save-publish" class="btn btn-success btn-large"><?=$this->_('Save')?></button>
                                </div>
                        </form> 


                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/accountnav', $this->vars())?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->
