<?
$item = $this->item;
$title = 'Privacy Setting';
$title = $this->_($title);
$this->headTitle($title, 'SET');
$form = $this->form;
$form->setView($this)
->setMethod('post')
->setAction($this->uri('/account/privacy/'))
->bind($item)
->prepare();

$roles = $this->roles;
$permissions = $this->permissions;
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="page-main-header">
                            <h3><?=$this->_('Privacy Setting')?></h3>
                        </div>

                        <form <?=$this->formAttr($form)?> class="form form-horizontal">
                            <?=$form->restful();?>
                            <?foreach($permissions as $key => $permission):?>
                            <div class="control-group <?=$form->isError($key) ? 'error' : '';?>">
                                <?=$form->helper($key, 'label', array('class' => 'control-label'))?>
                                <div class="controls">
                                    <?=$form->helper($key, 'formSelect', array('name' => "permission[$key]", 'class' => ''))?>        
                                    <div class="help-block"><?=$form->helper($key, 'formElementErrors')?></div>
                                </div>
                            </div>
                            <?endforeach?>
                            <div class="form-actions">
                                <button class="btn">Save</button>
                            </div>
                        </form>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/accountnav', $this->vars())?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->
