<?
$item = $this->item;
$title = 'Edit Profile';
$title = $this->_($title);
$this->headTitle($title, 'SET');

if(!$this->form){
    $form = new Epic\Form\AccountEditForm();
    $form->useSubFormGroup();
}

$form->setMethod($item['id'] ? 'put' : 'post');
$form->setView($this)
    ->setAction($this->uri('/account/profile/'))
     ->bind($item)
     ->prepare();

$tags = isset($item['Tags']) ? $item['Tags'] : array();
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="page-main-header">
                            <h3><?=$this->_('Edit Profile')?></h3>
                        </div>
                        <form id="profile-edit-form" <?=$this->formAttr($form)?> class="form">
                            <?=$form->restful();?>
                            <?=$form->helper('id');?>
                            <input type="hidden" name="callback" value="<?=$this->uri('/account/profile/')?>" />

                            <fieldset class="form-horizontal">



                                <div class="control-group">
                                    <?=$form->helper('avatar_id', 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <div id="avatar-uploader" class="row <?=isset($item['Avatar']) && $item['Avatar'] ? 'hide' : ''?>">
                                            <div class="span4">
                                                <?=$form->helper('avatar_id');?>
                                                <?=$this->widget('File', 'file/upload')?>
                                            </div>
                                        </div>
                                        <?if(isset($item['Avatar']) && $item['Avatar']):?>
                                        <img id="avatar-view" src="<?=$this->thumb($item['Avatar']['Thumb'], array('h_175', 'w_175', 'c_fill'))?>" alt="" class="img-polaroid" data-default="<?=$this->assets('/module/epic/img/default_avatar.png')?>" />
                                        <br /><a href="#" id="show-avatar-uploader"><?=$this->_('Change Avatar');?></a> <?=$this->_('or');?> <a id="delete-avatar" href="#" ><?=$this->_('Delete');?></a>
                                        <?else:?>
                                        <img  id="avatar-view" src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="img-polaroid" />
                                        <?endif?>
                                    </div>
                                </div>

                                <div class="page-header border-header">
                                    <h4><?=$this->_('Basic Information')?></h4>
                                </div>

                                <div class="control-group <?=$form->isError('firstName') ? 'error' : '';?>">
                                    <?=$form->helper('firstName', 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper('firstName', array('class' => ''))?>        
                                        <div class="help-block"><?=$form->helper('firstName', 'formElementErrors')?></div>
                                    </div>
                                </div>
                                <div class="control-group <?=$form->isError('lastName') ? 'error' : '';?>">
                                    <?=$form->helper('lastName', 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper('lastName', array('class' => ''))?>        
                                        <div class="help-block"><?=$form->helper('lastName', 'formElementErrors')?></div>
                                    </div>
                                </div>
                                <div class="control-group <?=$form->isError('gender') ? 'error' : '';?>">
                                    <?=$form->helper('gender', 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper('gender', 'formSelect', array('class' => ''))?>        
                                        <div class="help-block"><?=$form->helper('gender', 'formElementErrors')?></div>
                                    </div>
                                </div>

                                <div class="control-group <?=$form->isError(array('Profile', 'birthday')) ? 'error' : '';?>">
                                    <?=$form->helper(array('Profile', 'birthday'), 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper(array('Profile', 'birthday'), array('class' => 'datepicker', 'data-date-format' => 'yyyy-mm-dd'))?>        
                                        <div class="help-block"><?=$form->helper(array('Profile', 'birthday'), 'formElementErrors')?></div>
                                    </div>
                                </div>


                                <div class="control-group <?=$form->isError(array('Profile', 'country')) ? 'error' : '';?>">
                                    <?=$form->helper(array('Profile', 'country'), 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper(array('Profile', 'country'), 'formSelect', array('class' => 'select2 input-large'))?>        
                                        <div class="help-block"><?=$form->helper(array('Profile', 'country'), 'formElementErrors')?></div>
                                    </div>
                                </div>

                                <div class="control-group <?=$form->isError(array('Profile', 'city')) ? 'error' : '';?>">
                                    <?=$form->helper(array('Profile', 'city'), 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper(array('Profile', 'city'), 'formSelect', array('class' => 'select2 input-large'))?>        
                                        <div class="help-block"><?=$form->helper(array('Profile', 'city'), 'formElementErrors')?></div>
                                    </div>
                                </div>

                                <div class="control-group <?=$form->isError(array('Profile', 'phoneMobile')) ? 'error' : '';?>">
                                    <?=$form->helper(array('Profile', 'phoneMobile'), 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper(array('Profile', 'phoneMobile'), array('class' => ''))?>        
                                        <div class="help-block"><?=$form->helper(array('Profile', 'phoneMobile'), 'formElementErrors')?></div>
                                    </div>
                                </div>

                                <div class="page-header border-header">
                                    <h4><?=$this->_('Customized Information')?></h4>
                                </div>

                                <div class="control-group <?=$form->isError('role') ? 'error' : '';?>">
                                    <?=$form->helper('role', 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper('role', 'formSelect', array('class' => ''))?>        
                                        <div class="help-block"><?=$form->helper('role', 'formElementErrors')?></div>
                                    </div>
                                </div>


                                <div class="control-group <?=$form->isError('language') ? 'error' : '';?>">
                                    <?=$form->helper('language', 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper('language', 'formSelect', array('class' => 'select2 input-large'))?>        
                                        <div class="help-block"><?=$form->helper('language', 'formElementErrors')?></div>
                                    </div>
                                </div>


                                <div class="control-group <?=$form->isError(array('Profile', 'interest')) ? 'error' : '';?>">
                                    <?=$form->helper(array('Profile', 'interest'), 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper(array('Profile', 'interest'), 'formSelect', array('class' => 'input-large select2'))?>        
                                        <div class="help-block"><?=$form->helper(array('Profile', 'interest'), 'formElementErrors')?></div>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label">Tags</label>
                                    <div class="controls">
                                        <?$tagForm = $form->get('Tags')->get('0');?>
                                        <?=$tagForm->helper('tagName', array('id' => 'tagging', 'class' => 'input-large', 'value' => $this->tagging($tags)->toNameString()))?> 
                                    </div>
                                </div>

                                <div class="page-header border-header">
                                    <h4><?=$this->_('Other Information')?></h4>
                                </div>


                                <div class="control-group <?=$form->isError(array('Profile', 'industry')) ? 'error' : '';?>">
                                    <?=$form->helper(array('Profile', 'industry'), 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper(array('Profile', 'industry'), array('id' => 'positioning', 'class' => 'input-large'))?>  
                                        <div class="help-block"><?=$form->helper(array('Profile', 'industry'), 'formElementErrors')?></div>
                                        <p>If your position is not in the list, Please type it by your own.</p>
                                    </div>
                                </div>


                                <div class="control-group <?=$form->isError(array('Profile', 'site')) ? 'error' : '';?>">
                                    <?=$form->helper(array('Profile', 'site'), 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper(array('Profile', 'site'), array('class' => ''))?>        
                                        <div class="help-block"><?=$form->helper(array('Profile', 'site'), 'formElementErrors')?></div>
                                        <div class="help-block">Full url start by http://</div>
                                    </div>
                                </div>


                                <div class="control-group <?=$form->isError(array('Profile', 'address')) ? 'error' : '';?>">
                                    <?=$form->helper(array('Profile', 'address'), 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper(array('Profile', 'address'), array('class' => ''))?>        
                                        <div class="help-block"><?=$form->helper(array('Profile', 'address'), 'formElementErrors')?></div>
                                    </div>
                                </div>

                                <!--
                                <div class="control-group <?=$form->isError(array('Profile', 'province')) ? 'error' : '';?>">
                                    <?=$form->helper(array('Profile', 'province'), 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper(array('Profile', 'province'), array('class' => ''))?>        
                                        <div class="help-block"><?=$form->helper(array('Profile', 'province'), 'formElementErrors')?></div>
                                    </div>
                                </div>
                                -->
                                <!--
                                <div class="control-group <?=$form->isError(array('Profile', 'zipcode')) ? 'error' : '';?>">
                                    <?=$form->helper(array('Profile', 'zipcode'), 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper(array('Profile', 'zipcode'), array('class' => ''))?>        
                                        <div class="help-block"><?=$form->helper(array('Profile', 'zipcode'), 'formElementErrors')?></div>
                                    </div>
                                </div>
                                -->


                                <div class="control-group <?=$form->isError(array('Profile', 'bio')) ? 'error' : '';?>">
                                    <?=$form->helper(array('Profile', 'bio'), 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper(array('Profile', 'bio'), 'formTextarea', array('class' => ''))?>        
                                        <div class="help-block"><?=$form->helper(array('Profile', 'bio'), 'formElementErrors')?></div>
                                    </div>
                                </div>
                                <!--
                                <div class="control-group <?=$form->isError(array('Profile', 'localIm')) ? 'error' : '';?>">
                                    <?=$form->helper(array('Profile', 'localIm'), 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper(array('Profile', 'localIm'), array('class' => ''))?>        
                                        <div class="help-block"><?=$form->helper(array('Profile', 'localIm'), 'formElementErrors')?></div>
                                    </div>
                                </div>
                                -->
                                <div class="form-actions">
                                    <button id="save-publish" class="btn btn-success btn-large"><?=$this->_('Save')?></button>
                                </div>
                            </fieldset>
                        </form>
                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/accountnav', $this->vars())?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->

<script>
eva.ready(function(){
        eva.loadcss(eva.s('/lib/js/jquery/jquery.select2/select2.css'));
        eva.loader(eva.s('/lib/js/jquery/jquery.select2/select2.js'), function(){
                $('#tagging').select2({
                        tags : <?=$this->json(array('Gastronome', 'Oenophile', 'Foodie', 'Bon Vivant', 'Cocktail Lovers', 'Wine Lovers', 'Gourmet', 'Glamorous', 'Imbibers', 'Enlightened Tipplers'))?>
                });
                $('#positioning').select2({
                        tags : <?=$this->json(array('Business Owner', 'Partner', 'Managing Director', 'Executives', 'Managers'))?>
                });
        });

        var form = $("#profile-edit-form");
        var uploader = $('#singlefileupload');
        uploader.bind('fileuploaddone', function (e, data) {
                var file = data.result[0];
                form.find('input[name="avatar_id"]').val(file.id);
                $("#avatar-view").hide();
        });

        $("#show-avatar-uploader").click(function(){
                $("#avatar-uploader").show();
                return false;
        });

        $("#delete-avatar").click(function(){
                form.find('input[name="avatar_id"]').val('0');
                $("#avatar-view").attr("src", $("#avatar-view").attr("data-default"));
                $("#avatar-uploader").show();
                return false;
        });
});
</script>
