<?
$category = $this->category;
$title = $category['id'] ? 'Edit Category' : 'Create Category';
$title = $this->_($title);
$method = $category['id'] ? 'put' : 'post';
$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', $title);

if($this->form){
	$form = $this->form;
} else {
    $form = Eva\Api::_()->getForm('\Blog\Form\CategoryForm');
}
$form->init(array(
    'action' => $this->uri('/admin/blog/category/'),
    'method' => $method,
    'values' => $this->category
));
?>
<div class="row">
    <form <?=$this->formAttr($form)?>>
        <?=$form->restful();?>
        <?=$form->helper('id');?>
        <div class="span10">
            <div class="slate">
                <div class="page-header">
                    <?if($category):?>
                    <div class="btn-group pull-right">
                        <a href="<?=$this->uri('/admin/blog/category/create')?>" class="btn"><?=$this->_('Create Category')?></a>
                        <a href="<?=$this->uri('/admin/blog/?category=' . $category['id'])?>" class="btn"><?=$this->_('View Category Posts')?></a>
                        <a href="<?=$this->uri('/admin/blog/category/remove/' . $category['id'], 'c', array('c' => $this->uri('/admin/category/' . $category['id']))); ?>" class="btn"><?=$this->_('Delete')?></a>
                    </div>
                    <?endif?>
                    <h2><?=$title?></h2>
                </div>
                <fieldset class="">
                    <div class="control-group <?=$form->isError('categoryName') ? 'error' : '';?>">
                        <?=$form->helper('categoryName', 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper('categoryName', array('class' => 'span5'))?>        
                            <div class="help-block"><?=$form->helper('categoryName', 'formElementErrors')?></div>
                        </div>
                    </div>

                    <div class="control-group <?=$form->isError('urlName') ? 'error' : '';?>">
                        <?=$form->helper('urlName', 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <div class="input-prepend input-append">
                                <span class="add-on"><?=$this->serverUrl() . '/category/'?></span><?=$form->helper('urlName', array('class' => 'span6'))?><span class="add-on">/</span>
                            </div>
                            <div class="help-block"><?=$this->_('No input will create a random url')?></div>
                            <div class="help-block"><?=$form->helper('urlName', 'formElementErrors')?></div>
                        </div>
                    </div>

                    <div class="control-group <?=$form->isError('description') ? 'error' : '';?>">
                        <?=$form->helper('description', 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper('description', 'formTextarea', array('class' => 'span9'))?>        
                            <div class="help-block"><?=$form->helper('description', 'formElementErrors')?></div>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div><!--span10 end-->

        <div class="span10 listing-buttons">
            <button class="btn btn-info btn-large"><?=$this->_('Save')?></button>
        </div>
    </form>
</div>
