<?
$title = 'Category List';
$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', 'Category List');
if($this->form){
	$form = $this->form;
} else {
    $form = Eva\Api::_()->getForm('\Blog\Form\CategorySearchForm');
}
$form->init(array(
    'action' => $this->uri('/admin/blog/category/'),
    'method' => 'get',
    'values' => $this->query
));

?>

<div class="row">
    <div class="span10 listing-buttons">
        <div class="btn-group pull-right">
            <a href="<?=$this->uri('/admin/blog/category/create')?>" class="btn btn-info">Add New Category</a>
        </div>
        <form action="<?=$this->uri('/admin/blog/multi/')?>" method="post" class="pull-left" data-multiform="post">
            <input type="hidden" name="id" class="multiform-container-main" value="" />
            <input type="hidden" name="order" class="multiform-container" value="" />
            <div class="btn-group">
                <span class="btn"><input type="checkbox" class="multiform-checker" /></span>
                <a href="#" class="btn multiform-submiter" data-multiform-action="<?=$this->uri('/admin/blog/categorymulti/reorder')?>">Re-Order</a>
            </div>
        </form>
    </div>

    <div class="span10">
        <div class="slate">
            <div class="page-header">
                <div class="btn-group pull-right">
                    <span data-toggle="dropdown" class="btn dropdown-toggle">
                        Order
                        <span class="caret"></span>
                    </span>
                    <ul class="dropdown-menu">
                        <li><a href="<?=$this->uri('/admin/blog/category/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'idasc',),));?>" class=""><i class="icon-arrow-up"></i> Id</a></li>
                        <li><a href="<?=$this->uri('/admin/blog/category/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'iddesc',),));?>" class=""><i class="icon-arrow-down"></i> Id</a></li>
                        <li><a href="<?=$this->uri('/admin/blog/category/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'titleasc',),));?>" class=""><i class="icon-arrow-up"></i> Title</a></li>
                        <li><a href="<?=$this->uri('/admin/blog/category/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'titledesc',),));?>" class=""><i class="icon-arrow-down"></i> Title</a></li>
                        <li><a href="<?=$this->uri('/admin/blog/category/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'timeasc',),));?>" class=""><i class="icon-arrow-up"></i> Time</a></li>
                        <li><a href="<?=$this->uri('/admin/blog/category/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'timedesc',),));?>" class=""><i class="icon-arrow-down"></i> Time</a></li>
                    </ul>
                </div>
                <h2><?=$title?></h2>
            </div>

            <table class="orders-table table">
                <thead>
                    <tr>
                        <th class="span1">
                        </th>
                        <th>Category Name</th>
                        <th class="span1">Order</th>
                        <th class="actions">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?if($this->categories):?>
                    <?foreach($this->categories as $key=>$category):?>
                    <tr class="">
                        <td>
                            <input name="id" type="checkbox" class="multiform-item-checkbox"  data-multiform="post" data-multiform-itemid="<?=$category['id'] ?>" value="<?=$category['id'] ?>" />
                        </td>	
                        <td>
                               <?if($category['level'] > 1) {
			                        echo str_repeat("&nbsp;&nbsp;&nbsp;",$category['level']).'|_';
			                    }?>
                            <a href="<?=$this->uri('/admin/blog/category/' . $category['id'])?>" class="title"><?=$category['categoryName'] ?></a>
                            <p>
                            <span class="meta"><?=$category['urlName'] ?> <?=$category['createTime'];?></span>
                            </p>
                        </td>
                        <td>
                            <input name="order" tabindex="<?=$key+1 ?>" type="text" class="span1 multiform-item-input" size="2" maxlength="3"  data-multiform="post" data-multiform-itemid="<?=$category['id'] ?>" value="<?=$category['orderNumber'] ? $category['orderNumber'] : "0" ?>" />
                        </td>
                        <td class="actions">
                            <a href="<?=$this->uri('/admin/blog/category/remove/' . $category['id'], 'c', array('c' => $this->uri('/admin/blog/category', array('page' => $this->page)))); ?>" class="btn btn-small btn-danger">Delete</a>
                            <a href="<?=$this->uri('/admin/blog/category/' . $category['id'])?>" class="btn btn-small">Edit</a>
                        </td>
                    </tr>
                    <?endforeach;?>
                    <?endif;?>
                </tbody>
            </table>
        </div>
    </div><!--span10 end-->

    <div class="span10">
        <?if($this->paginator):?>
        <?=$this->paginator->setPath('/admin/blog/category')->setBaseQuery($this->query);?>
        <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
        <?endif;?>
    </div>

</div>
