<?
$category = $this->category;
$title = $this->_('Delete Category');
$this->headTitle($title, 'SET');
$form = Eva\Api::_()->getForm('\Blog\Form\CategoryDeleteForm');

$form->init(array(
	'action' => $this->uri('/admin/blog/category'),
	'method' => 'delete',
	'values' => $this->category
));
?>

<?if($category):?>
<div class="alert alert-block">
   <h2 class="alert-heading"><?=$title?></h2>
   <p><?=$this->_(array('Category %name% will be deleted, are you sure?', $category['categoryName']))?></p>
   <p>
		<form class="form-horizontal" <?=$this->formAttr($form)?>>
			<?=$form->restful();?>
			<?=$this->formInput($form->get('id'));?>
            <button class="btn btn-danger" type="submit"><?=$this->_('Delete')?></button>
            <input name="callback" type="hidden" value="<?=$this->callback?>" />
            <a class="btn" href="<?=$this->callback?>"><?=$this->_('Go Back')?></a>
   		</form>
	</p>
</div>
<?else:?>
<div class="alert alert-success container">
    <h2 class="alert-heading"><?=$this->_('Category have been deleted')?></h2>
</div>
<?endif?>
