<?
$item = $this->item;
$title = 'My Albums';
$title = $this->_($title);
$this->headTitle($title, 'SET');
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span6">
                                <div class="page-main-header">
                                    <a href="<?=$this->uri('/albums/create/')?>" class="btn btn-small btn-orange pull-right">Create New</a>
                                    <h3><?=$this->_($title)?></h3>
                                </div>
                                <div class="album-list">
                                    <?if(count($items) > 0 )?>
                                    <?for($i=0;$i< ceil(count($items) / 3);$i++):?>
                                    <div class="row-fluid stack-row">
                                        <?for($j= ($i * 3);$j< (3 * ($i+1));$j++):?>
                                        <?if(isset($items[$j])){$item = $items[$j];}else{continue;}?>
                                        <div class="span4">
                                            <div class="stack">	
                                                <a href="<?=$this->uri('/user/' . $item['user_name'] . '/albums/' . $item['urlName']);?>">
                                                    <?if(isset($item['Cover']) && $item['Cover']):?>
                                                        <img src="<?=$this->thumb($item['Cover']['Thumb'], array('c_fill', 'w_180', 'h_180'))?>" width="180" />
                                                    <?else:?>
                                                        <img src="<?=$this->assets('/module/epic/img/album-default.png')?>" width="180" alt="" />
                                                    <?endif?>
                                                </a>
                                            </div>
                                            <p class="caption">
                                                <a href="<?=$this->uri('/user/' . $item['user_name'] . '/albums/' . $item['urlName']);?>" class="caption-title"><?=$item['title']?></a>
                                                <span class="lowlight">(<?=$item['ImageCount']['imageCount']?> Photos Total)</span>
                                            </p>
                                            <p class="caption">
                                                <a href="<?=$this->uri('/albums/edit/' . $item['id'])?>"><i class="icon-edit"></i> Edit</a> 
                                                <a href="<?=$this->uri('/albums/remove/' . $item['id'])?>"><i class="icon-remove"></i> Delete</a>
                                            </p>
                                        </div>
                                        <?endfor;?>
                                    </div>
                                    <?endfor;?>
                                </div><!--album-list end-->
                                <?if($this->paginator):?>
                                <?=$this->paginator->setPath('/my/album/')->setBaseQuery($this->query);?>
                                <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                                <?endif;?>

                            </div><!--page main left end-->
                            <div class="span3">
                                <div class="page-extra">
                                    <?=$this->widget('Epic', 'widgets/userextra', $this->vars())?>
                                </div>
                            </div><!--page main right end-->
                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside')?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->

