<?
$item = $this->item;
$title = 'Blog';
$title = $this->_($title);
$this->headTitle($title, 'SET');
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span6">
                                <div class="page-main-header">
                                    <a href="<?=$this->uri('/blogs/create/')?>" class="btn btn-small btn-orange pull-right"><i class="icon-pencil"></i> Write New</a>
                                    <h3><?=$this->_($title)?></h3>
                                </div>
                                <div class="blog-list vlist">
                                    <?foreach($items as $item):?>
                                    <div class="item">
                                        <div class="item-title"><h2><a href="<?=$this->uri('/user/' . $this->user['userName'] . '/blog/' . $item['urlName'])?>"><?=$item['title']?></a></h2></div>
                                        <div class="item-meta">
                                            <p class="pull-right hide"><i class="icon-comment"></i> Comments (<span class="highlight"><?=$item['commentCount']?></span>)</p>
                                            <p class="pull-right"><a href="<?=$this->uri('/blogs/edit/' . $item['id'])?>"><i class="icon-edit"></i> Edit</a> <a href="<?=$this->uri('/blogs/remove/' . $item['id'])?>"><i class="icon-remove"></i> Delete</a></p>
                                            <p class="pull-left">
                                            <time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['createTime'])?>" datetime="<?=$this->datetime()->isoTime($item['createTime'])?>"><?=$this->datetime($item['createTime'])?></time>
                                            </p>
                                        </div>
                                        <div class="item-inline item-text">
                                                <?if($item['PostCover']):?>
                                                <div class="item-image pull-left">
                                                    <p><a href="<?=$item['PostCover'][0]['Thumb']?>"><img src="<?=$this->thumb($item['PostCover'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                                                </div>
                                                <?endif?>

                                                <?=$this->subText($item['Text']['ContentHtml'], 250)?>
                                        </div>
                                    </div>
                                    <?endforeach?>
                                </div><!--activity-list end-->
                                <?if($this->paginator):?>
                                <?=$this->paginator->setPath('/my/blog/')->setBaseQuery($this->query);?>
                                <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                                <?endif;?>

                            </div><!--page main left end-->
                            <div class="span3">
                                <div class="page-extra">
                                    <?=$this->widget('Epic', 'widgets/userextra', $this->vars())?>
                                </div>
                            </div><!--page main right end-->
                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside', $this->vars())?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->

