<?
$this->headTitle('Switch City', 'SET');	
$item = $this->item;
$title = 'Select Your Current City';
$title = $this->_($title);
$this->headTitle($title, 'SET');

$cities = Epic\Form\ProfileForm::$city;
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">
            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span9">
                                <div class="page-main-header">
                                    <a href="<?=$this->uri('/events/')?>" class="btn btn-small btn-orange pull-right">Back to Event</a>
                                    <h3><?=$this->_($title)?></h3>
                                </div>

                                <div class="typo typocn switch-city">

                                    <?foreach($cities as $key => $area):?>
                                    <div class="page-header border-header">
                                        <h2><?=$area['label']?></h2>
                                    </div>
                                    <ul class="row">
                                        <?foreach($area['options'] as $city):?>
                                        <li class="span2"><a href="#"><?=$city['label']?></a></li>
                                        <?endforeach?>
                                    </ul>
                                    <?endforeach?>

                                </div>
                            </div><!--page main left end-->

                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside')?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->
