<?
$item = $this->item;
$title = 'My Events';
$title = $this->_($title);
$this->headTitle($title, 'SET');

$unjoinForm = new Event\Form\EventUserForm();
$unjoinForm
->setView($this)
->useSubFormGroup()
->setMethod('delete')
->setAction($this->uri('/event/join/'))
->prepare();
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span6">
                                <div class="page-main-header">
                                    <span class="pull-right">
                                        <a href="<?=$this->uri('/events/list/')?>" class="btn btn-small btn-gray"><i class="icon-search"></i> Find an Event</a>
                                        <a href="<?=$this->uri('/events/create/')?>" class="btn btn-small btn-orange"><i class="icon-plus"></i> Schedule an Event</a>
                                    </span>
                                    <h3><?=$this->_($title)?></h3>
                                </div>
                                <ul class="nav nav-pills">
                                    <!--<li data-highlight-url="^/my/event/$"><a href="<?=$this->uri('/my/event/')?>"><?=$this->_('Ongoing')?></a></li>-->
                                    <li data-highlight-url="^/my/event/upcoming/?$"><a href="<?=$this->uri('/my/event/upcoming/')?>"><?=$this->_('Upcoming')?></a></li>
                                    <li data-highlight-url="^/my/event/finished/?$"><a href="<?=$this->uri('/my/event/finished/')?>"><?=$this->_('Finished')?></a></li>
                                </ul>

                                <div class="blog-list vlist">
                                    <?foreach($items as $item):?>
                                    <?$event = $item;?> 
                                    <div class="item">
                                        <div class="item-title"><h2><a href="<?=$this->uri('/event/' . $event['urlName'])?>"><?=$event['title']?></a></h2></div>
                                        <div class="item-meta">
                                            <?if($item['user_id'] == $user['id']):?>
                                            <!--
                                            <p class="pull-right hide"><i class="icon-comment"></i> <?=$this->_('Members')?> (<span class="highlight">0</span>)</p>
                                            -->
                                            <p class="pull-right"><a href="<?=$this->uri('/events/edit/' . $event['id'])?>"><i class="icon-edit"></i> Edit</a> <a href="<?=$this->uri('/events/remove/' . $event['id'])?>"><i class="icon-remove"></i> Delete</a></p>
                                            <?else:?>
                                            <p class="pull-right">
                                            <form <?=$this->formAttr($unjoinForm)?> class="pull-right">
                                                <?=$unjoinForm->restful();?>
                                                <?=$unjoinForm->helper('event_id', 'formHidden', array('class' => '', 'value' => $event['id']))?>
                                                <?=$unjoinForm->helper('user_id', array('class' => ''))?>
                                                <?=$this->callback()?>
                                                <button class="btn btn-small item-action-main"><?=$this->_('Quit')?></button>
                                            </form>
                                            </p>
                                            <?endif;?>
                                            <p class="pull-left">
                                            <time class="agotime" data-jstime="<?=$this->datetime()->jsTime($event['requestTime'])?>" datetime="<?=$this->datetime()->isoTime($event['requestTime'])?>"><?=$this->datetime($event['requestTime'])?></time>
                                            </p>
                                        </div>
                                        <div class="item-inline item-text">
                                                <?if($event['File']):?>
                                                <div class="item-image pull-left">
                                                    <p><a href="<?=$event['File'][0]['Thumb']?>"><img src="<?=$this->thumb($event['File'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                                                </div>
                                                <?endif?>

                                                <?=$this->subText($event['Text']['content'], 250)?>
                                        </div>
                                    </div>
                                    <?endforeach?>
                                </div><!--activity-list end-->
                                <?if($this->paginator):?>
                                <?=$this->paginator->setPath('/my/event/')->setBaseQuery($this->query);?>
                                <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                                <?endif;?>

                            </div><!--page main left end-->
                            <div class="span3">
                                <div class="page-extra">
                                    <?=$this->widget('Epic', 'widgets/userextra', $this->vars())?>
                                </div>
                            </div><!--page main right end-->
                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside', $this->vars())?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->

