<?
$item = $this->item;
$title = 'My Friends';
$title = $this->_($title);
$this->headTitle($title, 'SET');

$form = new Activity\Form\FollowForm();
$form
->setView($this)
->useSubFormGroup()
->setMethod('post')
->setAction($this->uri('/activity/follow/'))
->prepare();

$unfollowForm = clone $form;
$unfollowForm->setMethod('delete');
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span6">
                                <div class="page-main-header">
                                    <a href="<?=$this->uri('/account/import/')?>" class="btn btn-small btn-orange pull-right"><i class="icon-search"></i> Find Friends</a>
                                    <h3><?=$this->_($title)?></h3>
                                </div>
                            <div class="user-list vlist">
                                <?foreach($items as $item):
                                $item = $item['User'];
                                ?>
                                <div class="item">
                                    <div class="item-absolute item-userface">
                                        <a href="<?=$this->uri('/user/' . $item['userName'])?>" title="" class="userface">
                                             <img src="<?=$item['Avatar'] ? $this->thumb($item['Avatar']['Thumb'], array('h_60', 'w_60', 'c_fill')) :  $this->assets('/module/epic/img/default_avatar.png')?>" alt=""  width="60" height="60" class="img-rounded"/>
                                        </a>
                                        <a href="<?=$this->uri('/messages/send/' . $item['userName'])?>" title="" class="item-quick-action btn btn-small btn-tiny-white">Message</a>
                                    </div>
                                    <div class="item-inline item-text">
                                        <div class="item-title">
                                            <h2><a href="<?=$this->uri('/user/' . $item['userName'])?>" class="item-user"><?=$item['userName']?></a></h2>
                                            <?if($item['Profile']['city']):?>
                                            <?=$item['Profile']['city']?>
                                            <?endif?>
                                            <?if($item['Profile']['city']):?>
                                            <?=$item['Profile']['province']?>
                                            <?endif?>
                                            <?if($item['Profile']['country']):?>
                                            <?=$this->locale('territory', $item['Profile']['country'])?>
                                            <?endif?>
                                        </div>
                                        <div class="item-meta">
                                            <table class="table-condensed">
                                                <tbody>
                                                    <tr>
                                                        <td>Title: 
                                                            <?if($item['gender'] =='male'):?>
                                                            Mr.
                                                            <?elseif($item['gender'] == 'femail'):?>
                                                            Miss.
                                                            <?endif?>

                                                            <?if($item['firstName'] && $item['lastName']):?>
                                                            <?=$item['lastName']?> <?=$item['firstName']?>
                                                            <?endif?>
                                                        </td>
                                                        <td>Birthday : 
                                                            <?if($item['Profile']['birthday'] && $item['Profile']['birthday'] != '0000-00-00'):?>
                                                            <?=$item['Profile']['birthday']?>
                                                            <?else:?>
                                                            Secret
                                                            <?endif?>
                                                        </td>
                                                        <td>Interest : <a href="<?=$this->uri('/users/list/?interest=' . $item['Profile']['interest'])?>"><?=$item['Profile']['interest']?></a></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="item-content">
                                            <p><?=$item['Profile']['bio']?></p>
                                        </div>
                                    </div>
                                    <div class="item-absolute item-action">

                                        <?if(true || isset($item['Follow']) && $item['Follow']):?>
                                        <form <?=$this->formAttr($unfollowForm)?>>
                                            <?=$unfollowForm->restful();?>
                                            <?=$unfollowForm->helper('user_id', 'formHidden', array('class' => '', 'value' => $item['id']))?>
                                            <?=$unfollowForm->helper('follower_id', array('class' => ''))?>
                                            <?=$this->callback()?>
                                            <button class="btn btn-small item-action-main">Unfollow</button>
                                        </form>
                                        <?else:?>
                                        <form <?=$this->formAttr($form)?>>
                                            <?=$form->restful();?>
                                            <?=$form->helper('user_id', 'formHidden', array('class' => '', 'value' => $item['id']))?>
                                            <?=$form->helper('follower_id', array('class' => ''))?>
                                            <?=$this->callback()?>
                                            <button class="btn btn-small item-action-main">Follow</button>
                                        </form>
                                        <?endif?>


                                    </div>
                                </div>
                                <?endforeach?>
                            </div><!--activity-list end-->

                            </div><!--page main left end-->
                            <div class="span3">
                                <div class="page-extra">
                                    <?=$this->widget('Epic', 'widgets/userextra', $this->vars())?>
                                </div>
                            </div><!--page main right end-->
                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside')?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->

