<?
$this->headTitle('Epicurissimo compass | communauté privé pour les pros et les connaisseur du gastronomie et vin', 'SET');
$item = $this->item;
$form = new User\Form\LoginForm();
$form
->setView($this)
->useSubFormGroup()
->setMethod('post')
->setAction($this->uri('/login/'))
->bind($item)
->prepare();

$loginResult = $this->flashMessenger()->setNamespace('login-result')->getMessages();
$loginResult = $loginResult ? $loginResult[0] : array();
?>
<div class="bg bg-0">
    <div class="container">
        <div id="bg-0" class="guide"></div>
       <div class="loginblock loginformblock auto-login">
           <form <?=$this->formAttr($form)?> class="form">
                <?=$form->restful();?>
                <?if(isset($this->query['callback'])):?>
                <input name="callback" type="hidden" value="<?=$this->query['callback']?>" />
                <?endif?>
                <?if($loginResult):?>
                    <div class="alert alert-error">
                        <?if($loginResult->getCode() == -1):?>
                        User not found.
                        <?elseif($loginResult->getCode() == -3):?>
                        Password not match
                        <?endif?>
                    </div>
                <?endif?>
                <div class="control-group <?=$form->isError('loginName') ? 'error' : '';?>">
                    <?=$form->helper('loginName', 'label', array('class' => 'control-label'))?>
                    <div class="controls">
                        <?=$form->helper('loginName', array('class' => ''))?>        
                        <div class="help-block"><?=$form->helper('loginName', 'formElementErrors')?></div>
                    </div>
                </div>
                <div class="control-group <?=$form->isError('inputPassword') ? 'error' : '';?>">
                    <?=$form->helper('inputPassword', 'label', array('class' => 'control-label'))?>
                    <div class="controls">
                        <?=$form->helper('inputPassword', array('class' => ''))?>        
                        <div class="help-block"><?=$form->helper('inputPassword', 'formElementErrors')?></div>
                    </div>
                </div>
                <div class="control-group <?=$form->isError('rememberMe') ? 'error' : '';?>">
                    <div class="controls">
                        <label class="checkbox"><?=$form->helper('rememberMe', array('class' => 'checkbox'))?> <?=$this->_('Remember Me');?></label>
                    </div>
                </div>
                <div class="control-group">
                    <button type="submit" class="btn btn-inverse"><?=$this->_('Login');?></button> <a href="/reset/" class="pull-right">Forgot Password</a>
                </div>
                <hr />
                <div class="control-group">
                    <a href="<?=$this->uri('/oauth/', array('r' => $this->serverUrl() . '/login/oauth/', 'service' => 'twitter', 'version' => 1))?>" class="btn btn-small"><i class="icon-twitter"></i> Login by Twitter</a>
                    <a href="<?=$this->uri('/oauth/', array('r' => $this->serverUrl() . '/login/oauth/', 'service' => 'facebook',))?>" class="btn btn-small pull-right"><i class="icon-facebook-sign"></i> Login by Facebook</a>
                </div>
            </form>
        </div>
        <div class="loginblock block-text-1">
            <div class="typo">
                <p>Epicurissimo is a private network connecting all those involved in the world of Gastronomy and Fine Drinks, and a trusted place for professionals and connoisseurs to meet, connect, stay informed, showcase their work, find experts, share ideas, ask questions, find jobs and make business.</p>
                <p><a href="/reg" class="pull-right">Membership Request</a></p>
            </div>
        </div>
    </div>
</div>

<div class="bg bg-1">
    <div class="container">
        <div id="bg-1" class="guide"></div>

        <div class="loginblock block-1 hide">
        </div>
        <div class="loginblock block-2 hide">
        </div>
        <div class="loginblock block-6"></div>
        <div class="loginblock block-7"></div>
        <div class="loginblock block-text-2">
            <div class="typo">
                <p>"The gentle art of gastronomy is a friendly one. It hurdles the language barrier, makes friends among civilized people, and warms the heart."</p>
                <p class="rightalign">---Samuel Chamberlain</p>
            </div>
        </div>
    </div>
</div>

<div class="bg bg-2">
    <div class="container">
        <div id="bg-2" class="guide"></div>
        <div class="loginblock block-3 hide">
        </div>
        <div class="loginblock block-4 hide">
        </div>
        <div class="loginblock block-text-2 nobg">
            <div class="typo">
                <p>"Wine is earth's answer to the sun."</p>
                <p class="rightalign">---Margaret Fuller</p>
            </div>
        </div>
    </div>
</div>

<div class="bg bg-3">
    <div class="container">
        <div id="bg-3" class="guide"></div>
    </div>
        <div class="loginblock block-text-3">
            <div class="typo">
                <p>"Let schoolmasters puzzle their brain, with grammar, nonsense, and learning; Good liquor, I stoutly maintain,  gives genius better discerning."</p>
                <p class="rightalign">---Oliver Goldsmith</p>
            </div>
        </div>
</div>

<div class="bg bg-4">
    <div class="container">
        <div id="bg-4" class="guide"></div>
    </div>
        <div class="loginblock block-text-2 nobg">
            <div class="typo">
                <p>Highballs, high heels, girls’ guide to the art of cocktails.</p>
            </div>
        </div>
</div>

<div class="bg bg-5">
    <div class="container">
        <div id="bg-5" class="guide"></div>
    </div>
        <div class="loginblock block-text-1 nobg">
            <div class="typo">
                <p>"To Travel is To Live."</p>
                <p class="rightalign">---Hans Christian Andersen</p>
            </div>
        </div>
</div>

<div class="bg bg-6">
    <div class="container">
        <div id="bg-6" class="guide"></div>
    </div>
        <div class="loginblock block-text-5 nobg">
            <div class="typo">
                <p>"Small cheer and great welcome makes a merry feast."</p>
                <p class="rightalign">---William Shakespeare</p>
            </div>
        </div>
</div>

<!-- Modal -->
<div id="welcome-modal" class="modal hide fade typo" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="welcome-modal">Congratulations</h3>
    </div>
    <div class="modal-body">
        <p>Congratulations! You have successfully registered as a member of Epicurissimo. Conformation letter bas been sent to your E-mail address, Please check your mail box and confirm your E-mail address.</p>
        <p>Once you confirm your E-mail address, please use the email address and password to login Epicurissimo.</p>
        <p>* If you can not find the conformation letter, please chech the junk mailbox.</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
</div>


<script>
eva.ready(function(){
    var widthStep = [1024, 1280, 1366, 1440, 1920];
    var heightStep = [640, 680, 640, 780, 960];
    var imgDir = "<?=$this->assets('/module/epic/img')?>";
    var i = 0;

    var setBg = function(){
        var screenWidth = $(document).width();
        for(i in widthStep){
                if(screenWidth < widthStep[i]){
                    break;
                }
        }
        $(".bg").height(heightStep[i]);
        $(".bg").each(function(index){
                var bgDir = 'url("' + imgDir + '/' + widthStep[i] + '/' + 'bg' + index + '.jpg")';
                $(this).css('background-image', bgDir);
        });
    }

    setBg();

    var url = eva.parseUri();
    if(url.queryKey.reg){
            $('#welcome-modal').modal({
                    show : true
            });
    }

    $(window).resize(function(){
        setBg();
    });
});
</script>
