<?php
$title = 'Edit album';
$this->headTitle($title);
?>
<h1><?=$this->escape($title); ?></h1>
<?
$form = \Eva\Api::_()->getForm('\Blog\Form\PostForm')->init(array(
	'action' => $this->uri('/admin/blog/'),
	'method' => 'get',
	'values' => $this->post
));
?>

<form class="form-horizontal" <?=$this->formAttr($form)?>>
	<?=$form->restful();?>
	<?=$this->formInput($form->get('id'));?>
	<?//=$this->formInput($form->get('security'));?>
	<fieldset>
		  <div class="control-group">
		    <label class="control-label"><?=$this->formLabel($form->get('title'));?></label>
			<div class="controls docs-input-sizes">
			  <?=$this->formInput($form->get('title'))?>
			  <p class="help-block">Title</p>
			</div>
		  </div>
		  <div class="control-group">
			<label class="control-label"><?=$this->formLabel($form->get('status'));?></label>
			<div class="controls docs-input-sizes">
			  <?=$this->formSelect($form->get('status'))?>
			  
			  <p class="help-block">Default is </p>
			</div>
		  </div>
		  <div class="control-group">
            <label for="textarea" class="control-label"><?=$this->formLabel($form->get('content'));?></label>
            <div class="controls">
			  <?=$this->formTextarea($form->get('content'))?>
            </div>
          </div>
		  <div class="control-group">
			<label class="control-label"><?=$this->formLabel($form->get('codeType'));?></label>
			<div class="controls">
			  <?=$this->formRadio($form->get('codeType'))?>
			</div>
		  </div>

<!--
		  <div class="control-group">
			<label for="inlineCheckboxes" class="control-label">Inline checkboxes</label>
			<div class="controls">
			  <label class="checkbox inline">
				<input type="checkbox" value="option1" id="inlineCheckbox1"> 1
			  </label>
			  <label class="checkbox inline">
				<input type="checkbox" value="option2" id="inlineCheckbox2"> 2
			  </label>
			  <label class="checkbox inline">
				<input type="checkbox" value="option3" id="inlineCheckbox3"> 3
			  </label>
			</div>
		  </div>
		  <div class="control-group">
			<label for="optionsCheckboxList" class="control-label">Checkboxes</label>
			<div class="controls">
			  <label class="checkbox">
				<input type="checkbox" value="option1" name="optionsCheckboxList1">
				Option one is this and that&mdash;be sure to include why it's great
			  </label>
			  <label class="checkbox">
				<input type="checkbox" value="option2" name="optionsCheckboxList2">
				Option two can also be checked and included in form results
			  </label>
			  <label class="checkbox">
				<input type="checkbox" value="option3" name="optionsCheckboxList3">
				Option three can&mdash;yes, you guessed it&mdash;also be checked and included in form results
			  </label>
			  <p class="help-block"><strong>Note:</strong> Labels surround all the options for much larger click areas and a more usable form.</p>
			</div>
		  </div>
		  <div class="control-group">
			<label class="control-label">Radio buttons</label>
			<div class="controls">
			  <label class="radio">
				<input type="radio" checked="" value="option1" id="optionsRadios1" name="optionsRadios">
				Option one is this and that&mdash;be sure to include why it's great
			  </label>
			  <label class="radio">
				<input type="radio" value="option2" id="optionsRadios2" name="optionsRadios">
				Option two can is something else and selecting it will deselect option one
			  </label>
			</div>
		  </div>
-->
		  <div class="form-actions">
			<button class="btn btn-primary" type="submit">Submit</button>
			<button class="btn">Cancel</button>
		  </div>
		</fieldset>
</form>
