<?
$post = $this->post;
$title = $post['id'] ? 'Edit Post' : 'Create Post';
$method = $post['id'] ? 'put' : 'post';
$this->headTitle($title, 'SET');
if($this->form){
	$form = $this->form;
} else {
	$form = Eva\Api::_()->getForm('\Blog\Form\PostForm');
}

$form->init(array(
	'action' => $this->uri('/admin/blog/'),
	'method' => $method,
	'values' => $this->post
));

$form->mergeInvalid();
?>

<div class="page-header">
<h1><?=$title?></h1>
</div>

<form class="form-horizontal" <?=$this->formAttr($form)?>>
	<?=$form->restful();?>
	<?=$this->formInput($form->get('id'));?>
	<?//=$this->formInput($form->get('security'));?>
	<fieldset>
			<div class="control-group <?=$form->get('title')->getMessages() ? 'error' : '';?>">
		    <label class="control-label"><?=$this->formLabel($form->get('title'));?></label>
			<div class="controls docs-input-sizes">
			  <?=$this->input($form->get('title'), array('class' => 'input-xlarge'))?>
			  <?foreach($form->get('title')->getMessages() as $message):?>
			  <p class="help-block"><?=$message?></p>
			  <?endforeach?>
			</div>
		  </div>
		  <div class="control-group">
			<label class="control-label"><?=$this->formLabel($form->get('status'));?></label>
			<div class="controls">
			<?=$this->input($form->get('status'), array(
				'type' => 'formSelect',
				'class' => 'span3',
			  ))?>
			</div>
		  </div>

		  <div class="control-group">
			<label class="control-label"><?=$this->formLabel($form->get('codeType'));?></label>
			<div class="controls">
			<?=$this->input($form->get('codeType'), array(
				'type' => 'formRadio',
				'class' => 'checkbox inline',
			  ))?>
			</div>
		  </div>
		  <div class="control-group">
            <label for="textarea" class="control-label"><?=$this->formLabel($form->get('visibility'));?></label>
			<div class="controls">
			<?=$this->input($form->get('visibility'), array(
				'type' => 'formSelect',
			  ))?>
            </div>
          </div>
		  <div class="control-group <?=$form->get('content')->getMessages() ? 'error' : '';?>">
            <label for="textarea" class="control-label"><?=$this->formLabel($form->get('content'));?></label>
			<div class="controls">
			<?=$this->input($form->get('content'), array(
				'type' => 'formTextarea',
				'class' => 'span10',
				'rows' => '15',
			  ))?>
			</div>
		    <?foreach($form->get('content')->getMessages() as $message):?>
		    <p class="help-block"><?=$message?></p>
		    <?endforeach?>
          </div>
		  <div class="form-actions">
			<button class="btn btn-primary" type="submit">Submit</button>
			<button class="btn">Cancel</button>
		  </div>
	</fieldset>
</form>
