<?
$post = $this->post;
$title = $post['id'] ? 'Edit Post' : 'Create Post';
$method = $post['id'] ? 'put' : 'post';
$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', $title);

if($this->form){
	$form = $this->form;
} else {
    if($post) {
        $form = Eva\Api::_()->getForm('\Blog\Form\PostEditForm');
    } else {
        $form = Eva\Api::_()->getForm('\Blog\Form\PostForm');
    }
}
$form->setSubForms(array(
    'Text' => array('Blog\Form\TextForm'),
));
$form->init(array(
    'action' => $this->uri('/admin/blog/'),
    'method' => $method,
    'values' => $this->post
));

$moduleConfig = \Eva\Api::_()->getModuleConfig('Blog');
//p($config);

//Form usage:
//is error
//$form->subForm('Text')->get('content')->getMessages() ? 'error' : '';
//$form->isError(array('Text', 'content'))


//$this->input($form->subForm('Text')->get('content'), array(
//    'type' => 'formTextarea',
//    'class' => 'span9',
//    'rows' => '15',
//))
//$form->input(array('Text', 'content), 'formTextarea', array('class' => 'span9','rows' => '15',))

//Print out error messages:
//foreach($form->subForm('Text')->get('content')->getMessages() as $message):
?>

<input id="flash-messenger" type="hidden" value="<?=is_array($this->flashMessenger) ? implode(',', $this->flashMessenger) : ''?>" />
<div id="post-edit-succeed" class="alert alert-success hide">
    <a href="#" data-dismiss="alert" class="close">x</a>
    <h4 class="alert-heading">Post Edit Succeed</h4>
</div>

<div id="post-edit-failed" class="alert alert-error hide">
    <a href="#" data-dismiss="alert" class="close">x</a>
    <h4 class="alert-heading">Post Edit Failed</h4>
</div>



<div class="row">
    <form <?=$this->formAttr($form)?>>
        <?=$form->restful();?>
        <?=$form->helper('id');?>
        <div class="span10">
            <div class="slate">
                <div class="page-header">
                    <?if($post):?>
                    <div class="btn-group pull-right">
                        <a href="<?=$this->uri('/blog/page/' . $post['urlName'])?>" class="btn">View</a>
                        <a href="<?=$this->uri('/admin/blog/create')?>" class="btn">Clear Cache</a>
                        <a href="<?=$this->uri('/admin/blog/remove/' . $post['id'], 'c', array('c' => $this->uri('/admin/blog/' . $post['id']))); ?>" class="btn">Delete</a>
                    </div>
                    <?endif?>
                    <h2><?=$title?></h2>
                </div>
                <fieldset class="">
                    <div class="control-group <?=$form->isError('title') ? 'error' : '';?>">
                        <?=$form->helper('title', 'label', array('class' => 'control-label'))?>
                        <div class="controls docs-input-sizes">
                            <?=$form->helper('title', array('class' => 'span9'))?>
                            <div class="help-block"><?=$form->helper('title', 'formElementErrors')?></div>
                        </div>
                    </div>

                    <div class="control-group <?=$form->isError(array('Text', 'content')) ? 'error' : '';?>">
                        <!--<?=$form->helper(array('Text', 'content'), 'label', array('class' => 'control-label'))?>-->


                        <div id="editor-left" class="controls">
                            <div class="btn-toolbar markdown-toolbar">
                                <div class="btn-group">
                                    <span class="btn"  data-original-title="Bold - Ctrl+B"><i class="icon-bold"></i></span>
                                    <span class="btn"  data-original-title="Italic - Ctrl+I"><i class="icon-italic"></i></span>
                                </div>
                                <div class="btn-group">
                                    <span class="btn"  data-original-title="Link - Ctrl+L"><i class="icon-link"></i></span>
                                    <span class="btn"  data-original-title="Blockquote - Ctrl+Q"><i class="icon-blockquote"></i></span>
                                    <span class="btn"  data-original-title="Code Sample - Ctrl+K"><i class="icon-code"></i></span>
                                    <span class="btn"  data-original-title="Image - Ctrl+G"><i class="icon-picture"></i></span>
                                </div>
                                <div class="btn-group">
                                    <span class="btn"  data-original-title="Numbered List - Ctrl+O"><i class="icon-list"></i></span>
                                    <span class="btn"  data-original-title="Bulleted List - Ctrl+U"><i class="icon-bullet-list"></i></span>
                                    <span class="btn"  data-original-title="Heading - Ctrl+H"><i class="icon-header"></i></span>
                                    <span class="btn"  data-original-title="Horizontal Rule - Ctrl+R"><i class="icon-hr-line"></i></span>
                                </div>
                                <div class="btn-group">
                                    <span class="btn"  data-original-title="Undo - Ctrl+Z" disabled=""><i class="icon-undo"></i></span>
                                    <span class="btn"  data-original-title="Redo - Ctrl+Y" disabled=""><i class="icon-share-alt"></i></span>
                                </div>
                                <div class="btn-group">
                                    <span class="btn fullscreen" data-original-title="Full Screen"><i class="icon-fullscreen"></i></span>
                                </div>
                            </div>
                            <?=$form->helper(array('Text', 'content'), 'formTextarea', array('class' => 'span9 editor-markdown','rows' => '15',))?>
                        </div>
                        <div id="editor-right" class="markdown-preview"></div>
                        <div class="help-block"><?=$form->helper(array('Text', 'content'), 'formElementErrors')?></div>

                    </div>
                </fieldset>
            </div>
        </div><!--span10 end-->

        <div class="span5">
            <div class="slate">
                <div class="page-header">
                    <h3>Post Setting</h3>
                </div>
                <fieldset class="form-horizontal">

                    <div class="control-group <?=$form->isError('urlName') ? 'error' : '';?>">
                        <?=$form->helper('urlName', 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper('urlName', array('class' => 'input-xlarge'))?>
                            <div class="help-block"><?=$form->helper('urlName', 'formElementErrors')?></div>
                        </div>
                    </div>


                    <div class="control-group <?=$form->isError('urlName') ? 'error' : '';?>">
                        <?=$form->helper('status', 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper('status', 'formSelect')?>
                            <div class="help-block"><?=$form->helper('status', 'formElementErrors')?></div>
                        </div>
                    </div>

                    <div class="control-group <?=$form->isError('urlName') ? 'error' : '';?>">
                        <?=$form->helper('codeType', 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper('codeType', 'formRadio', array('class' => 'checkbox inline'))?>
                            <div class="help-block"><?=$form->helper('codeType', 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError('urlName') ? 'error' : '';?>">
                        <?=$form->helper('visibility', 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper('visibility', 'formSelect')?>
                            <div class="help-block"><?=$form->helper('visibility', 'formElementErrors')?></div>
                        </div>
                    </div>

                </fieldset>
            </div>
        </div><!--span5 end-->

        <div class="span10 listing-buttons">
            <button class="btn btn-info btn-large">Save Post</button>
        </div>
    </form>
</div>
