<?
$title = 'Posts List';
$this->headTitle($title, 'SET');
if($this->form){
	$form = $this->form;
} else {
    $form = Eva\Api::_()->getForm('\Blog\Form\PostSearchForm');
}
$form->init(array(
    'action' => $this->uri('/admin/blog/'),
    'method' => 'get',
    'values' => $this->query
));

$lableMap = array(
    'draft' => '',
    'published' => 'label-success',
    'pending' => 'label-warning',
);

?>

<div class="row">
    <div class="span10">
        <div class="slate">
            <form <?=$this->formAttr($form)?> class="form-inline">
                <?=$form->helper('keyword', array('class' => 'input-large', 'placeholder' => 'Keyword...'))?>
                <?=$form->helper('status', 'formSelect', array('class' => 'span2'))?>
                <?=$form->helper('visibility', 'formSelect', array('class' => 'span2'))?>
                <button class="btn" type="submit">Filter Posts</button>
            </form>
        </div>
    </div>
</div>


<div class="row">
    <div class="span10 listing-buttons">
        <div class="btn-group pull-right">
            <a href="<?=$this->uri('/admin/blog/create')?>" class="btn btn-info">Add New Post</a>
        </div>
        <div class="btn-group pull-left">
            <span class="btn"><input type="checkbox" class="checkall" /></span>
            <button data-toggle="dropdown" class="btn dropdown-toggle">
                Status
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li><a href="">Published</a></li>
                <li><a href="">Draft</a></li>
                <li><a href="">Pending</a></li>
            </ul>
        </div>
    </div>

    <div class="span10">
        <div class="slate">
            <div class="page-header">
                <div class="btn-group pull-right">
                    <a href="<?=$this->uri('/admin/blog/', 'Qq', array(
                            'Q' => $this->query,
                            'q' => array(
                                'order' => 'idasc',
                                'page' => '',
                            ),
                        ));?>" class="btn"><i class="icon-arrow-up"></i> Id</a>
                    <a href="<?=$this->uri('/admin/blog/create')?>" class="btn"><i class="icon-arrow-down"></i> Title</a>
                    <a href="<?=$this->uri('/admin/blog/create')?>" class="btn"><i class="icon-arrow-down"></i> Update Time</a>
                </div>
                <h2><?=$title?></h2>
            </div>

            <table class="orders-table table">
                <thead>
                    <tr>
                        <th class="span1">
                        </th>
                        <th>Post Name</th>
                        <th class="span1">Order</th>
                        <th class="actions">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?if($this->posts):?>
                    <?foreach($this->posts as $key=>$post):?>
                    <tr id="post_<?=$post['id'] ?>">
                        <td>
                            <input type="checkbox" class="checkall" name="post_ids[]" value="<?=$post['id'] ?>" />
                            <input type="hidden" name="post_id[]" class="reorder_post_id" value="<?=$post['id'] ?>" />
                        </td>	
                        <td>
                            <a href="<?=$this->uri('/admin/blog/' . $post['id'])?>" class="title"><?=$post['title'] ?></a>
                            <span class="label <?=$lableMap[$post['status']]?>"><?=$post['status']?></span>
                            <?if($post['visibility'] == 'private'):?>
                            <span class="label label-important">private</span>
                            <?endif?>
                            <p>
                            <span class="meta"><?=$post['user_name'] ?> <?=$post['createTime'];?></span>
                            </p>
                        </td>
                        <td>
                            <input tabindex="<?=$key+1 ?>" type="text" class="order span1" size="2" maxlength="3" name="orderNumber[]" value="<?=$post['orderNumber'] ? $post['orderNumber'] : "0" ?>" />
                        </td>
                        <td class="actions">
                            <a href="<?=$this->uri('/admin/blog/remove/' . $post['id'], 'c', array('c' => $this->uri('/admin/blog', array('page' => $this->page)))); ?>" class="btn btn-small btn-danger">Delete</a>
                            <a href="<?=$this->uri('/blog/page/' . $post['urlName'])?>" class="btn btn-small">View</a>
                            <a href="<?=$this->uri('/admin/blog/' . $post['id'])?>" class="btn btn-small">Edit</a>
                        </td>
                    </tr>
                    <?endforeach;?>
                    <?endif;?>
                </tbody>
            </table>
        </div>
    </div><!--span10 end-->

    <div class="span10">
        <?if($this->paginator):?>
        <?=$this->paginator->setPath('/admin/blog/')?>
        <?$this->baseQuery = (array) $this->query?>
        <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
        <?endif;?>
    </div>

</div>
