<?
$title = $this->_('Post List');
$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', $title);
if($this->form){
	$form = $this->form;
} else {
    $form = Eva\Api::_()->getForm('\Blog\Form\PostSearchForm');
}
$form->init(array(
    'action' => $this->uri('/admin/blog/'),
    'method' => 'get',
    'values' => $this->query
));

$lableMap = array(
    'draft' => '',
    'published' => 'label-success',
    'pending' => 'label-warning',
    'deleted' => 'label-inverse',
);

?>
<div class="row">
    <div class="span10">
        <div class="slate">
            <form <?=$this->formAttr($form)?> class="form-inline">
                <?=$form->helper('keyword', array('class' => 'input-large', 'placeholder' => 'Keyword...'))?>
                <?=$form->helper('status', 'formSelect', array('class' => 'span2'))?>
                <?=$form->helper('visibility', 'formSelect', array('class' => 'span2'))?>
                <?=$form->helper('category', 'formSelect', array(
                    'class' => 'span2',
                    'value_options' => $this->action('Blog\Api\Controller\CategoryController', 'selectAction'),
                ), array('replace' => false, 'i18n' => false))?>
                <button class="btn" type="submit"><?=$this->_('Filter Posts')?></button>
            </form>
        </div>
    </div>
</div>


<div class="row">
    <div class="span10 listing-buttons">
        <div class="btn-group pull-right">
            <a href="<?=$this->uri('/admin/blog/create')?>" class="btn btn-info"><?=$this->_('Add New Post')?></a>
        </div>
        <form action="<?=$this->uri('/admin/blog/multi/')?>" method="post" class="pull-left" data-multiform="post">
            <input type="hidden" name="id" class="multiform-container-main" value="" />
            <input type="hidden" name="order" class="multiform-container" value="" />
            <div class="btn-group">
                <span class="btn"><input type="checkbox" class="multiform-checker" /></span>
                <span data-toggle="dropdown" class="btn dropdown-toggle">
                    <?=$this->_('Status')?>
                    <span class="caret"></span>
                </span>
                <ul class="dropdown-menu">
                    <li><a href="#" class="multiform-submiter" data-multiform-action="<?=$this->uri('/admin/blog/multi/status/published')?>"><?=$this->_('Published')?></a></li>
                    <li><a href="#" class="multiform-submiter" data-multiform-action="<?=$this->uri('/admin/blog/multi/status/draft')?>"><?=$this->_('Draft')?></a></li>
                    <li><a href="#" class="multiform-submiter" data-multiform-action="<?=$this->uri('/admin/blog/multi/status/pending')?>"><?=$this->_('Pending')?></a></li>
                    <li><a href="#" class="multiform-submiter" data-multiform-action="<?=$this->uri('/admin/blog/multi/status/deleted')?>"><?=$this->_('Deleted')?></a></li>
                </ul>
                <a href="#" class="btn multiform-submiter" data-multiform-action="<?=$this->uri('/admin/blog/multi/reorder')?>"><?=$this->_('Re-Order')?></a>
            </div>
        </form>
    </div>

    <div class="span10">
        <div class="slate">
            <div class="page-header">
                <div class="btn-group pull-right">
                    <span data-toggle="dropdown" class="btn dropdown-toggle">
                        <?=$this->_('Order')?> <span class="caret"></span>
                    </span>
                    <ul class="dropdown-menu">
                        <li><a href="<?=$this->uri('/admin/blog/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'idasc',),));?>" class=""><i class="icon-arrow-up"></i> <?=$this->_('Id')?></a></li>
                        <li><a href="<?=$this->uri('/admin/blog/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'iddesc',),));?>" class=""><i class="icon-arrow-down"></i> <?=$this->_('Id')?></a></li>
                        <li><a href="<?=$this->uri('/admin/blog/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'titleasc',),));?>" class=""><i class="icon-arrow-up"></i> <?=$this->_('Title')?></a></li>
                        <li><a href="<?=$this->uri('/admin/blog/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'titledesc',),));?>" class=""><i class="icon-arrow-down"></i> <?=$this->_('Title')?></a></li>
                        <li><a href="<?=$this->uri('/admin/blog/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'timeasc',),));?>" class=""><i class="icon-arrow-up"></i> <?=$this->_('Time')?></a></li>
                        <li><a href="<?=$this->uri('/admin/blog/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'timedesc',),));?>" class=""><i class="icon-arrow-down"></i> <?=$this->_('Time')?></a></li>
                    </ul>
                </div>
                <h2><?=$title?></h2>
            </div>

            <table class="orders-table table">
                <thead>
                    <tr>
                        <th class="span1">
                        </th>
                        <th><?=$this->_('Post Title')?></th>
                        <th class="span1"><?=$this->_('Order')?></th>
                        <th class="actions"><?=$this->_('Actions')?></th>
                    </tr>
                </thead>
                <tbody>
                    <?if($this->posts):?>
                    <?foreach($this->posts as $key=>$post):?>
                    <tr class="">
                        <td>
                            <input name="id" type="checkbox" class="multiform-item-checkbox"  data-multiform="post" data-multiform-itemid="<?=$post['id'] ?>" value="<?=$post['id'] ?>" />
                        </td>	
                        <td>
                            <a href="<?=$this->uri('/admin/blog/' . $post['id'])?>" class="title"><?=$post['title'] ?></a>
                            <span class="label <?=$lableMap[$post['status']]?>"><?=$this->_($post['status'])?></span>
                            <?if($post['visibility'] == 'private'):?>
                            <span class="label label-important"><?=$this->_('private')?></span>
                            <?endif?>
                            <p>
                            <span class="meta"><?=$post['user_name'] ?> <?=$post['createTime'];?></span>
                            </p>
                        </td>
                        <td>
                            <input name="order" tabindex="<?=$key+1 ?>" type="text" class="span1 multiform-item-input" size="2" maxlength="3"  data-multiform="post" data-multiform-itemid="<?=$post['id'] ?>" value="<?=$post['orderNumber'] ? $post['orderNumber'] : "0" ?>" />
                        </td>
                        <td class="actions">
                            <a href="<?=$this->uri('/admin/blog/remove/' . $post['id'], 'c', array('c' => $this->uri('/admin/blog', array('page' => $this->page)))); ?>" class="btn btn-small btn-danger"><?=$this->_('Delete')?></a>
                            <a href="<?=$this->uri('/blog/page/' . $post['urlName'])?>" class="btn btn-small"><?=$this->_('View')?></a>
                            <a href="<?=$this->uri('/admin/blog/' . $post['id'])?>" class="btn btn-small"><?=$this->_('Edit')?></a>
                        </td>
                    </tr>
                    <?endforeach;?>
                    <?endif;?>
                </tbody>
            </table>
        </div>
    </div><!--span10 end-->

    <div class="span10">
        <?if($this->paginator):?>
        <?=$this->paginator->setPath('/admin/blog/')->setBaseQuery($this->query);?>
        <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
        <?endif;?>
    </div>

</div>
