<?
$title = 'Admin Reset Password';
$this->headTitle($title, 'SET');

if($this->form){
	$form = $this->form;
} else {
    $form = new User\Form\ResetForm();
}
$form->setView($this)
    ->setMethod('put')
     ->setAction($this->uri('/admin/user/reset'))
     ->bind($this->item)
     ->prepare();
?>

<div class="slate">
    <form class="form-horizontal" <?=$this->formAttr($form)?> >
        <?=$form->restful();?>
        <header class="page-header">
        <h3>Reset Password</h3>
        </header>
        <fieldset>
            <div class="control-group <?=$form->isError('email') ? 'error' : '';?>">
                <?=$form->helper('email', 'label', array('class' => 'control-label'))?>
                <div class="controls">
                    <?=$form->helper('email', array('class' => 'input-xlarge'))?>
                    <div class="help-block"><?=$form->helper('email', 'formElementErrors')?></div>
                </div>
            </div>
            <div class="form-actions">
                <button class="btn btn-primary" type="submit">Reset</button>
            </div>
        </fieldset>
    </form>
</div>
