<!DOCTYPE html>
<!-- Variation 1 -->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta charset="utf-8" />
        <?=$this->headTitle()?>
        <!--[if lt IE 9]>
        <meta http-equiv="PRAGMA" content="NO-CACHE" />
        <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
        <link rel="stylesheet" href="assets/css/ie.css" />
        <![endif]-->
        <?=$this->headMeta()?>

        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
        <script type="text/javascript" src="<?=$this->assets('/module/epic/js/placeholder.js')?>"></script>  
        <script type="text/javascript" src="<?=$this->assets('/module/epic/js/supersized.3.2.7.min.js')?>"></script>
        <script type="text/javascript" src="<?=$this->assets('/module/epic/js/form.js')?>"></script>
        <script type="text/javascript" src="<?=$this->assets('/module/epic/js/subscribe.js')?>"></script>

        <link href='http://fonts.googleapis.com/css?family=Philosopher' rel='stylesheet' type='text/css'>
        <link href="<?=$this->assets('/module/epic/css/coming.css')?>" media="all" rel="stylesheet" type="text/css" />
        <?=$this->evajs()?>

        <script type="text/javascript">
            jQuery(function($){
                    jQuery.supersized({
                            slides:
                            [	
                            {image:'<?=$this->assets('/module/epic/img/bg.jpg')?>'}
                            ]
                    });
            });
        </script>

        <script type="text/javascript">
            //Animate Pull Down Content
            $(function() {
                    $('#open').click(function(){
                            $('#pull_down_content').animate({'top':'0px'},1000);
                            $('#open').fadeTo('slow', 0); 
                    });
                    $('#close').click(function(){
                            $('#pull_down_content').animate({'top':'-800px'},1000);
                            $('#open').fadeTo('slow', 1);
                    });

                    $('.h1, .h2, .heading').click(function(){
                            $('#pull_down_content').animate({'top':'0px'},1000);
                            $('#open').fadeTo('slow', 0); 
                    });
            });
        </script>
    </head>

    <body>
        <div id="container">
            <!-- Pull Down -->
            <div id="pull_down_content">
                <div class="about">
                    <div class="dropdown_heading"><?=$this->_('About Us')?></div>
                    <!-- About Us -->
                    <p>
                    <?=$this->_('Epicurissimo is a private network and online publication, a trusted place for professionals and connoisseurs of gastronomy and fine drinks to meet, connect, stay informed, showcase their work, find experts, share ideas, ask questions, find jobs and make business.')?></p>

                    <div class="nav">
                        <a href="<?=$this->uri('/pages/terms')?>"><?=$this->_('Terms & Conditions')?></a> |
                        <a href="<?=$this->uri('/pages/privacy')?>"><?=$this->_('Privacy Policy')?></a> |
                        <a href="<?=$this->uri('/pages/contact')?>"><?=$this->_('Contact')?></a>
                    </div>
                    <div class="social">
                        <!-- Social Links -->
                        <ul id="social">
                            <li class="facebook">
                            <a href="https://www.facebook.com/pages/Epicurissimo-Compass/478175602201443" title="Facebook"></a>
                            </li>
                            <li class="twitter">
                            <a href="https://twitter.com/Epicurissimo" title="Twitter"></a>
                            </li>
                            <li class="google">

                            <a href="https://plus.google.com/102220617896813322867" title="Google+"></a>
                            </li>
                            <li class="vimeo">
                            <a href="http://pinterest.com/pin/524739794052354407/" title="Pinterest"></a>
                            </li>
                            <li class="skype">
                            <a href="http://weibo.com/2936625884" title="Weibo"></a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div id="contactForm" class="contact">
                    <!-- Contact Us -->
                    <div class="dropdown_heading"><?=$this->_('Contact Us')?></div>

                    <form class="pulldowncontact" method="post" action="<?=$this->assets('/module/epic/php/submit-form-ajax.php')?>">
                        <input type="text" id="email" class="text-input" name="email" placeholder="<?=$this->_('your email address')?>" />
                        <br />
                        <span id="errorEmail" class="formError"></span>

                        <textarea name="message" placeholder="<?=$this->_('type your message here')?>" id="message" class="message"></textarea>
                        <span id="errorMessage" class="formError"></span>
                        <div class="complete">
                            <input type="submit" value="<?=$this->_('Send')?>" name="submit" id="submit" class="submit" />
                            <span id="formProgress" class="formProgress"></span>
                        </div>
                    </form>

                </div>

                <!-- Close Pull Down -->
                <a href="#" class="button_up" id="close"></a>
            </div>
            <!-- End Drop Down -->
            <!-- Open Pull Down-->
            <a href="#" class="button_down" id="open"><?=$this->_('About & Contact')?></a>
        </div>
        <!-- Black Horizontal Banner -->
        <div id="banner">
            <div id="wrapper">
                <!-- White Horizontal Rule -->
                <div class="rule"></div>

                <!-- Left block information -->
                <div class="leftinfo">
                </div>
                <!-- Right block information -->
                <div class="rightinfo">
                    <?if(isset($_GET['reg']) && $_GET['reg']):?>
                    <a href="<?=$this->uri('/')?>"><?=$this->_('Back')?></a>
                    <?endif?>
                </div>

                <div class="heading">
                    <!-- Coming soon main text -->
                    <img src="<?=$this->assets('/module/epic/css/img/logofull.png')?>" height="90"  />    
                </div>

                <div id="countdown">
                    <!-- Countdown -->
                </div>

                <div class="signup_wrap">
                    <?if(isset($_GET['reg']) && $_GET['reg']):?>
                    <div class="signup">
                        <a href="<?=$this->uri('/reg/connoisseur')?>">
                            <?=$this->_('Sign Up as')?><br >
                            <span><?=$this->_('Connoisseur')?></span>
                            <small><?=$this->_('Share Inspire Connect Inform Enjoy')?></small>
                        </a>
                    </div>
                    <div class="signup last">
                        <a href="<?=$this->uri('/reg/professional')?>">
                            <?=$this->_('Sign Up as')?> <br >
                            <span><?=$this->_('Professional')?></span>

                            <!--<small>Show Your Works, Exchange Ideas, Get Connected, Develop Your Career</small>-->
                            <small><?=$this->_('Show Your Works, Get Connected')?></small>
                        </a>
                    </div>
                    <?else:?>
                    <div class="signup">
                        <a href="<?=$this->uri('/reg?reg=1')?>">
                            <?=$this->_('Sign Up as')?><br >
                            <span><?=$this->_('Individual Member')?></span>
                        </a>
                    </div>
                    <div class="signup last">
                        <a href="<?=$this->uri('/reg/corporate')?>">
                            <?=$this->_('Sign Up as')?> <br >
                            <span><?=$this->_('Corporate Member')?></span>
                        </a>
                    </div>
                    <?endif?>
                    <!--
                    <div class="signup last"><a href="<?=$this->uri('/reg/corporate')?>">
                            Pre Sign Up as <br >
                            <span>Corporate</span>
                    </a></div>
                    -->
                </div>
                <div class="rule2">
                    <!-- Bottom White horizontal rule -->
                </div>
            </div>
        </div>
    </body>
</html>
