<?
$title = 'File Edit';
$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', 'File Edit');

if($this->form){
	$form = $this->form;
} else {
    $form = Eva\Api::_()->getForm('File\Form\FileEditForm');
}
$form->init(array(
    'action' => $this->uri('/admin/form'),
    'method' => 'put',
    'values' => $this->file
));
?>

<div class="row">
    <form <?=$this->formAttr($form)?>>
        <?=$form->restful();?>
        <?=$form->helper('id')?>
        <div class="span10">
            <div class="slate">
                <div class="page-header">
                    <div class="btn-group pull-right">
                        <a href="<?=$file['Url']?>" class="btn">Download File</a>
                        <a href="<?=$this->uri('/admin/file/remove/' . $file['id'], 'c', array('c' => $this->uri('/admin/file/' . $file['id']))); ?>" class="btn">Delete</a>
                    </div>
                    <h2><?=$title?></h2>
                </div>
            </div>
        </div><!--span10 end-->

        <div class="span5">
            <div class="slate">
                <div class="page-header">
                    <h3>Edit File Info</h3>
                </div>
                <fieldset class="form-horizontal">

                    <div class="control-group <?=$form->isError('title') ? 'error' : '';?>">
                        <?=$form->helper('title', 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper('title', array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper('title' ,'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError('originalName') ? 'error' : '';?>">
                        <?=$form->helper('originalName', 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper('originalName', array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper('originalName' ,'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError('description') ? 'error' : '';?>">
                        <?=$form->helper('description', 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper('description', 'formTextarea', array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper('description', 'formElementErrors')?></div>
                        </div>
                    </div>

                    <div class="form-actions">
                        <button class="btn btn-info btn-large">Save</button>
                    </div>
                </fieldset>
            </div>
        </div><!--span5 end-->

        <div class="span5">
            <div class="slate">
                <div class="page-header">
                    <h3>File Info</h3>
                </div>
                <dl class="well dl-horizontal">
                    <dt>File Original Name</dt>
                    <dd><?=$file['originalName']?></dd>
                    <dt>File Size:</dt>
                    <dd><?=$file['ReadableFileSize']?></dd>
                    <dt>File Hash:</dt>
                    <dd><?=$file['fileHash']?></dd>
                    <dt>File Upload Time:</dt>
                    <dd><?=$file['createTime']?></dd>
                    <?if($file['isImage']):?>
                    <dt>Image Width:</dt>
                    <dd><?=$file['imageWidth']?> px</dd>
                    <dt>Image Height:</dt>
                    <dd><?=$file['imageHeight']?> px</dd>
                    <?endif?>
                </dl>

            </div>
        </div><!--span5 end-->

    </form>
</div><!--row end-->
