<?
$title = 'File Management';
$this->headTitle($title, 'SET');
$this->textDelay('breadcrumbText', 'File Management');
if($this->form){
	$form = $this->form;
} else {
    $form = Eva\Api::_()->getForm('\File\Form\FileSearchForm');
}
$form->init(array(
    'action' => $this->uri('/admin/file/'),
    'method' => 'get',
    'values' => $this->query
));

$lableMap = array(
    'draft' => '',
    'published' => 'label-success',
    'pending' => 'label-warning',
    'deleted' => 'label-inverse',
);

function getFileTypeIcon($ext)
{
    if(file_exists(EVA_PUBLIC_PATH . '/static/lib/icon/filetypes/' . $ext . '.png')){
        return '/lib/icon/filetypes/' . $ext . '.png';
    }
    return '/lib/icon/filetypes/_blank.png';
}
?>
<div class="row">
    <div class="span10">
        <div class="slate">
            <form <?=$this->formAttr($form)?> class="form-inline">
                <?=$form->helper('keyword', array('class' => 'input-large', 'placeholder' => 'Keyword...'))?>
                <?=$form->helper('status', 'formSelect', array('class' => 'span2'))?>
                <?//=$form->helper('visibility', 'formSelect', array('class' => 'span2'))?>
                <button class="btn" type="submit">Filter Files</button>
            </form>
        </div>
    </div>
</div>


<div class="row">
    <div class="span10 listing-buttons">
        <div class="btn-group pull-right">
            <a href="<?=$this->uri('/admin/file/upload')?>" class="btn btn-info">Upload File</a>
        </div>
        <form action="<?=$this->uri('/admin/file/multi/')?>" method="post" class="pull-left" data-multiform="post">
            <input type="hidden" name="id" class="multiform-container-main" value="" />
            <input type="hidden" name="order" class="multiform-container" value="" />
            <div class="btn-group">
                <span class="btn"><input type="checkbox" class="multiform-checker" /></span>
                <span data-toggle="dropdown" class="btn dropdown-toggle">
                    Status
                    <span class="caret"></span>
                </span>
                <ul class="dropdown-menu">
                    <li><a href="#" class="multiform-submiter" data-multiform-action="<?=$this->uri('/admin/file/multi/status/published')?>">Published</a></li>
                    <li><a href="#" class="multiform-submiter" data-multiform-action="<?=$this->uri('/admin/file/multi/status/draft')?>">Draft</a></li>
                    <li><a href="#" class="multiform-submiter" data-multiform-action="<?=$this->uri('/admin/file/multi/status/pending')?>">Pending</a></li>
                    <li><a href="#" class="multiform-submiter" data-multiform-action="<?=$this->uri('/admin/file/multi/status/deleted')?>">Deleted</a></li>
                </ul>
                <a href="#" class="btn multiform-submiter" data-multiform-action="<?=$this->uri('/admin/file/multi/reorder')?>">Re-Order</a>
            </div>
        </form>
    </div>

    <div class="span10">
        <div class="slate">
            <div class="page-header">
                <div class="btn-group pull-right">
                    <span data-toggle="dropdown" class="btn dropdown-toggle">
                        Order
                        <span class="caret"></span>
                    </span>
                    <ul class="dropdown-menu">
                        <li><a href="<?=$this->uri('/admin/file/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'idasc',),));?>" class=""><i class="icon-arrow-up"></i> Id</a></li>
                        <li><a href="<?=$this->uri('/admin/file/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'iddesc',),));?>" class=""><i class="icon-arrow-down"></i> Id</a></li>
                        <li><a href="<?=$this->uri('/admin/file/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'titleasc',),));?>" class=""><i class="icon-arrow-up"></i> Title</a></li>
                        <li><a href="<?=$this->uri('/admin/file/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'titledesc',),));?>" class=""><i class="icon-arrow-down"></i> Title</a></li>
                        <li><a href="<?=$this->uri('/admin/file/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'timeasc',),));?>" class=""><i class="icon-arrow-up"></i> Time</a></li>
                        <li><a href="<?=$this->uri('/admin/file/', 'dq', array('Q' => $this->query, 'q' => array('order' => 'timedesc',),));?>" class=""><i class="icon-arrow-down"></i> Time</a></li>
                    </ul>
                </div>
                <h2><?=$title?></h2>
            </div>

            <table class="orders-table table">
                <thead>
                    <tr>
                        <th class="span1">
                        </th>
                        <th>File Name</th>
                        <th class="span1">
                        </th>
                        <th class="span1">Order</th>
                        <th class="actions">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?if($files):?>
                    <?foreach($files as $key=>$file):?>
                    <tr class="">
                        <td>
                            <input name="id" type="checkbox" class="multiform-item-checkbox"  data-multiform="post" data-multiform-itemid="<?=$file['id'] ?>" value="<?=$file['id'] ?>" />
                        </td>	

                        <td>
                            <a href="<?=$this->uri('/admin/file/' . $file['id'])?>" class="title"><?=$file['title'] ?></a>
                            <span class="label <?=$lableMap[$file['status']]?>"><?=$file['status']?></span>
                            <span class="label"><?=$file['fileExtension']?></span>
                            <p>
                            <span class="meta"><?=$file['user_name'] ?> <?=$file['createTime'];?></span>
                            </p>
                        </td>
                        <td>
                            <?if($file['isImage']):?>
                            <img src="<?=$this->link(getFileTypeIcon($file['fileExtension']))?>" alt="<?=$file['fileExtension']?>" />
                            <?else:?>
                            <img src="<?=$this->link(getFileTypeIcon($file['fileExtension']))?>" alt="<?=$file['fileExtension']?>" />
                            <?endif?>
                        </td>	
                        <td>
                            <input name="order" tabindex="<?=$key+1 ?>" type="text" class="span1 multiform-item-input" size="2" maxlength="3"  data-multiform="post" data-multiform-itemid="<?=$file['id'] ?>" value="<?=$file['orderNumber'] ? $file['orderNumber'] : "0" ?>" />
                        </td>
                        <td class="actions">
                            <a href="<?=$this->uri('/admin/file/remove/' . $file['id'], 'c', array('c' => $this->uri('/admin/file', array('page' => $this->page)))); ?>" class="btn btn-small btn-danger">Delete</a>
                            <a href="<?=$this->uri('/admin/file/' . $file['id'])?>" class="btn btn-small">Edit</a>
                        </td>
                    </tr>
                    <?endforeach;?>
                    <?endif;?>
                </tbody>
            </table>
        </div>
    </div><!--span10 end-->

    <div class="span10">
        <?if($this->paginator):?>
        <?=$this->paginator->setPath('/admin/file/')->setBaseQuery($this->query);?>
        <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
        <?endif;?>
    </div>

</div>
