<?
$this->headTitle($this->post['title'], 'SET');
?>
<div class="container">
    <div id="singletitle" class="page-header typo">
        <h1><?=$this->_($post['title'])?></h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="span12">
            <div class="well">
                <div class="hero-unit typo">
                    <?if($post['urlName'] == 'about'):?>
                    <?$locale = \Eva\Api::_()->getServiceManager()->get('translator')->getLocale();?>
                    <?if($locale == 'en'):?>
                    <p>Epicurissimo is a private network connecting all those involved in the world of Gastronomy and Fine Drinks. </p>

                    <p>Gathered here is a joint group of professionals and connoisseurs : from celebrate chefs, reputed sommeliers to legendary barmans ; from gastronomic critics, journalists to food stylists, from ulterior Oenophilia, spirit aficionado to gourmet connoisseurs.</p>

                    <p>Epicurissimo offer a trusted place and multitude of facilities for professionals and connoisseurs to meet, connect, stay informed, showcase their work, find experts, share ideas, ask questions, find jobs and make business.</p>

                    <p>To optimize users experiences, the membership of Epicurissimo is reserved for eligible organizations/individuals, and currently by invitation only.</p>
                    <?elseif($locale == 'fr'):?>
                    <p>Epicurissimo est un réseau privé reliant tous les acteurs du monde de la gastronomie et des boissons fines.</p>

                    <p>Réunis ici est un groupe mixte de professionnels et d'amateurs: des chefs célèbres, des sommeliers réputés, barmans légendaires; de critiques gastronomiques, journalistes, de stylistes culinaires, de ultime oenophilia, et des gourmets.</p>

                    <p>Epicurissimo offrir un lieu de confiance et une multitude d'équipements pour les professionnels et les amateurs de se rencontrer, se connecter, s'informer, de présenter leur travail, trouver des experts, échanger des idées, poser des questions, trouver un emploi et faire des affaires.</p>

                    <p>Pour optimaliser l'expérience des utilisateurs, l'adhésion de Epicurissimo est réservée aux organisations / individus qualifies et seulement sur invitation.</p>

                    <?elseif($locale == 'zh'):?>
                    <p>Epicurissimo是一个关于美食及美酒的私密高端网络平台。“飨”是其中文版意译，取享受、享乐、设盛宴款待等意思。</p>

                    <p>这里聚集着全球行业内的专业人士及行家：从顶尖主厨、知名侍酒师 到 传奇酒保；从美食评论家、行业记者 到 顶级食品造型师；从酒品尝家, 美酒爱好者 到 美食鉴赏家。</p>

                    <p>Epicurissimo为职业人士和行家们提供了一个专业和可靠的交流平台，供大家交流、结识、获得最新信息、展示个人作品、寻找专家，分享创意、提出和解答问题，、寻找工作及促成业务往来。</p>

                    <p>为了创造一个私密的空间和提升用户体验，Epicurissimo的会员只提供给那些受邀参与的机构和个人。目前关闭普通会员注册，仅采用邀请制。</p>

                    <?elseif($locale == 'zh_TW'):?>
                    <p>Epicurissimo是一個關於美食及美酒的私密高端網絡平臺。“饗”是其中文版意譯，取享受、享樂、設盛宴款待等意思。</p>

                    <p>這裏聚集著全球行業內的專業人士及行家：從頂尖主廚、知名侍酒師 到 傳奇酒保；從美食評論家、行業記者 到 頂級食品造型師；從酒品嘗家, 美酒愛好者 到 美食鑒賞家。</p>

                    <p>Epicurissimo為職業人士和行家們提供了一個專業和可靠的交流平臺，供大家交流、結識、獲得最新信息、展示個人作品、尋找專家，分享創意、提出和解答問題，、尋找工作及促成業務往來。</p>

                    <p>為了創造一個私密的空間和提升用戶體驗，Epicurissimo的會員只提供給那些受邀參與的機構和個人。目前關閉普通會員註冊，僅采用邀請制。</p>

                    <?endif?>

                    <?else:?>
                    <?=$post['Text']['content'];?>
                    <?endif?>
                </div>
            </div>
        </div>
    </div>
</div>
