<?
$title = 'Share';
$this->headTitle($title, 'SET');
$user = $this->user;
$items = $this->items;
$paginator = $this->paginator;
$paginator = $paginator ? $paginator->toArray() : array();
?>
<div class="page-inner">

    <div class="container">
        <div class="profile-main">
            <div class="row">
                <div class="span12">
                    <div id="feed-wall">
                        <?if($items):?>
                        <?foreach($items as $item):?>
                        <div class="box thumbnail ">
                            <a href="<?=$this->uri('/feed/' . $item['messageHash'])?>">
                                <?if($item['File']):?>
                                <img src="<?=$this->thumb($item['File'][0]['Thumb'], array('w_250'))?>" alt="" class="" />
                                <?endif?>
                            </a>
                            <div class="text-wrap">
                            <p class="text">
                            <?=$item['ContentHtml']?>
                            </p>
                            </div>
                        </div>
                        <?endforeach;?>
                        <?endif?>
                    </div>
                    <?if(isset($paginator['nextPage']) && $paginator['nextPage']):?>
                    <div class="pager">
                        <a href="<?=$this->uri('/share/?page=' . $paginator['nextPage'])?>" class="btn load-more span11">More</a>
                    </div>
                    <?endif?>
                </div>



            </div><!--row end-->
        </div><!--profil-main end-->
    </div><!--container end-->
</div><!--page inner end-->


<script>
    /*
    $(function(){
            eva.loader(eva.s('/lib/js/jquery/jquery.masonry.js'), function(){
                    var $container = $('#feed-wall');
                    $container.imagesLoaded( function(){
                            $container.masonry({
                                    itemSelector : '.box'
                            });
                    });
            });


    });
    */
</script>

