<?
$post = $this->post;
$title = $this->_('Delete Post');
$this->headTitle($title, 'SET');
$form = Eva\Api::_()->getForm('\Blog\Form\PostDeleteForm');

$form->init(array(
	'action' => $this->uri('/admin/blog/'),
	'method' => 'delete',
	'values' => $this->post
));
?>

<?if($post):?>
<div class="alert alert-block">
   <h2 class="alert-heading"><?=$title?></h2>
   <p><?=$this->_(array('Post %title% will be deleted, are you sure?', $post['title']))?></p>
   <p>
		<form class="form-horizontal" <?=$this->formAttr($form)?>>
			<?=$form->restful();?>
			<?=$this->formInput($form->get('id'));?>
            <button class="btn btn-danger" type="submit"><?=$this->_('Delete')?></button>
            <input name="callback" type="hidden" value="<?=$this->callback?>" />
            <a class="btn" href="<?=$this->callback?>"><?=$this->_('Go Back')?></a>
   		</form>
	</p>
</div>
<?else:?>
<div class="alert alert-success container">
    <h2 class="alert-heading"<?=$this->_('>Post have been deleted')?></h2>
</div>
<?endif?>
