<?
$items = $this->items;
$viewAsGuest = $this->viewAsGuest;

$form = new Activity\Form\MessageCreateForm();
$form->useSubFormGroup()
     ->setMethod('post')
     ->setView($this)
     ->setAction($this->uri('/event/feed/'))
     ->prepare();

$joinForm = new Event\Form\EventUserForm();
$joinForm
->setView($this)
->setMethod('post')
->setAction($this->uri('/event/join/'))
->prepare();

$unjoinForm = clone $joinForm;
$unjoinForm->setMethod('delete');
?>
<div class="event-detail media">
    <a class="pull-left" href="<?=$this->uri('/event/' . $item['urlName']);?>">
        <?if($item['File']):?>
        <img class="media-object" src="<?=$this->thumb($item['File'][0]['Thumb'], array('c_fill', 'h_240', 'w_240'))?>" width="240" />
        <?else:?>
        <img class="media-object" src="<?=$this->assets('/module/epic/img/event-default-l.png')?>" width="240" />
        <?endif?>
    </a>
    <div class="media-body">
        <h4 class="media-heading"><a href="<?=$this->uri('/event/' . $item['urlName']);?>"><?=$item['title'];?></a></h4>
        <div class="media typo">
            <dl class="dl-horizontal">
                <dt>Start Time:</dt>
                <dd><?=$item['startDay']?> <?=$item['startTime'] ? $item['startTime'] : null?></dd>
                <dt>End Time:</dt>
                <dd><?=$item['endDay']?> <?=$item['endTime'] ? $item['endTime'] : null?></dd>
                <dt>City:</dt>
                <dd><?=$item['city']?></dd>
                <?if($item['location']):?>
                <dt>Location:</dt>
                <dd><?=$item['location']?></dd>
                <?endif?>
                <?if($item['Tags']):?>
                <dt>Tags:</dt>
                <dd>
                <?foreach($item['Tags'] as $tag):?>
                <a href="<?=$this->uri('/events/list/?tag=' . $tag['tagName']);?>" class="label"><?=$tag['tagName']?></a>
                <?endforeach?>
                </dd>
                <?endif?>
                <dt>Event Owner</dt>
                <dd><?=$item['user_name']?></dd>
            </dl>
            <p><span class="highlight"><?=$item['Count']['memberCount']?></span> Members Joined</p>
            <p>
            <?if(isset($item['Join']) && $item['Join']['user_id'] == $item['user_id']):?>
            <?elseif(isset($item['Join']) && $item['Join'] && $item['Join']['user_id'] != $item['user_id']):?>
            <form <?=$this->formAttr($unjoinForm)?>>
                <?=$unjoinForm->restful();?>
                <?=$unjoinForm->helper('event_id', 'formHidden', array('class' => '', 'value' => $item['id']))?>
                <?=$unjoinForm->helper('user_id', array('class' => ''))?>
                <?=$this->callback()?>
                <button class="btn btn-small item-action-main btn btn-orange icon-minus-sign"> <?=$this->_('Quit')?></button>
            </form>
            <?elseif($item['memberEnable'] && ($item['memberLimit'] > $item['Count']['memberCount'] || $item['memberLimit'] == 0)):?>
            <form <?=$this->formAttr($joinForm)?>>
                <?=$joinForm->restful();?>
                <?=$joinForm->helper('event_id', 'formHidden', array('class' => '', 'value' => $item['id']))?>
                <?=$joinForm->helper('user_id', array('class' => ''))?>
                <?=$this->callback()?>
                <button class="btn btn-small item-action-main btn btn-orange icon-user"> <?=$this->_('RVSP')?></button>
            </form>
            <?endif?> 
            </p>
        </div>
    </div>
</div>

<div class="page-header border-header">
    <h3>Event Members</h3>
</div>

<div class="side-user-list">
    <ul class="thumbnails">
        <?if($this->members):?>
        <?foreach($this->members as $member):?>
        <li>
        <a class="thumbnail" href="<?=$this->uri('/user/' . $member['User']['userName'])?>">
            <img src="<?=$member['User']['Avatar'] ? $this->thumb($member['User']['Avatar']['Thumb'], array('h_30', 'w_30', 'c_fill')) :  $this->assets('/module/epic/img/default_avatar.png')?>" alt="userface"  width="30" height="30" />
        </a>
        </li>
        <?endforeach;?>
        <?endif;?>
    </ul>
</div>

<div class="page-header border-header">
    <h3>Event Description</h3>
</div>


<article class="typo typocn">
<?=isset($item['Text']['content']) ? $item['Text']['content'] : ''?>
</article>

<div class="page-header border-header">
    <small class="pull-right"><a href="" class="btn btn-small btn-gray"><i class="icon-plus"></i>Add image</a></small>
    <h3>Event Images</h3>
</div>


<div>
    <ul class="thumbnails">
        <?for($i=0;$i<8;$i++):?>
        <li class="thumbnail"><a href="#"><img src="https://lh4.googleusercontent.com/-24AS3_MK3m0/UKLldhEDMoI/AAAAAAAARCM/u_zXkKeb9vo/s144-p/DSC_0065.jpg" alt=""></a></li>
        <?endfor?>
    </ul>
</div>

<div class="page-header border-header">
    <h3>Event Talking</h3>
</div>


<div class="event-activities">
    <div class="row">
        <form id="activity-form" <?=$this->formAttr($form)?> class="activity-box span7">
            <?=$form->helper('messageType', 'formHidden', array('class' => ''))?>        
            <?=$form->helper('reference_id', array('class' => ''))?>
            <?=$form->helper(array('MessageFile', 'file_id'), 'formHidden', array('class' => ''))?>
            <input type="hidden" name="event_id" value="<?=$this->item['id']?>"> 
            <?=$this->callback()?>
            <fieldset class="form">
                <div class="activity-box-wrap">
                    <div class="activity-box-content">
                        <?=$form->helper('content', 'formTextarea', array('class' => '', 'rows' => 5, 'value' => 'From Event :' . $this->serverUrl() . '/event/' . $this->item['urlName']))?>        
                    </div>
                    <div class="activity-box-buttons">
                        <a id="activity-box-image-button" class="activity-box-func activity-box-text" href="javascript:;" data-activity-text="Share Photo."><i class="icon-mini icon-picture"></i> Photo</a>
                        <a id="activity-box-video-button" class="activity-box-func" href="javascript:;" data-placement="bottom" rel="popover"><i class="icon-mini icon-facetime-video"></i> Video</a>
                        <label id="activity-box-sync-twitter" class="activity-box-func" title="Sync to Twitter"><i class="icon-mini icon-twitter"></i><input type="checkbox" /></label>
                        There are <span class="highlight highlight-large activity-box-count">140</span> letters left <button type="submit" class="btn btn-light-brown btn-large">Submit</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>

    <div class="activity-list vlist">
        <?foreach($items as $item):?>
        <div class="item">
            <a href="<?=$this->uri('/user/' . $item['User']['userName'])?>" title="" class="item-absolute item-userface">
                <img src="<?=$item['User']['Avatar'] ? $this->thumb($item['User']['Avatar']['Thumb'], array('h_30', 'w_30', 'c_fill')) :  $this->assets('/module/epic/img/default_avatar.png')?>" alt="userface"  width="30" height="30" class="img-rounded"/>
            </a>
            <div class="item-inline item-text span6">
                <div class="item-content">
                    <div class="item-title"><a href="<?=$this->uri('/user/' . $item['User']['userName'])?>" class="item-user"><?=$item['User']['userName']?></a> Said:</div>
                    <p><?=$item['ContentHtml']?></p>
                    <?if($item['File']):?>
                    <div class="item-image">
                        <p><a href="<?=$item['File'][0]['Thumb']?>" class="item-preview image" data-preview-type="image" data-url="<?=$this->thumb($item['File'][0]['Thumb'], array('w_400'))?>" data-width="400"><img src="<?=$this->thumb($item['File'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                    </div>
                    <?endif?>

                    <?if($item['Video']):$video = $item['Video'];?>
                    <div class="item-video">
                        <?if($video['thumbnail']):?>
                        <a href="<?=$video['url']?>" class="item-preview video" data-preview-type="video" data-url="<?=$video['swf']?>" data-width="<?=$video['width']?>" data-height="<?=$video['height']?>"><img src="<?=$video['thumbnail']?>" alt="video preview" class="img-polaroid" width="200" /><i class="icon-play btn-play"></i></a>
                        <?else:?>
                        <a href="<?=$video['url']?>" class="item-preview video" data-preview-type="video" data-url="<?=$video['swf']?>" data-width="<?=$video['width']?>" data-height="<?=$video['height']?>"><div class="video-no-preview"></div><i class="icon-play btn-play"></i></a>
                        <?endif?>
                    </div>
                    <?endif?>

                    <?if(isset($item['ForwardActivity']) && $item['ForwardActivity']): $subItem = $item['ForwardActivity'];?>
                    <div class="well">
                        <p><?=$subItem['ContentHtml']?></p>
                        <?if($subItem['File']):?>
                        <div class="item-image">
                            <p><a href="<?=$subItem['File'][0]['Thumb']?>"><img src="<?=$this->thumb($subItem['File'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                        </div>
                        <?endif?>
                        <div class="item-action">
                            <p class="pull-right"><a href="<?=$this->uri('/feed/' . $subItem['messageHash'])?>" class="" data-activity-comment="<?=$subItem['id']?>"><i class="icon-comment"></i> Comments (<span class="highlight"><?=$subItem['commentedCount']?></span>)</a></p>
                            <p class="pull-left">
                            <a href="<?=$this->uri('/feed/' . $subItem['messageHash'])?>"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($subItem['createTime'])?>" datetime="<?=$this->datetime()->isoTime($subItem['createTime'])?>"><?=$this->datetime($subItem['createTime'])?></time></a>
                            </p>
                        </div>
                    </div>
                    <?endif?>

                    <div class="item-action">
                        <p class="pull-right">
                        <a href="javascript:;" class="item-func remove <?=$viewAsGuest ? 'hide' : ''?>"><i class="icon-remove"></i> Delete</a>
                        <a href="javascript:;" class="item-func comment" data-activity-comment="<?=$item['id']?>"><i class="icon-comment"></i> Comments (<span class="highlight"><?=$item['commentedCount']?></span>)</a>
                        </p>
                        <p class="pull-right hide"><a href="#activity-form" class="item-func reference" data-activity-reference="<?=$item['id']?>" data-activity-text="@<?=$item['User']['userName']?> "><i class="icon-share-alt"></i> RT (<span class="highlight"><?=$item['transferredCount']?></span>)</a></p>
                        <p class="pull-left">
                        <a href="<?=$this->uri('/feed/' . $item['messageHash'])?>" class="item-id"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['createTime'])?>" datetime="<?=$this->datetime()->isoTime($item['createTime'])?>"><?=$this->datetime($item['createTime'])?></time></a>
                        </p>
                    </div>
                </div>

                <div class="item-remove-ajax">
                </div>
                <div class="item-sub-ajax">
                </div>
            </div>
        </div>
        <?endforeach?>

        <?if($this->paginator):?>
        <?=$this->paginator->setPath('/event/' . $this->item['urlName'] . '/')->setBaseQuery($this->query);?>
        <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
        <?endif;?>
    </div><!--activity-list end-->
</div>


<div id="video-popover" class="popover bottom">
    <div class="arrow"></div>
    <h3 class="popover-title">Add Video
        <span class="close">×</span>
    </h3>
    <div class="popover-content">
        <div class="form">
            <div class="input-append">
                <input name="url" class="input-medium" type="text" placeholder="Video Url..." />
                <button id="add-video" class="btn" type="button">Add</button>
            </div>
        </div>
        <div class="ajax-video-preview">
            <p>Support video sites: Youtube, Youku</p>
        </div>
    </div>
</div>
<?=$this->widget('File', 'file/index')?>
<script src="<?=$this->assets('/module/epic/js/feed.js')?>"></script>
