<?
$item = $this->item;
$album = $item;
$title = $item['id'] ? 'Edit Album' : 'Create Album';
$title = $this->_($title);
$this->headTitle($title, 'SET');
$items = $items->toArray();
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">
            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span6">
                                <div class="page-main-header">
                                    <a href="<?=$this->uri('/albums/create/')?>" class="btn btn-small btn-orange pull-right"><i class="icon-pencil"></i> Create New</a>
                                    <h3><?=$this->_($title)?> <?if($item['id']):?><a href="<?=$this->uri('/user/' . $this->user['userName'] . '/albums/' . $item['urlName'])?>" class="">[View]</a><?endif?></h3>
                                </div>
                                <div class="row-fluid">
                                    <?if($item['id']):?>
                                    <ul id="album-form-nav" class="nav nav-pills">
                                        <li><a href="<?=$this->uri('/albums/edit/' . $item['id'])?>#album-basic-form"><?=$this->_('Album Basic Info')?></a></li>
                                        <li><a href="<?=$this->uri('/albums/edit/' . $item['id'])?>#album-upload-form"><?=$this->_('Upload Photo')?></a></li>
                                        <li class="active"><a href="<?=$this->uri('/albums/photo/' . $item['id'])?>"><?=$this->_('Photo Management')?></a></li>
                                    </ul>
                                    <?endif?>
                                    <div class="tab-content">
                                        <div class="album-photos">
                                    <?if(count($items) > 0 )?>
                                    <?for($i=0;$i< ceil(count($items) / 3);$i++):?>
                                    <div class="row-fluid stack-row">
                                        <?for($j= ($i * 3);$j< (3 * ($i+1));$j++):?>
                                        <?if(isset($items[$j])){$item = $items[$j]['Image'];}else{continue;}?>
                                        <div class="thumbnail span4">
                                            <div>	
                                               <a href="<?=$this->thumb($item['Thumb'])?>"  class="gallery"  rel="event-album">
                                                <?if(isset($item['Thumb']) && $item['Thumb']):?>
                                                <img src="<?=$this->thumb($item['Thumb'], array('c_fill', 'w_180', 'h_180'))?>" width="100%" class="" />
                                                <?endif?>
                                            </a>
                                            </div>
                                            <p class="caption">
                                                <?if($album['cover_id'] != $item['id']):?>
                                                <a href="<?=$this->uri('/albums/cover/' . $album['id'] . '?file_id=' . $item['id'], 'c', array('c' => $this->uri('/albums/photo/' . $album['id'], array('page' => $this->page))))?>"><i class="icon-edit"></i> Set As Cover</a>
                                                <?endif;?>
                                                <a href="<?=$this->uri('/albums/imageremove/' . $album['id']  . '?file_id=' . $item['id'],'c', array('c' => $this->uri('/albums/photo/' . $album['id'], array('page' => $this->page))))?>"><i class="icon-remove"></i> Delete</a>
                                            </p>
                                        </div>
                                        <?endfor;?>
                                    </div>
                                    <?endfor;?>
                                </div><!--album-list end-->
                                    </div>
                                </div>

                            </div><!--page main left end-->
                            <div class="span3">
                                <div class="page-extra">
                                    <?=$this->widget('Epic', 'widgets/userextra', $this->vars())?>
                                </div>
                            </div><!--page main right end-->
                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside', $this->vars())?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->
