<?
$item = $this->item;
$title = $this->_('Delete Notice');
$this->headTitle($title, 'SET');
$form = new Notification\Form\NoticeDeleteForm();

$form->setView($this)
->setMethod('delete')
->setAction($this->uri('/notifications/remove/' . $item['message_id']))
->bind($item)
->prepare();
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span6">
                                <div class="page-main-header">
                                    <h3><?=$this->_($title)?></h3>
                                </div>

                                <?if($item):?>
                                <div class="alert alert-block">
                                    <h2 class="alert-heading"><?=$title?></h2>
                                    <p><?=$this->_('Notice will be deleted, are you sure?')?></p>
                                    <p>
		                            <form class="form-horizontal" <?=$this->formAttr($form)?>>
			                        <?=$form->restful();?>
			                        <?=$this->formInput($form->get('message_id'));?>
			                        <?=$this->formInput($form->get('user_id'));?>
                                    <button class="btn btn-danger" type="submit"><?=$this->_('Delete')?></button>
                                    <input name="callback" type="hidden" value="<?=$this->callback?>" />
                                    <a class="btn" href="<?=$this->callback?>"><?=$this->_('Go Back')?></a>
   		                            </form>
	                                </p>
                                </div>
                                <?else:?>
                                    <div class="alert alert-success container">
                                        <h2 class="alert-heading"<?=$this->_('>Message have been deleted')?></h2>
                                    </div>
                                <?endif?>
                            </div><!--page main left end-->
                            <div class="span3">
                                <div class="page-extra">
                                    <?=$this->widget('Epic', 'widgets/userextra')?>
                                </div>
                            </div><!--page main right end-->
                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside')?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->

