Dear <?=$this->user['userName']?>:

Welcome to join Epicurissimo's network of engaged experts and passionate connoisseurs of fine food and drinks.

As the art of living is a share pursuit, let's enjoy something, share something and create something. Epicurissimo helps you exchanging leads with experts, joining various events, and forming local groups with mind-liked fellows.



Get started:

You can access your account here with the email (name) and password: 

<?=$this->serverUrl('/account/active/?code=' . $this->code['code'])?>


If you have any questions, please don't hesitate to visit FAQ page or contact us: info@epicurissimomedia.com
