<?
$title = 'Conversation with ' . $this->user['userName'];
$title = $this->_($title);
$this->headTitle($title, 'SET');
$items = $this->items;
$message = $this->item;
if($this->form){
	$form = $this->form;
} else {
    $form = new Message\Form\MessageReplyForm();
}
$form->useSubFormGroup()
     ->setMethod('post')
     ->setView($this)
     ->setAction($this->uri('/message/'))
     ->bind($message)
     ->prepare();
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span6">
                                <div class="page-main-header">
                                    <h3><?=$this->_($title)?></h3>
                                </div>


                                <form <?=$this->formAttr($form)?> class="message-reply-form form row">

                                    <?=$form->restful();?>
                                    <input name="callback" type="hidden" value="<?=$this->uri('/messages/conversation/' . $this->user['userName'])?>" />
                                    <?=$form->helper(array('Conversation', 'recipient_id'), array('class' => ''))?>        
                                    <div class="control-group <?=$form->isError('body') ? 'error' : '';?> span5">
                                        <div class="controls">
                                            <?=$form->helper('body', 'formTextarea', array('class' => 'span5'))?>        
                                            <div class="help-block"><?=$form->helper('body', 'formElementErrors')?></div>
                                        </div>
                                    </div>
                                        <button type="submit" class="btn btn-light-brown btn-large span1"><?=$this->_('Reply')?></button>
                                </form>

                                <div class="message-list vlist">
                                    <?foreach($items as $item):?>
                                    <div class="item">
                                        <a href="<?=$this->uri('/messages/conversation/' . $item['Sender']['userName'])?>" title="" class="item-absolute item-userface">
                                            <img src="<?=$item['Sender']['Avatar'] ? $this->thumb($item['Sender']['Avatar']['Thumb'], array('h_60', 'w_60', 'c_fill')) :  $this->assets('/module/epic/img/default_avatar.png')?>" alt=""  width="60" height="60" class="img-rounded"/>
                                        </a>
                                        <div class="item-inline item-text span5">
                                            <div class="item-content">
                                                <?if($item['Sender']['id'] == $item['author_id']):?>
                                                <div class="item-title">To <a href="<?=$this->uri('/messages/conversation/' . $item['Recipient']['userName'])?>" class="item-user"><?=$item['Recipient']['userName']?></a> : </div>
                                                <?else:?>    
                                                <div class="item-title">From <a href="<?=$this->uri('/messages/conversation/' . $item['Sender']['userName'])?>" class="item-user"><?=$item['Sender']['userName']?></a> : </div>
                                                <?endif;?>
                                                <?=$item['Message']['body']?>
                                            </div>
                                            <div class="item-action">
                                                <p class="pull-right">
                                                <a href="<?=$this->uri('/messages/remove/' . $item['id'], 'c', array('c' => $this->uri('/messages/conversation/' . $this->user['userName']))); ?>" class=""><?=$this->_('Delete')?></a>
                                                </p>
                                                <p class="pull-left">
                                                <time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['createTime'])?>" datetime="<?=$this->datetime()->isoTime($item['createTime'])?>"><?=$this->datetime($item['createTime'])?></time>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <?endforeach?>

                                    <?if($this->paginator):?>
                                        <?=$this->paginator->setPath('/messages/conversation/' . $this->user['userName'])->setBaseQuery($this->query);?>
                                        <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                                    <?endif;?>
                                </div><!--activity-list end-->


                            </div><!--page main left end-->
                            <div class="span3">
                                <div class="page-extra">
                                    <?=$this->widget('Epic', 'widgets/userextra')?>
                                </div>
                            </div><!--page main right end-->
                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside')?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->

