<?
$item = $this->item;
$title = 'Messages';
$title = $this->_($title);
$this->headTitle($title, 'SET');
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span6">

                                <div class="page-main-header">
                                    <!--<a href="<?=$this->uri('/messages/send/')?>" class="btn btn-small btn-orange pull-right"><i class="icon-envelope-alt"></i> Send Message</a>-->
                                    <h3><?=$this->_($title)?></h3>
                                </div>

                                <div class="message-list vlist">
                                    <?foreach($items as $item):?>
                                    <div class="item">
                                        <a href="<?=$this->uri('/messages/conversation/' . $item['User']['userName'])?>" title="" class="item-absolute item-userface">
                                            <img src="<?=$item['User']['Avatar'] ? $this->thumb($item['User']['Avatar']['Thumb'], array('h_60', 'w_60', 'c_fill')) :  $this->assets('/module/epic/img/default_avatar.png')?>" alt=""  width="60" height="60" class="img-rounded"/>
                                        </a>
                                        <div class="item-inline item-text span4">
                                            <div class="item-content">
                                                <div class="item-title">
                                                    <?if($item['Conversation']['sender_id'] == $item['author_id']):?>
                                                    To
                                                    <?else:?>
                                                    From
                                                    <?endif;?>    
                                                    <a href="<?=$this->uri('/messages/conversation/' . $item['User']['userName'])?>" class="item-user"><?=$item['User']['userName']?></a> : 
                                                </div>
                                                <?=$item['Conversation']['Message']['body']?>
                                            </div>
                                            <div class="item-action">
                                                <p class="pull-right"><a href="<?=$this->uri('/messages/conversation/' . $item['User']['userName'])?>" title="" class="highlight">Reply</a></p>
                                                <?if($item['unreadCount'] > 0):?>
                                                <p class="pull-right"><a href="<?=$this->uri('/messages/conversation/' . $item['User']['userName'])?>" title="" class="highlight"><?=$item['unreadCount']?> unread messages</a></p>
                                                <?endif;?>
                                                <p class="pull-left">
                                                <time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['messageTime'])?>" datetime="<?=$this->datetime()->isoTime($item['messageTime'])?>"><?=$this->datetime($item['messageTime'])?></time>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <?endforeach?>

                                    <?if($this->paginator):?>
                                    <?=$this->paginator->setPath('/messages/')->setBaseQuery($this->query);?>
                                    <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                                    <?endif;?>
                                </div><!--activity-list end-->
                            </div><!--page main left end-->
                            <div class="span3">
                                <div class="page-extra">
                                    <?=$this->widget('Epic', 'widgets/userextra', $this->vars())?>
                                </div>
                            </div><!--page main right end-->
                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside')?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->

