<?
$this->headTitle($item['title'], 'SET');
$item = $this->item;
?>
<div class="page-content">
    <div id="blog">
        <div class="page-header large">
            <h1><a href="<?=$this->uri('/p/' . $item['id'])?>" rel="nofollow"><?=$item['title'] ?></a></h1>
        </div>

        <p class="copyright">
        <span class="pull-left">
            日志未经声明，均为<a href="https://plus.google.com/104171418568283484752?rel=author">AlloVince</a>原创。版权采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/2.5/cn/" target="_blank">『 知识共享署名-非商业性使用 2.5 许可协议』</a>进行许可。
        </span>
        <span class="share-btn pull-left">
            <span class="addthis_toolbox addthis_default_style ">
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_google_plusone_share"></a>
                <a class="addthis_button_sinaweibo"></a>
                <a class="addthis_button_douban"></a>
            </span>
            <script type="text/javascript">var addthis_config = {"data_track_addressbar":false};</script>
        </span>
        <span class="pull-left">
            <span id="google_translate_element"></span>
            <script type="text/javascript">
                function googleTranslateElementInit() {new google.translate.TranslateElement({pageLanguage: 'zh-CN', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');}
            </script>
        </span>


        </p>
        <article class="typo typocn">
        <?=$item['Text']['ContentHtml']?>
        <?if($item['Tags']):?>
        <hr />
        <p class="tags"> Tags :
        <?foreach($item['Tags'] as $tag):?>
        <a href="<?=$this->uri('/thinking/'. $tag['tagName'])?>" class="label tag"><?=$tag['tagName']?></a>
        <?endforeach?>
        </p>
        <p class="share"> Follow :
        <span data-url-wrap="http://avnpc.com/feed/"><i class="icon-social-rss"></i></span>
        <span data-url-wrap="https://github.com/AlloVince"><i class="icon-social-github-circled"></i></span>
        <span data-url-wrap="http://www.facebook.com/allovince"><i class="icon-social-facebook-squared"></i></span>
        <span data-url-wrap="https://twitter.com/intent/follow?source=followbutton&variant=1.0&screen_name=AlloVince"><i class="icon-social-twitter"></i></span>
        <span data-url-wrap="https://plus.google.com/104171418568283484752"><i class="icon-social-googleplus-rect"></i></span>
        <span data-url-wrap="http://weibo.com/avnpc"><i class="icon-social-weibo"></i></span>
        <span data-url-wrap="http://www.linkedin.com/in/qianxu"><i class="icon-social-linkedin-squared"></i></span>
        <span data-url-wrap="https://www.evernote.com/pub/allovince/Tech"><i class="icon-social-evernote"></i></span>
        </p>
        <?endif?>
        </article>

        <?if($item['Prev'] || $item['Next']):?>
        <div class="neighbors">
            <?if($item['Prev']):?>
            <a href="<?=$this->uri('/pages/' . $item['Prev']['urlName'])?>" class="prev" title="<?=$this->escapeHtmlAttr($item['Prev']['title'])?>"><span class="icon-ext icon-arrow-left"></span></a>
            <?else:?>
            <a href="#" class="prev" title="没有了"><span class="icon-ext icon-arrow-left"></a>
                <?endif;?>
                <div class="postdate">
                    <abbr class="gmtdate" title="本篇日志发布于：<?=$this->datetime($item['createTime']);?>">
                        <span class="month"><?=$this->datetime($item['createTime'], null, 'M');?></span>
                        <span class="day"><?=$this->datetime($item['createTime'], null, 'd');?></span>
                    </abbr>
                </div>
                <?if($item['Next']):?>
                <a href="<?=$this->uri('/pages/' . $item['Next']['urlName'])?>" class="next" title="<?=$this->escapeHtmlAttr($item['Next']['title'])?>"><span class="icon-ext icon-arrow-right"></span></a>
                <?endif;?>
            </div>
            <?endif;?>

            <?=$this->widget('Blog', 'comment/embed', $this->vars())?>
            <?if(count($this->comments) > 0):?>
            <div class="page-header large bordered">
                <h4>评论</h4>
            </div>
            <div class="comments">
                <div class="vlist texts img50">
                    <?foreach($this->comments as $key => $comment):?>
                    <div id="comment<?=$comment['id']?>" class="item <?=$key%2 !== 0 ? 'right' : ''?>">
                        <span class="item-absolute imgdelay figure userface" title=""><img class="thumbnail" alt="<?=$comment['user_name']?>" src="<?=$this->gravatarLink($comment['email'], 50)?>" /></span>
                        <div class="item-inline item-text">
                            <div class="well">
                                <div class="text-content">
                                    <?=$comment['ContentHtml']?>
                                </div>
                            </div>
                            <div class="item-absolute item-action">
                                <p class="margin15h pull-right">
                                <time datetime="<?=$this->datetime()->isoTime($comment['createTime'])?>" data-jstime="<?=$this->datetime()->jsTime($comment['createTime'])?>" class="agotime"><?=$this->datetime($comment['createTime'])?></time>
                                </p>
                                <p class="margin15h pull-left">
                                <?=$comment['user_name']?>
                                </p>
                            </div>
                        </div>
                    </div>
                    <?endforeach?>
                </div>
            </div><!-- box end-->
            <?endif?>
        </div><!--blog end-->

    </div>
