<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
    <?=$this->headTitle('Eva Engine')?>

	<!--[if IE]>
	<meta http-equiv="PRAGMA" content="NO-CACHE" />
	<![endif]-->
	<!--[if lt IE 9]>
	<![endif]-->
	
    <?=$this->headMeta()?>
</head>

<body class="">

<div id="page" class="page"><?=$this->content;?></div><!-- #page end-->

</body>
</html>
