<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
    <?=$this->headTitle()?>
    <?$this->link('/src/admin/css/bootstrap.css')?>
	<!--[if lt IE 9]>
	<meta http-equiv="PRAGMA" content="NO-CACHE" />
    <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
	<![endif]-->
    <?=$this->headMeta()?>
    <link href="<?=$this->link('/lib/css/bootstrap/bootstrap.min.css')?>" media="all" rel="stylesheet" type="text/css" />
	<style>
	body, h1, h2, h3, h4, h5, h6  {
		font-family:Microsoft YaHei,Trebuchet MS, Verdana, Helvetica, Arial, sans-serif;
	}
	</style>
</head>

<body class="">
	<div class="navbar"><div class="navbar-inner"><div class="container">
                <a class="brand" href="/">EvaEngine</a>	
    <ul class="nav">
        <li><a href="/"><?=$this->_('Home')?></a></li>
        <?if($this->hasModule('Blog')):?>
        <li><a href="/blog/"><?=$this->_('Blog')?></a></li>
        <?endif?>
        <?if($this->hasModule('User')):?>
        <li><a href="/user/"><?=$this->_('User')?></a></li>
        <?endif?>
	</ul>
    <ul class="nav pull-right">
        <li><a href="/admin/"><?=$this->_('Admin')?></a></li>
    </ul>
    </div></div></div>

<div id="page" class="page">
<?=$this->content;?>
</div><!-- #page end-->
</body>
</html>
