<?
$file = $this->file;
$title = $this->_('Delete File');
$this->headTitle($title, 'SET');
$form = Eva\Api::_()->getForm('\File\Form\FileDeleteForm');

$form->init(array(
    'action' => $this->uri('/admin/file/'),
	'method' => 'delete',
	'values' => $this->file
));
?>

<?if($file):?>
<div class="alert alert-block">
   <h2 class="alert-heading"><?=$title?></h2>
   <p><?=$this->_(array('File %title% will be deleted, are you sure?', $file['title']))?></p>
   <p>
		<form class="form-horizontal" <?=$this->formAttr($form)?>>
			<?=$form->restful();?>
			<?=$this->formInput($form->get('id'));?>
            <button class="btn btn-danger" type="submit"><?=$this->_('Delete')?></button>
            <input name="callback" type="hidden" value="<?=$this->callback?>" />
            <a class="btn" href="<?=$this->callback?>"><?=$this->_('Go Back')?></a>
   		</form>
	</p>
</div>
<?else:?>
<div class="alert alert-success container">
    <h2 class="alert-heading"><?=$this->_('File have been deleted')?></h2>
</div>
<?endif?>
